### PR TITLE
Fix pause-remove container

### LINKED ISSUE #317: failed to remove paused container
# Description of problem

```sh
$ docker run --name foo -dti debian bash && docker pause foo && docker rm -f foo
c6510b66d61f7cfff9a65bab8a08f583086a9fe46d4f4903bbf72b03e33f95d1
foo
Error response from daemon: Could not kill running container c6510b66d61f7cfff9a65bab8a08f583086a9fe46d4f4903bbf72b03e33f95d1, cannot remove - Cannot kill container c6510b66d61f7cfff9a65bab8a08f583086a9fe46d4f4903bbf72b03e33f95d1: unknown error after kill: /usr/bin/kata-runtime did not terminate sucessfully: Container c6510b66d61f7cfff9a65bab8a08f583086a9fe46d4f4903bbf72b03e33f95d1 not ready or running, cannot send a signal
: unknown
```

# Expected result

no errors

# Actual result

```
Error response from daemon: Could not kill running container c6510b66d61f7cfff9a65bab8a08f583086a9fe46d4f4903bbf72b03e33f95d1, cannot remove - Cannot kill container c6510b66d61f7cfff9a65bab8a08f583086a9fe46d4f4903bbf72b03e33f95d1: unknown error after kill: /usr/bin/kata-runtime did not terminate sucessfully: Container c6510b66d61f7cfff9a65bab8a08f583086a9fe46d4f4903bbf72b03e33f95d1 not ready or running, cannot send a signal
```

### PR DESCRIPTION
**Pull request by devimc**
Instead of pausing the sanbox, this patch just pauses the container
allowing the communication with the agent. The communication with the agent
should be still possible even if all containers are paused, because of we don't
know when a new container can be created in the same sandbox.

Depends-on: github.com/kata-containers/agent#246

fixes #317

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
kata-agent needs to be re-vendored

**Comment by katabuilder** [comment]
PSS Measurement:
Qemu: 142043 KB
Proxy: 6756 KB
Shim: 10867 KB

Memory inside container:
Total Memory: 2045972 KB
Free Memory:  2010720 KB

**Comment by katabuilder** [comment]
PSS Measurement:
Qemu: 141744 KB
Proxy: 6807 KB
Shim: 11174 KB

Memory inside container:
Total Memory: 2045972 KB
Free Memory:  2011216 KB

**Comment by katabuilder** [comment]
PSS Measurement:
Qemu: 144361 KB
Proxy: 6622 KB
Shim: 11117 KB

Memory inside container:
Total Memory: 2045972 KB
Free Memory:  2015264 KB

**Comment by devimc** [comment]
related to https://github.com/moby/moby/issues/37137

**Comment by katabuilder** [comment]
PSS Measurement:
Qemu: 144377 KB
Proxy: 6752 KB
Shim: 8769 KB

Memory inside container:
Total Memory: 2045972 KB
Free Memory:  2011272 KB

**Comment by katabuilder** [comment]
PSS Measurement:
Qemu: 141845 KB
Proxy: 4673 KB
Shim: 10822 KB

Memory inside container:
Total Memory: 2045972 KB
Free Memory:  2013332 KB

**Comment by devimc** [comment]
@kata-containers/runtime please take a look

File: virtcontainers/api.go [hunk 1]
```diff
@@ -653,3 +653,40 @@ func StatsContainer(sandboxID, containerID string) (ContainerStats, error) {
...
+	if err != nil {
+		return err
+	}
+	defer unlockSandbox(lockFile)
+
+	s, err := fetchSandbox(sandboxID)
+	if err != nil {
+		return err
+	}
+
```
Comment (sboeuf) [inline virtcontainers/api.go]: Get the container pointer from here, this way, you don't need to define sandbox functions for this. Let's avoid useless indirections.
This way, only
```go
func (c *Container) pause() error {}
func (c *Container) resume() error {}
```
are needed.

**Comment by sboeuf** [comment]
Thanks for the change @devimc 
LGTM

**Comment by devimc** [comment]
added unit test to fix code coverage, thanks

File: cli/kill.go [hunk 2]
```diff
@@ -103,9 +103,9 @@ func kill(containerID, signal string, all bool) error {
 		return err
 	}
 
-	// container MUST be created or running
-	if status.State.State != vc.StateReady && status.State.State != vc.StateRunning {
-		return fmt.Errorf("Container %s not ready or running, cannot send a signal", containerID)
+	// container MUST be created, running or paused
+	if status.State.State != vc.StateReady && status.State.State != vc.StateRunning && status.State.State != vc.StatePaused {
```
Comment (jodh-intel) [inline cli/kill.go]: I'd say this is ok, but it's on the verge of needing to be turned into a switch.

/me waits for laughter from @sboeuf for the use of "that word" ;)

Comment (sboeuf) [reply cli/kill.go]: Yeah could be a switch but I am fine with it ;)

Comment (jodh-intel) [reply cli/kill.go]: @sboeuf - I was referring to the amusing translation of the "v word" ;)

**Comment by katabuilder** [comment]
PSS Measurement:
Qemu: 162188 KB
Proxy: 6771 KB
Shim: 8851 KB

Memory inside container:
Total Memory: 2045972 KB
Free Memory:  1997624 KB

**Comment by sboeuf** [comment]
@devimc please rebase, as this is ready to be merged ;)

**Comment by katabuilder** [comment]
PSS Measurement:
Qemu: 163754 KB
Proxy: 4581 KB
Shim: 10852 KB

Memory inside container:
Total Memory: 2045972 KB
Free Memory:  2004640 KB

**Comment by devimc** [comment]
@sboeuf done, thanks
