### PR TITLE
virtcontainers: support vm factory in QEMU 4

### LINKED ISSUE #1747: vm-factory not working with qemu 4.0
While running the `integration/vm_factory/vm_templating_test.sh` with qemu v4.0.0, we have the following errors
```
kata-runtime[6584]: time="2019-05-27T17:11:44.535534622-05:00" level=info msg="{\"error\": {\"class\": \"GenericError\", \"desc\": \"Nested VMX virtualization does not support live migration yet\"}}" arch=amd64 command=create container=f88bd65f84356bb89702885ba24ca0fea4a30b5919279db91b56350bf3927ab6 name=kata-runtime pid=6584 source=virtcontainers subsystem=qmp
kata-runtime[6584]: time="2019-05-27T17:11:44.535702274-05:00" level=error msg="exec migration" arch=amd64 command=create container=f88bd65f84356bb89702885ba24ca0fea4a30b5919279db91b56350bf3927ab6 error="QMP command failed: Nested VMX virtualization does not support live migration yet" name=kata-runtime pid=6584 source=virtcontainers subsystem=qemu
kata-runtime[6584]: time="2019-05-27T17:11:44.537976786-05:00" level=warning msg="create vm factory failed" arch=amd64 command=create container=f88bd65f84356bb89702885ba24ca0fea4a30b5919279db91b56350bf3927ab6 error="QMP command failed: Nested VMX virtualization does not support live migration yet" name=kata-runtime pid=6584 source=katautils
```

### PR DESCRIPTION
**Pull request by devimc**
Turn off VMX if vm-factory is enabled since it's not migratable yet.
see https://bugzilla.redhat.com/show_bug.cgi?id=1689216

fixes #1747

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: virtcontainers/qemu_amd64.go [hunk 1]
```diff
@@ -129,6 +135,13 @@ func (q *qemuAmd64) cpuModel() string {
 	if q.nestedRun {
 		cpuModel += ",pmu=off"
 	}
+
+	// VMX is not migratable yet, see https://bugzilla.redhat.com/show_bug.cgi?id=1689216
+	// issue: https://github.com/kata-containers/runtime/issues/1750
```
Comment (jodh-intel) [inline virtcontainers/qemu_amd64.go]: How about turning this comment into a structured log call? That way:

- admins can see why performance may be suffering.
- We can tweak the [stale skip checker](https://github.com/kata-containers/tests/blob/master/.ci/kata-find-stale-skips.sh) to look at *all* github Kata issue URLs in the logs (and the code too I guess) and warn / error if it finds any that are closed as that's a sign we forgot to update something ;)

I'd just reference the Kata issue as that has the bugzilla on it.

Comment (jodh-intel) [reply virtcontainers/qemu_amd64.go]: https://github.com/kata-containers/tests/issues/1655 raised for the stale skip idea.

Comment (grahamwhaley) [reply virtcontainers/qemu_amd64.go]: ack that a log message might be nice.

**Comment by bergwolf** [comment]
@devimc, travis failed with:
```
virtcontainers/qemu_arch_base.go:113:2: `vmFactory` is unused (structcheck)
	vmFactory             bool
	^
```

**Comment by devimc** [comment]
/test

@bergwolf @jodh-intel changes applied, thanks

**Comment by amshinde** [comment]
@devimc Seeing some failures here: 
Opensuse: 
```
• Failure [30.798 seconds]
[4] Hotplug memory when create containers
[4] /tmp/jenkins/workspace/kata-containers-runtime-opensuse-15-PR/go/src/github.com/kata-containers/tests/integration/docker/mem_test.go:47
[4]   Hotplug memory when create containers
[4]   /tmp/jenkins/workspace/kata-containers-runtime-opensuse-15-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
[4]     hotplug memory when create containers should not fail [It]
[4]     /tmp/jenkins/workspace/kata-containers-runtime-opensuse-15-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
[4] 
[4]     Expected error:
[4]         <*strconv.NumError | 0xc00028c330>: {
[4]             Func: "Atoi",
[4]             Num: "",
[4]             Err: {s: "invalid syntax"},
[4]         }
[4]         strconv.Atoi: parsing "": invalid syntax
[4]     not to have occurred
```

**Comment by devimc** [comment]
@amshinde that's a weird error that occurred while docker integration tests were running, restarting suse CI
