### PR TITLE
devices: add per-device VFIO ids

### LINKED ISSUE #708: IOMMU groups with multiple devices
# Description of problem
When passing the VFIO device file corresponding to an IOMMU group comprised of multiple devices, the QMP `device_add` successfully adds the first device but fails to add any devices after that.

This seems to happen because only one device ID is generated per VFIO device file (`/dev/vfio/XX`). When attaching the PCI devices associated with this IOMMU group via the QMP `device_add` command, the `id` parameter is set to generated device ID resulting in the `Duplicate ID` error (see log below) for any PCI devices after the first one.

# Potential Fixes
- generate VFIO devices IDs per device/BDF rather than per device file/IOMMU group
- don't pass the `id` parameter to the `device_add` command since it's optional

# Log
CLI: `docker run --runtime=kata --device=/dev/vfio/34 --rm -it busybox` 

Device `15:00.0` has already been successfully attached with `id = vfio-97d2a47534f15ff4` (prior to this part of the log). This shows device `15:00.1` failing to hotplug since it shares the same `id`. 

time="2018-09-10T14:46:16.107445474-07:00" level=info msg="{\"error\": {\"class\": \"GenericError\", \"desc\": \"Duplicate ID 'vfio-97d2a47534f15ff4' for device\"}}" arch=amd64 command=create container=dd9219202646dd82c0d4ba829426da75a93ff995b763c5e623f4904bf2dee2ff name=kata-runtime pid=21953 source=virtcontainers subsystem=qmp
time="2018-09-10T14:46:16.107681462-07:00" level=error msg="failed to hotplug VFIO device" arch=amd64 command=create container=dd9219202646dd82c0d4ba829426da75a93ff995b763c5e623f4904bf2dee2ff error="QMP command failed" name=kata-runtime pid=21953 sandbox=dd9219202646dd82c0d4ba829426da75a93ff995b763c5e623f4904bf2dee2ff sandboxid=dd9219202646dd82c0d4ba829426da75a93ff995b763c5e623f4904bf2dee2ff source=virtcontainers subsystem=sandbox vfio device BDF="15:00.1" vfio device ID=vfio-97d2a47534f15ff4
time="2018-09-10T14:46:16.107826113-07:00" level=error msg="Failed to add device" arch=amd64 command=create container=dd9219202646dd82c0d4ba829426da75a93ff995b763c5e623f4904bf2dee2ff error="QMP command failed" name=kata-runtime pid=21953 source=virtcontainers subsystem=device
time="2018-09-10T14:46:16.211620142-07:00" level=error msg="QMP command failed" arch=amd64 command=create container=dd9219202646dd82c0d4ba829426da75a93ff995b763c5e623f4904bf2dee2ff name=kata-runtime pid=21953 source=runtime

### PR DESCRIPTION
**Pull request by eguzman3**
Adds per-device VFIO ids allowing IOMMU groups with
multiple devices to be passed to qemu.

Fixes #708

Signed-off-by: Edward Guzman <eguzman@nvidia.com>

### CODE REVIEW

**Comment by amshinde** [comment]
Retriggering fedora build.

File: virtcontainers/device/drivers/vfio.go [hunk 1]
```diff
@@ -64,14 +65,14 @@ func (device *VFIODevice) Attach(devReceiver api.DeviceReceiver) error {
...
-	for _, deviceFile := range deviceFiles {
+	for i, deviceFile := range deviceFiles {
 		//Get bdf of device eg 0000:00:1c.0
 		deviceBDF, err := getBDF(deviceFile.Name())
 		if err != nil {
 			return err
 		}
 		vfio := &config.VFIODev{
-			ID:  utils.MakeNameID("vfio", device.DeviceInfo.ID, maxDevIDSize),
+			ID:  utils.MakeNameID("vfio", device.DeviceInfo.ID+strconv.Itoa(i), maxDevIDSize),
```
Comment (WeiZhang555) [inline virtcontainers/device/drivers/vfio.go]: Good find! This is a true bug, thanks!

Can you help to modify `device.DeviceInfo.ID+strconv.Itoa(i)` to `device.ID+strconv.Itoa(i)` ? I just realized `DeviceInfo` isn't necessary.

Comment (jodh-intel) [reply virtcontainers/device/drivers/vfio.go]: @WeiZhang555 - oh! We have two fields with the same information? Do we need to remove `GenericDevice.ID` so that we only have `GenericDevice.DeviceInfo.ID` then?

If we need to keep both:

- We should add a comment explaining why.
- We should have tests to ensure both `ID` values are the same.

Comment (WeiZhang555) [reply virtcontainers/device/drivers/vfio.go]: `DeviceInfo` is input data for creating a new device, `GenericDevice.ID` is the real device ID made by each device driver, in my original refactor, the `DeviceInfo` is designed to be throwed away and not stored, and `DeviceInfo` should be only for one-time use. 
But currently so many places are using `DeviceInfo`, and it is involved deeply, that's why I didn't do it.

But you remind me that it's better to do it earlier :smile: I'll take a look at it.

**Comment by sboeuf** [comment]
Ok merging this PR as it will fix multiple VFIO devices support!

**Comment by sboeuf** [comment]
@eguzman3 please backport to stable branches.

**Comment by eguzman3** [comment]
Backport to stable-1.2: https://github.com/kata-containers/runtime/pull/721
stable-1.1 doesn't appear to have this bug
