### PR TITLE
devices: Skip floppy drives while passing devices to guest

### LINKED ISSUE #1551: Failed to start privileged kata container
# Description of problem
Failed to start privileged kata container 
Failed cmd: 
docker run --privileged -ti -d centos

but this cmd will work well:
docker run  -ti -d centos

# Expected result

start kata container successfully;

# Actual result
Kata logs:
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.289242506+08:00" level=info msg="loaded configuration" arch=amd64 command=create file=/usr/share/defaults/kata-containers/configuration.toml format=TOML name=kata-runtime pid=65277 source=katautils
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.289829443+08:00" level=debug arch=amd64 command=create default-kernel-parameters="init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket systemd.mask=systemd-journald.service systemd.mask=systemd-journald.socket systemd.mask=systemd-journal-flush.service systemd.mask=systemd-udevd.service systemd.mask=systemd-udevd.socket systemd.mask=systemd-udev-trigger.service systemd.mask=systemd-timesyncd.service systemd.mask=systemd-update-utmp.service systemd.mask=systemd-tmpfiles-setup.service systemd.mask=systemd-tmpfiles-cleanup.service systemd.mask=systemd-tmpfiles-cleanup.timer systemd.mask=tmp.mount" name=kata-runtime pid=65277 source=katautils
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.290054784+08:00" level=info arch=amd64 arguments="\"create --bundle /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 --pid-file /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/init.pid --console-socket /tmp/pty059830655/pty.sock 52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397\"" command=create commit=8e72cf1 name=kata-runtime pid=65277 source=runtime version=1.6.0-rc2
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.290422334+08:00" level=debug msg="converting /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/config.json" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=oci
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.292154837+08:00" level=debug msg="container rootfs: /var/lib/docker/overlay2/36d0a6dcb06907bf5225c1bd3e434505587af4ef52264f14a7dc191d9e32488a/merged" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=oci
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.29235675+08:00" level=info msg="shm-size detected: 67108864" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=oci
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.415044861+08:00" level=debug msg="New filesystem store backend for /var/lib/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/var/lib/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.415162254+08:00" level=debug msg="Creating root directory" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/var/lib/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.415355576+08:00" level=debug msg="Creating raw directory" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/var/lib/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/raw pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.415457915+08:00" level=debug msg="New filesystem store backend for /run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.415517207+08:00" level=debug msg="Creating root directory" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.415562808+08:00" level=debug msg="Creating raw directory" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/raw pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.415636593+08:00" level=debug msg="Creating bridges" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qemu
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.41587701+08:00" level=debug msg="Creating UUID" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qemu
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.417561051+08:00" level=debug msg="agent: Using unix socket form VM socket endpoint" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=kata_agent
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.417624937+08:00" level=debug msg="Could not retrieve anything from storage" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=kata_agent
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.417674579+08:00" level=warning msg="load sandbox devices failed" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 error="open /run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/devices.json: no such file or directory" name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 sandboxid=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=sandbox
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.418041583+08:00" level=info msg="Endpoints found after scan" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 endpoints="[0xc0001a4500]" name=kata-runtime pid=65277 source=virtcontainers subsystem=network
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.418393238+08:00" level=info msg="Attaching endpoint" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 endpoint-type=virtual hotplug=false name=kata-runtime pid=65277 source=virtcontainers subsystem=network
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.41893448+08:00" level=debug msg="Network added" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=network
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.419108246+08:00" level=info msg="Starting VM" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=sandbox
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.419173531+08:00" level=debug arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 default-kernel-parameters="tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro rw rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug" name=kata-runtime pid=65277 source=virtcontainers subsystem=qemu
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.419307657+08:00" level=info msg="Adding extra file [0xc0002b05a0 0xc0002b0590]" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qmp
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.419374307+08:00" level=info msg="launching /usr/bin/qemu-lite-system-x86_64 with: [-name sandbox-52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 -uuid 6b0da8a8-08a3-4660-a4f1-425b7ec61a92 -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host,pmu=off -qmp unix:/run/vc/vm/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/qmp.sock,server,nowait -m 1024M,slots=10,maxmem=9001M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=true,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/usr/share/kata-containers/kata-containers-image_clearlinux_1.6.0-rc2_agent_a41f322af86.img,size=134217728 -device virtio-scsi-pci,id=scsi0,disable-modern=true,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng,rng=rng0,romfile= -device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 -chardev socket,id=charch0,path=/run/vc/vm/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/kata.sock,server,nowait -device virtio-9p-pci,disable-modern=true,fsdev=extra-9p-kataShared,mount_tag=kataShared,romfile= -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397,security_model=none -netdev tap,id=network-0,vhost=on,vhostfds=3,fds=4 -device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:11:00:03,disable-modern=true,mq=on,vectors=4,romfile= -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -kernel /usr/share/kata-containers/vmlinuz-4.19.24.31-21.container -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro rw rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug panic=1 nr_cpus=4 init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket systemd.mask=systemd-journald.service systemd.mask=systemd-journald.socket systemd.mask=systemd-journal-flush.service systemd.mask=systemd-udevd.service systemd.mask=systemd-udevd.socket systemd.mask=systemd-udev-trigger.service systemd.mask=systemd-timesyncd.service systemd.mask=systemd-update-utmp.service systemd.mask=systemd-tmpfiles-setup.service systemd.mask=systemd-tmpfiles-cleanup.service systemd.mask=systemd-tmpfiles-cleanup.timer systemd.mask=tmp.mount -pidfile /run/vc/vm/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/pid -smp 1,cores=1,threads=1,sockets=1,maxcpus=4]" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qmp
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.480399836+08:00" level=info msg="{\"QMP\": {\"version\": {\"qemu\": {\"micro\": 0, \"minor\": 11, \"major\": 2}, \"package\": \"\"}, \"capabilities\": []}}" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qmp
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.480786749+08:00" level=info msg="QMP details" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 qmp-capabilities= qmp-major-version=2 qmp-micro-version=0 qmp-minor-version=11 source=virtcontainers subsystem=qemu
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.480981952+08:00" level=info msg="{\"execute\":\"qmp_capabilities\"}" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qmp
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.481356406+08:00" level=info msg="{\"return\": {}}" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qmp
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.48156671+08:00" level=info msg="VM started" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=sandbox
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.481719022+08:00" level=debug msg="Starting regular Kata proxy rather than built-in" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=kata_agent
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.482120327+08:00" level=info msg="proxy started" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 proxy-pid=65315 proxy-url="unix:///run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/proxy.sock" sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=kata_agent
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.48227685+08:00" level=info msg="New client" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=kata_agent url="unix:///run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/proxy.sock"
Apr 17 17:12:11 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:11.493523966+08:00" level=info msg=announce agent-logs-socket=/run/vc/vm/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/console.sock channel-mux-socket=/run/vc/vm/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/kata.sock debug=true log-level=debug name=kata-proxy pid=65315 proxy-listen-socket="unix:///run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/proxy.sock" sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=proxy version=1.6.0-rc2-d4aa0b2
Apr 17 17:12:11 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:11.494038234+08:00" level=debug msg="sending request" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=grpc.CheckRequest pid=65277 req= source=virtcontainers subsystem=kata_agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.024554192+08:00" level=info msg="[    0.301165] brd: module loaded\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.026032378+08:00" level=info msg="[    0.302663] loop: module loaded\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.027931343+08:00" level=info msg="[    0.304577]  pmem0: p1\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.028306838+08:00" level=info msg="[    0.304874] pmem0: detected capacity change from 0 to 132120576\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.030172215+08:00" level=info msg="[    0.306791] scsi host0: Virtio SCSI HBA\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.031440458+08:00" level=info msg="[    0.308083] random: fast init done\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.031935087+08:00" level=info msg="[    0.308573] random: crng init done\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.070687549+08:00" level=info msg="[    0.347303] tun: Universal TUN/TAP device driver, 1.6\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.07266314+08:00" level=info msg="[    0.349178] ixgbe: Intel(R) 10 Gigabit PCI Express Network Driver - version 5.1.0-k\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.072973666+08:00" level=info msg="[    0.349552] ixgbe: Copyright (c) 1999-2016 Intel Corporation.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.073384539+08:00" level=info msg="[    0.349910] ixgbevf: Intel(R) 10 Gigabit PCI Express Virtual Function Network Driver - version 4.1.0-k\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.073704819+08:00" level=info msg="[    0.350284] ixgbevf: Copyright (c) 2009 - 2015 Intel Corporation.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.074052066+08:00" level=info msg="[    0.350612] i40e: Intel(R) Ethernet Connection XL710 Network Driver - version 2.3.2-k\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.074349292+08:00" level=info msg="[    0.350916] i40e: Copyright (c) 2013 - 2014 Intel Corporation.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.074756881+08:00" level=info msg="[    0.351266] i40evf: Intel(R) 40-10 Gigabit Virtual Function Network Driver - version 3.2.2-k\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.074994502+08:00" level=info msg="[    0.351620] Copyright (c) 2013 - 2015 Intel Corporation.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.075317356+08:00" level=info msg="[    0.351910] VFIO - User Level meta-driver version: 0.3\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.075657751+08:00" level=info msg="[    0.352277] IR NEC protocol handler initialized\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.075957388+08:00" level=info msg="[    0.352575] IR RC5(x/sz) protocol handler initialized\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.076188584+08:00" level=info msg="[    0.352818] IR RC6 protocol handler initialized\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.076454316+08:00" level=info msg="[    0.353075] IR JVC protocol handler initialized\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.076702684+08:00" level=info msg="[    0.353325] IR Sony protocol handler initialized\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.076946267+08:00" level=info msg="[    0.353568] IR SANYO protocol handler initialized\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.077191647+08:00" level=info msg="[    0.353813] IR Sharp protocol handler initialized\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.077492418+08:00" level=info msg="[    0.354071] IR MCE Keyboard/mouse protocol handler initialized\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.077731712+08:00" level=info msg="[    0.354356] IR XMP protocol handler initialized\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.078110683+08:00" level=info msg="[    0.354651] device-mapper: ioctl: 4.39.0-ioctl (2018-04-03) initialised: dm-devel@redhat.com\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.078548647+08:00" level=info msg="[    0.355170] xt_time: kernel timezone is -0000\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.07885146+08:00" level=info msg="[    0.355429] IPVS: Registered protocols (TCP, UDP, SCTP, AH, ESP)\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.079180305+08:00" level=info msg="[    0.355724] IPVS: Connection hash table configured (size=4096, memory=64Kbytes)\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.079465801+08:00" level=info msg="[    0.356104] IPVS: ipvs loaded.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.079745303+08:00" level=info msg="[    0.356367] IPVS: [rr] scheduler registered.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.079986267+08:00" level=info msg="[    0.356605] IPVS: [wrr] scheduler registered.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.080239017+08:00" level=info msg="[    0.356855] IPVS: [lc] scheduler registered.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.080500331+08:00" level=info msg="[    0.357121] IPVS: [wlc] scheduler registered.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.080762673+08:00" level=info msg="[    0.357385] IPVS: [fo] scheduler registered.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.081009576+08:00" level=info msg="[    0.357632] IPVS: [ovf] scheduler registered.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.081255657+08:00" level=info msg="[    0.357878] IPVS: [lblc] scheduler registered.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.08151816+08:00" level=info msg="[    0.358141] IPVS: [lblcr] scheduler registered.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.081772899+08:00" level=info msg="[    0.358395] IPVS: [dh] scheduler registered.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.082025433+08:00" level=info msg="[    0.358641] IPVS: [sh] scheduler registered.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.08229297+08:00" level=info msg="[    0.358897] IPVS: [sed] scheduler registered.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.082582755+08:00" level=info msg="[    0.359194] IPVS: [nq] scheduler registered.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.082843342+08:00" level=info msg="[    0.359465] IPVS: ftp: loaded support on port[0] = 21\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.083061091+08:00" level=info msg="[    0.359706] IPVS: [sip] pe registered.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.083427182+08:00" level=info msg="[    0.359992] ipt_CLUSTERIP: ClusterIP Version 0.8 loaded successfully\n" name=kat -proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.083717967+08:00" level=info msg="[    0.360338] Initializing XFRM netlink socket\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.084050102+08:00" level=info msg="[    0.360668] NET: Registered protocol family 10\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.084464295+08:00" level=info msg="[    0.361098] Segment Routing with IPv6\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.084742207+08:00" level=info msg="[    0.361360] NET: Registered protocol family 17\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.085006459+08:00" level=info msg="[    0.361627] 9pnet: Installing 9P2000 support\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.086433492+08:00" level=info msg="[    0.362994] sched_clock: Marking stable (360919188, 1109366)->(369080115, -7051561)\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.086748821+08:00" level=info msg="[    0.363382] registered taskstats version 1\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.087346459+08:00" level=info msg="[    0.363877] EXT4-fs (pmem0p1): DAX enabled. Warning: EXPERIMENTAL, use at your own risk\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.088383615+08:00" level=info msg="[    0.364888] EXT4-fs (pmem0p1): mounted filesystem with ordered data mode. Opts: dax,data=ordered,errors=remount-ro\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.088716729+08:00" level=info msg="[    0.365296] VFS: Mounted root (ext4 filesystem) on device 259:1.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.088985363+08:00" level=info msg="[    0.365623] devtmpfs: mounted\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.08971698+08:00" level=info msg="[    0.366335] Freeing unused kernel image memory: 840K\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.091452155+08:00" level=info msg="[    0.368030] Write protecting the kernel read-only data: 16384k\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.092343109+08:00" level=info msg="[    0.368938] Freeing unused kernel image memory: 2016K\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.092956092+08:00" level=info msg="[    0.369577] Freeing unused kernel image memory: 1204K\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.093241162+08:00" level=info msg="[    0.369855] Run /usr/lib/systemd/systemd as init process\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.108704418+08:00" level=info msg="[    0.384867] systemd[1]: systemd 241 running in system mode. (+PAM -AUDIT -SELINUX +IMA -APPARMOR -SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=legacy)\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.109066402+08:00" level=info msg="[    0.385655] systemd[1]: No virtualization found in DMI\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.109397073+08:00" level=info msg="[    0.385969] systemd[1]: Virtualization found, CPUID=KVMKVMKVM\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.109675349+08:00" level=info msg="[    0.386297] systemd[1]: Found VM virtualization kvm\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.109938493+08:00" level=info msg="[    0.386558] systemd[1]: Detected virtualization kvm.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.110227448+08:00" level=info msg="[    0.386850] systemd[1]: Detected architecture x86-64.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.110509135+08:00" level=info msg="[    0.387128] systemd[1]: Running with unpopulated /etc.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.111024097+08:00" level=info msg="[    0.387494] systemd[1]: Mounting cgroup to /sys/fs/cgroup/cpu,cpuacct of type cgroup with options cpu,cpuacct.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.111575869+08:00" level=info msg="[    0.388111] systemd[1]: Mounting cgroup to /sys/fs/cgroup/freezer of type cgroup with options freezer.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.112038563+08:00" level=info msg="[    0.388562] systemd[1]: Mounting cgroup to /sys/fs/cgroup/cpuset of type cgroup with options cpuset.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.113280201+08:00" level=info msg="\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.113542853+08:00" level=info msg="Welcome to \x1b[1;35mClear Linux OS\x1b[0m!\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.113722264+08:00" level=info msg="\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.132353774+08:00" level=info msg="[    0.408777] systemd-gpt-auto-generator[74]: Failed to chase block device '/', ignoring: No such file or directory\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.134236896+08:00" level=info msg="[    0.410831] systemd-fstab-generator[72]: Parsing /etc/fstab\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.135453388+08:00" level=info msg="[    0.411960] systemd-getty-generator[73]: Automatically adding serial getty for /dev/hvc0.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.137428616+08:00" level=info msg="[    0.413918] systemd-getty-generator[73]: Automatically adding serial getty for /dev/hvc0.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.138828419+08:00" level=info msg="[    0.415337] systemd-gpt-auto-generator[74]: pmem0p1: Root device /dev/pmem0.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.139964195+08:00" level=info msg="[    0.416444] systemd-bless-boot-generator[69]: Skipping generator, not an EFI boot.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.144511836+08:00" level=info msg="[    0.420996] systemd-gpt-auto-generator[74]: Waiting for device (parent + 1 partitions) to appear...\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.157787779+08:00" level=info msg="[\x1b[0;1;31mFAILED\x1b[0m] Failed to listen on \x1b[0;1;39mudev Kernel Socket\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.158090222+08:00" level=info msg="See 'systemctl status systemd-udevd-kernel.socket' for details.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.158629935+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Listening on \x1b[0;1;39minitctl Compatibility Named Pipe\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.159977118+08:00" level=info msg="         Starting \x1b[0;1;39mApply Kernel Variables\x1b[0m...\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.160760885+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Set up automount \x1b[0;1;39mArbitrary…s File System Automount Point\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.164045804+08:00" level=info msg="[    0.440486] systemd[76]: systemd-sysctl.service: Failed to connect stdout to the journal socket, ignoring: No such file or directory\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.164627173+08:00" level=info msg="[    0.441143] systemd[76]: systemd-sysctl.service: Executing: /usr/lib/systemd/systemd-sysctl\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.167703865+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Listening on \x1b[0;1;39mProcess Core Dump Socket\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.168194958+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Reached target \x1b[0;1;39mSwap\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.169111846+08:00" level=info msg="[    0.445683] systemd-sysctl[76]: Parsing /usr/lib/sysctl.d/50-coredump.conf\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.169533082+08:00" level=info msg="[\x1b[0;1;31mFAILED\x1b[0m] Failed to listen on \x1b[0;1;39mudev Control Socket\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.169898237+08:00" level=info msg="[    0.446487] systemd-sysctl[76]: Parsing /usr/lib/sysctl.d/50-default.conf\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.170349526+08:00" level=info msg="[    0.446850] systemd-sysctl[76]: Setting 'kernel/core_pattern' to '|/usr/lib/systemd/coredump-wrapper %E %P %u %g %s %t %c %h %e'.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.170652423+08:00" level=info msg="See 'systemctl status systemd-udevd-control.socket' for details.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.17106453+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Reached target \x1b[0;1;39mLocal File Systems (Pre)\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.171515587+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Reached target \x1b[0;1;39mLocal File Systems\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.171862362+08:00" level=info msg="[    0.448423] systemd-sysctl[76]: Setting 'kernel/sysrq' to '16'.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.17223419+08:00" level=info msg="[    0.448758] systemd-sysctl[76]: Couldn't write '16' to 'kernel/sysrq', ignoring: No such file or directory\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.172663321+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Reached target \x1b[0;1;39mSlices\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.173472267+08:00" level=info msg="[    0.450046] systemd-sysctl[76]: Setting 'kernel/core_uses_pid' to '1'.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.173840293+08:00" level=info msg="         Starting \x1b[0;1;39mLoad/Save Random Seed\x1b[0m...\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.174184188+08:00" level=info msg="[    0.450741] systemd-sysctl[76]: Setting 'net/ipv4/conf/all/rp_filter' to '2'.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.17468+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Started \x1b[0;1;39mDispatch Password …ts to Console Directory Watch\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.175039984+08:00" level=info msg="[    0.451592] systemd-sysctl[76]: Setting 'net/ipv4/conf/all/accept_source_route' to '0'.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.175398648+08:00" level=info msg="[    0.451934] systemd-sysctl[76]: Setting 'net/ipv4/conf/all/promote_secondaries' to '1'.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.175822736+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Reached target \x1b[0;1;39mPaths\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.176136892+08:00" level=info msg="[    0.452726] systemd-sysctl[76]: Setting 'net/core/default_qdisc' to 'fq'.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.176617858+08:00" level=info msg="[\x1b[0;1;31mFAILED\x1b[0m] Failed to listen on \x1b[0;1;39mJournal Socket (/dev/log)\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.177065805+08:00" level=info msg="[    0.453653] systemd-sysctl: 4 output lines suppressed due to ratelimiting\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.177905567+08:00" level=info msg="[    0.454373] systemd[77]: systemd-random-seed.service: Failed to connect stdout to the journal socket, ignoring: No such file or directory\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.178375478+08:00" level=info msg="[    0.454893] systemd[77]: systemd-random-seed.service: Executing: /usr/lib/systemd/systemd-random-seed load\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.181263868+08:00" level=info msg="[    0.457767] systemd-random-seed[77]: Seed file /var/lib/systemd/random-seed not yet initialized, proceeding.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.181584461+08:00" level=info msg="See 'systemctl status systemd-journald-dev-log.socket' for details.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.182012601+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Reached target \x1b[0;1;39mSockets\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.182427122+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Reached target \x1b[0;1;39mLocal Encrypted Volumes\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.183783257+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Started \x1b[0;1;39mApply Kernel Variables\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.185538542+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Started \x1b[0;1;39mLoad/Save Random Seed\x1b[0m.\n" name kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.186540408+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Reached target \x1b[0;1;39mSystem Initialization\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.189506236+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Started \x1b[0;1;39mDaily Cleanup of Temporary Directories\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.190589538+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Reached target \x1b[0;1;39mTimers\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.192844645+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Reached target \x1b[0;1;39mBasic System\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.194413441+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Started \x1b[0;1;39mKata Containers Agent\x1b[0m.\n" name kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.194865948+08:00" level=info msg="[\x1b[0;32m  OK  \x1b[0m] Reached target \x1b[0;1;39mKata Containers Agent Target\x1b[0m.\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.195937057+08:00" level=info msg="[    0.472510] systemd[83]: kata-agent.service: Executing: /usr/bin/kata-agent\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.239889984+08:00" level=info msg="time=\"2019-04-17T09:12:12.231084741Z\" level=info msg=announce device-handlers=\"mmioblk,blk,scsi,nvdimm\" name=kata-agent pid=83 source=agent storage-handlers=\"scsi,ephemeral,9p,virtio-fs,blk,mmioblk\" system-memory=\"1010708 kB\" version=1.6.0-rc2-a41f322af869fddbed252f51dbcde04076594db5\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.241046904+08:00" level=info msg="time=\"2019-04-17T09:12:12.232748608Z\" level=info msg=\"Started listening for uevents\" name=kata-agent pid=83 source=agent subsystem=udevlistener\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.248557008+08:00" level=info msg="time=\"2019-04-17T09:12:12.24016066Z\" level=info msg=\"agent grpc server starts\" name=kata-agent pid=83 source=agent\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.249282951+08:00" level=info msg="time=\"2019-04-17T09:12:12.240974756Z\" level=info msg=\"Waiting for stopServer signal...\" name=kata-agent pid=83 source=agent subsystem=stopserverwatcher\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.252033794+08:00" level=info msg="New client" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=kata_agent url="unix:///run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/proxy.sock"
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.252685486+08:00" level=debug msg="sending request" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=grpc.UpdateInterfaceRequest pid=65277 req="interface:<device:\"eth0\" name:\"eth0\" IPAddresses:<address:\"172.17.0.3\" mask:\"16\" > mtu:1500 hwAddr:\"02:42:ac:11:00:03\" > " source=virtcontainers subsystem=kata_agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.255084692+08:00" level=info msg="time=\"2019-04-17T09:12:12.246789252Z\" level=info msg=\"Getting interface from MAC address\" interface-name=eth0 mac-address=\"02:42:ac:11:00:03\" name=kata-agent pci-address= pid=83 source=agent\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.256176496+08:00" level=info msg="time=\"2019-04-17T09:12:12.247849497Z\" level=info msg=\"Link found\" interface-name=eth0 link=\"&{LinkAttrs:{Index:2 MTU:1500 TxQLen:1000 Name:eth0 HardwareAddr:02:42:ac:11:00:03 Flags:broadcast|multicast RawFlags:4098 ParentIndex:0 MasterIndex:0 Namespace:<nil> Alias: Statistics:0xc0001de624 Promisc:0 Xdp:0xc0000372e0 EncapType:ether Protinfo:<nil> OperState:down NetNsID:0 NumTxQueues:0 NumRxQueues:0 Vfs:[]}}\" mac-address=\"02:42:ac:11:00:03\" name=kata-agent pci-address= pid=83 source=agent\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.257210452+08:00" level=info msg="[    0.533794] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.257711329+08:00" level=info msg="New client" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=kata_agent url="unix:///run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/proxy.sock"
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.258145081+08:00" level=debug msg="sending request" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=grpc.UpdateRoutesRequest pid=65277 req="routes:<Routes:<gateway:\"172.17.0.1\" device:\"eth0\" > Routes:<dest:\"172.17.0.0/16\" device:\"eth0\" source:\"172.17.0.3\" scope:253 > > " source=virtcontainers subsystem=kata_agent
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.26209774+08:00" level=info msg="New client" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=kata_agent url="unix:///run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/proxy.sock"
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.262717368+08:00" level=debug msg="sending request" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=grpc.CreateSandboxRequest pid=65277 req="hostname:\"52e7aef4e199\" storages:<driver:\"9p\" source:\"kataShared\" fstype:\"9p\" options:\"trans=virtio,version=9p2000.L,cache=mmap\" options:\"nodev\" options:\"msize=8192\" mount_point:\"/run/kata-containers/shared/containers/\" > storages:<driver:\"ephemeral\" source:\"shm\" fstype:\"tmpfs\" options:\"noexec\" options:\"nosuid\" options:\"nodev\" options:\"mode=1777\" options:\"size=67108864\" mount_point:\"/run/kata-containers/sandbox/shm\" > sandbox_id:\"52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397\" " source=virtcontainers subsystem=kata_agent
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.269574501+08:00" level=info msg="time=\"2019-04-17T09:12:12.261291987Z\" level=info msg=\"Received add uevent\" name kata-agent pid=83 source=agent subsystem=udevlistener uevent-action=add uevent-devname= uevent-devpath=/devices/virtual/bdi/9p-1 uevent-seqnum=818 uevent-subsystem=bdi\n" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=agent
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.27004993+08:00" level=info msg="Agent started in the sandbox" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=sandbox
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.270233152+08:00" level=info msg="New client" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=kata_agent url="unix:///run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/proxy.sock"
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.270603582+08:00" level=debug msg="sending request" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=grpc.GuestDetailsRequest pid=65277 req="mem_block_size:true " source=virtcontainers subsystem=kata_agent
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.273985973+08:00" level=debug msg="Request to hypervisor to update vCPUs" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 cpus-sandbox=1 name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=sandbox
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.274154559+08:00" level=debug msg="Sandbox CPUs: 1" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=sandbox
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.274285659+08:00" level=debug msg="Request to hypervisor to update memory" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 memory-sandbox-size-byte=1073741824 name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=sandbox
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.274553995+08:00" level=info msg="{\"QMP\": {\"version\": {\"qemu\": {\"micro\": 0, \"minor\": 11, \"major\": 2}, \"package\": \"\"}, \"capabilities\": []}}" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qmp
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.274712463+08:00" level=info msg="{\"execute\":\"qmp_capabilities\"}" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qmp
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.275268454+08:00" level=info msg="{\"return\": {}}" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qmp
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.275384874+08:00" level=debug msg="Sandbox memory size: 1024 Byte" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=sandbox
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.27549979+08:00" level=info msg="New client" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=kata_agent url="unix:///run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/proxy.sock"
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.275859461+08:00" level=debug msg="sending request" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=grpc.OnlineCPUMemRequest pid=65277 req= source=virtcontainers subsystem=kata_agent
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.277264221+08:00" level=debug msg="New filesystem store backend for /var/lib/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/var/lib/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.277439098+08:00" level=debug msg="Creating root directory" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/var/lib/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.277624913+08:00" level=debug msg="Creating raw directory" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/var/lib/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/raw pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.277820668+08:00" level=debug msg="New filesystem store backend for /run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.277950705+08:00" level=debug msg="Creating root directory" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.278073847+08:00" level=debug msg="Creating raw directory" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/raw pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.278340135+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/agpgart name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.278536156+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ashmem name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.278704166+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/autofs name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.278862104+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/binder0 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.279029297+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/binder1 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.279186995+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/binder2 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.279365679+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device="/dev/bsg/1:0:0:0" name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.279536783+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device="/dev/bsg/2:0:0:0" name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.279658628+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/btrfs-control name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.279814576+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/cpu_dma_latency name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.27993676+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/cuse name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.280104266+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/dri/card0 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.280267531+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/dri/renderD128 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.280427575+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ecryptfs name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.280603217+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/fb0 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.280810907+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/full name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.280969221+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/fuse name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.281136604+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/hpet name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.281301206+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/hwrng name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.281470161+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/input/event0 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.281645975+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/input/event1 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.281806482+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/input/event2 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.281968862+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/input/event3 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.28212488+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/input/mice name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.28229547+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/input/mouse0 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.282449467+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/input/mouse1 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.282624203+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/kmsg name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.282793172+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/kvm name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.28296023+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/lightnvm/control name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.283183891+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/loop-control name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.283638481+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/mapper/control name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.283803609+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/mcelog name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.283970121+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/mem name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.284135443+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/memory_bandwidth name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.284306167+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/net/tun name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.284460399+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/network_latency name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.28463866+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/network_throughput name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.284804872+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/null name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.284969249+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/port name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.285132249+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ppp name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.285297915+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/psaux name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.285463586+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ptmx name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.285634149+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/random name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.285798219+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/rfkill name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.285976673+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/rtc0 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.286231827+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/sg0 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.286400758+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/sg1 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.286573585+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/snapshot name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.286750165+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/snd/seq name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.286912977+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/snd/timer name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.287115708+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tap28254 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.287280118+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.287459014+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty0 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.287616356+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty1 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.287770595+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty10 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.287926208+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty11 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.288081733+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty12 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.288239505+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty13 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.289460437+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty14 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.289917373+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty15 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.290087843+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty16 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.290259945+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty17 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.290422783+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty18 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.29058545+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty19 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.290742971+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty2 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.290918655+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty20 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.291071378+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty21 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.291235015+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty22 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.29139305+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty23 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.291558356+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty24 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.29170494+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty25 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.291868722+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty26 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.292023278+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty27 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.292184374+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty28 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.292340906+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty29 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.292491871+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty3 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.292665584+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty30 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.292829912+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty31 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.292993844+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty32 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.293149313+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty33 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.293300569+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty34 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.293461066+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty35 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.293617286+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty36 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.293785846+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty37 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.293945031+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty38 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.294101905+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty39 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.294249146+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty4 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.294403752+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty40 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.294564684+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty41 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.294716236+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty42 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.29486213+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty43 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.295024771+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty44 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.295188951+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty45 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.295363465+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty46 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.295520082+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty47 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.295682747+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty48 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.295842146+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty49 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.296011946+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty5 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.296173288+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty50 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.29633563+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty51 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.296492411+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty52 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.296698113+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty53 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.296860694+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty54 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.297019151+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty55 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.297172591+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty56 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.297330547+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty57 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.297492053+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty58 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.297650703+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty59 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.297810491+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty6 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.297965979+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty60 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.298120375+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty61 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.298282838+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty62 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.298430176+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty63 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.298581635+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty7 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.298730263+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty8 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.298888583+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/tty9 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.299052891+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS0 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.299216795+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS1 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.29938357+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS10 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.29954769+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS11 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.299702788+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS12 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.299868367+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS13 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.300022771+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS14 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.300176144+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS15 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.30033006+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS16 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.300489922+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS17 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.300667339+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS18 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.30083271+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS19 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.300993239+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS2 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.301161977+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS20 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.301331706+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS21 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.301493633+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS22 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.301663478+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS23 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.301820664+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS24 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.301979876+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS25 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.302141047+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS26 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.302302834+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS27 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.302459162+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS28 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.302615866+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS29 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.302779493+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS3 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.30294431+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS30 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.303101295+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS31 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.303263265+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS4 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.303423993+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS5 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.303581618+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS6 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.30375634+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS7 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.303913308+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS8 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.304076216+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyS9 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.3042411+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/ttyprintk name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.304369434+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/uhid name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.304523067+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/uinput name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.304739743+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/urandom name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.304874378+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/userio name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.305259183+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/vcsa name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.305429599+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/vcsa1 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.305588134+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/vcsa2 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.305753808+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/vcsa3 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.30591997+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/vcsa4 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.306090437+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/vcsa5 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.306243323+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/vcsa6 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.306365399+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/vfio/vfio name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.30651986+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/vga_arbiter name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.30665755+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/vhci name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.306821031+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/vhost-net name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.306953048+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/vhost-vsock name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.307116389+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/vmci name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.307283138+08:00" level=info msg="Device has not been passed to the container" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/zero name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.307409193+08:00" level=info msg="Not attach device because it is a CDROM" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/fb0 name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=container
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.307526027+08:00" level=info msg="Not attach device because it is a CDROM" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/sr0 name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=container
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.307674301+08:00" level=info msg="device details" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device-major=0 device-minor=56 mount-point=/var/lib/docker/overlay2/36d0a6dcb06907bf5225c1bd3e434505587af4ef52264f14a7dc191d9e32488a/merged name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=container
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.307855788+08:00" level=info msg="Attaching virtio-scsi device" VirtPath= arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 device=/dev/fd0 name=kata-runtime pid=65277 source=virtcontainers subsystem=device
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.308118775+08:00" level=info msg="{\"arguments\":{\"driver\":\"raw\",\"file\":{\"driver\":\"file\",\"filename\":\"/dev/fd0\"},\"node-name\":\"drive-f549618d008d50c1\"},\"execute\":\"blockdev-add\"}" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name kata-runtime pid=65277 source=virtcontainers subsystem=qmp
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.35697739+08:00" level=info msg="{\"error\": {\"class\": \"GenericError\", \"desc\": \"Could not open '/dev/fd0': No such device or address\"}}" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qmp
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.357472605+08:00" level=info msg="Stopping sandbox in the VM" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=sandbox
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.357554315+08:00" level=info msg="New client" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=kata_agent url="unix:///run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/proxy.sock"
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.358074752+08:00" level=debug msg="sending request" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=grpc.DestroySandboxRequest pid=65277 req= source=virtcontainers subsystem=kata_agent
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.364548459+08:00" level=info msg="Stopping VM" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=sandbox
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.36460938+08:00" level=info msg="Stopping Sandbox" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qemu
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.364877651+08:00" level=info msg="{\"execute\":\"quit\"}" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qmp
Apr 17 17:12:12 ub2-k8s001 kata-proxy[65315]: time="2019-04-17T17:12:12.364727474+08:00" level=fatal msg="channel error" error="accept unix /run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397/proxy.sock: use of closed network connection" name=kata-proxy pid=65315 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=proxy
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.365323727+08:00" level=info msg="{\"return\": {}}" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qmp
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.365379084+08:00" level=info msg="{\"timestamp\": {\"seconds\": 1555492332, \"microseconds\": 365313}, \"event\": \"SHUTDOWN\", \"data\": {\"guest\": false}}" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qmp
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.365499062+08:00" level=info msg="cleanup vm path" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 dir=/run/vc/vm/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 link=/run/vc/vm/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=qemu
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.365671489+08:00" level=info msg="Detaching endpoint" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 endpoint-type=virtual hotunplug=false name=kata-runtime pid=65277 source=virtcontainers subsystem=network
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.384955186+08:00" level=debug msg="Network removed" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=network
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.385012001+08:00" level=info msg="Network namespace \"/var/run/netns/cni-edd616c2-dc90-3f7a-160e-f85d5797398f\" deleted" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=virtcontainers subsystem=network
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.408656487+08:00" level=debug msg="Deleting sandbox cgroup" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=sandbox
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.408727165+08:00" level=debug msg="Deleting no constraints cgroup" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/kata pid=65277 sandbox=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 source=virtcontainers subsystem=sandbox
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.411533383+08:00" level=info msg="cleanup agent" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/run/kata-containers/shared/sandboxes/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 pid=65277 source=virtcontainers subsystem=kata_agent
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.411611055+08:00" level=debug msg="Deleting files" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/var/lib/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.411930668+08:00" level=debug msg="Deleting files" arch=amd64 backend=filesystem command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime path=/run/vc/sbs/52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 pid=65277 source=virtcontainers/store subsystem=store
Apr 17 17:12:12 ub2-k8s001 kata-runtime[65277]: time="2019-04-17T17:12:12.412128546+08:00" level=error msg="QMP command failed: Could not open '/dev/fd0': No such device or address" arch=amd64 command=create container=52e7aef4e1998c4444d379a9e26310144c99a74bdd1afa33fa9fc32e7c82d397 name=kata-runtime pid=65277 source=runtime

### PR DESCRIPTION
**Pull request by amshinde**
In privileged mode, all host devices are supposed to be passed
to the container in config.json. Skip floppy drives.

Fixes #1551

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

File: virtcontainers/container.go [hunk 1]
```diff
@@ -51,6 +51,10 @@ var cdromMajors = map[int64]string{
 	32: "CM206_CDROM_MAJOR",
 }
 
+// https://github.com/torvalds/linux/blob/master/include/uapi/linux/major.h
+// #FLOPPY_MAJOR		2
```
Comment (jodh-intel) [inline virtcontainers/container.go]: For reference, according to that file two devices share this major number:

```c
#define FLOPPY_MAJOR		2
#define PTY_MASTER_MAJOR	2
```

Comment (grahamwhaley) [reply virtcontainers/container.go]: I suspect one is a block device (fd) and the other a char (pty), just for ref.

File: virtcontainers/container.go [hunk 2]
```diff
@@ -603,6 +607,14 @@ func filterDevices(sandbox *Sandbox, c *Container, devices []ContainerDevice) (r
 			}).Info("Not attach device because it is a CDROM")
 			continue
 		}
+
+		if major == floppyMajor {
```
Comment (grahamwhaley) [inline virtcontainers/container.go]: as I think @jodh-intel implied - either now or if we add any more, we could fold the floppy and cd bits into a map/table and just have the one test loop maybe.

File: virtcontainers/container.go (hunk 1 above)
Comment (amshinde) [reply virtcontainers/container.go]: yes, one is a block device while the other is a char one.

File: virtcontainers/container.go [hunk 3]
```diff
@@ -51,6 +51,10 @@ var cdromMajors = map[int64]string{
 	32: "CM206_CDROM_MAJOR",
 }
 
+// https://github.com/torvalds/linux/blob/master/include/uapi/linux/major.h
+// #FLOPPY_MAJOR		2
+var floppyMajor = int64(2)
```
[the remark this answers is not in the document]
Comment (amshinde) [reply virtcontainers/container.go]: @jodh-intel Made this a const.
I did not add it to the map in this case, just so that we can clearly distinguish them and pass this in the log mesage.

**Comment by grahamwhaley** [comment]
ooh, ooh - q35 ci we know is not working, so, this is effectively green! Merging!!

**Comment by jodh-intel** [comment]
You beat me to the soylent! ;)
