### PR TITLE
rootless: fix rootless for case net=none

### LINKED ISSUE #2319: Fix running rootless with net=none
When kata is invoked as rootless with net=none, it fails with the following error:
```
$ podman --log-level debug run --runtime=/usr/local/bin/kata-runtime --net=none -ti busybox
ERRO[0000] mkdir /var/run/netns: permission denied: OCI runtime permission denied error
```

### PR DESCRIPTION
**Pull request by amshinde**
When kata-runtime was invoked as rootless by podman with
net=none, an empty net namespace path is provided.
kata-runtime was then trying to create a new network namespace
and bind-mounting it under /var/run/netns, resulting in a permission error.

Instead, with this commit, the runtime checks if it is
running rootless and instead creates network namespace bind mount
under rootless directory instead.

Fixes #2319

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@egernst @jodh-intel Once I submit another PR to reduce some of the setup required, I am planning to add a  test to verify rootless with podman, just a single test to verify that a container is started to begin with.

**Comment by amshinde** [comment]
Will backport to stable once this is merged.

**Comment by amshinde** [comment]
ping @kata-containers/runtime

**Comment by jcvenegas** [comment]
I see that `kata-containers/SoB-check Expected — Waiting for status to be reported` may be not reported @chavafg @GabyCT  where could I re-trigger ?

**Comment by grahamwhaley** [comment]
@jcvenegas - the 'trick' is to find an SoB (or WIP) that worked, and that will have a link to the guidance page, such as: https://github.com/kata-containers/community/wiki/The-SoB-check

For the SoB, you need an:

/zuul-recheck

(for WIP, you have to wiggle the labels....)

**Comment by grahamwhaley** [comment]
Having said that, the checks have been fairly steady at updating for some time now - I suspect maybe there is some Zuul outage or planned maintenance (I've not seen anything though - /cc @ttx just in case he knows...)

**Comment by ttx** [comment]
There were a couple of Zuul restarts on Monday/Tuesday which may be the root cause for the glitch here.

File: pkg/rootless/rootless.go [hunk 1]
```diff
@@ -3,19 +3,39 @@
 // SPDX-License-Identifier: Apache-2.0
 //
 
+// Copyright 2015-2017 CNI authors
```
Comment (tedyu) [inline pkg/rootless/rootless.go]: 2017 -> 2019

File: pkg/rootless/rootless.go [hunk 2]
```diff
@@ -121,3 +141,112 @@ func IsRootless() bool {
...
+
+	// Create the directory for mounting network namespaces
+	// This needs to be a shared mountpoint in case it is mounted in to
+	// other namespaces (containers)
+	err = os.MkdirAll(nsRunDir, 0755)
+	if err != nil {
+		return nil, err
+	}
+
+	nsName := fmt.Sprintf("cni-%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:])
```
Comment (jodh-intel) [inline pkg/rootless/rootless.go]: ooi, why the `cni-` prefix?

File: pkg/rootless/rootless.go [hunk 3]
```diff
@@ -3,19 +3,39 @@
 // SPDX-License-Identifier: Apache-2.0
 //
 
+// Copyright 2015-2017 CNI authors
+//
+// Licensed under the Apache License, Version 2.0 (the "License");
```
Comment (devimc) [inline pkg/rootless/rootless.go]: change this to SPDX
