### PR TITLE
mounts: fix isSystemMount check for mountSharedDirMounts

### LINKED ISSUE #1591: Certain Dockerfile volumes preventing pod start
We've found certain volume paths defined in the Dockerfile prevent the Pod from starting with Kata. One such example is `/sys/fs/cgroup`.

The following Dockerfile can be used to replicate:
```Dockerfile
FROM ubuntu

VOLUME /sys/fs/cgroup
```

We receive the following errors:
```
Error: failed to create containerd task: Could not run process: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/containerd/io.containerd.grpc.v1.cri/containers/sleep/volumes/a45869c2ff90df3649c035b429e23e8b935804e90cd5cfd997778ff0d64d693c\\\" to rootfs \\\"/run/kata-containers/shared/containers/sleep\\\" at \\\"/sys/fs/cgroup\\\" caused \\\"stat /var/lib/containerd/io.containerd.grpc.v1.cri/containers/sleep/volumes/a45869c2ff90df3649c035b429e23e8b935804e90cd5cfd997778ff0d64d693c: no such file or directory\\\"\"": unknown
```

Unfortunately we do not have control over the contents of the Dockerfiles/images and need an elegant solution for handling this in Kata.

The following paths have been found to prevent the pods from starting:
 - `/sys/fs/cgroup`

(I will add more as I find them)

I think this issue is similar to https://github.com/kata-containers/runtime/issues/1561 as both are related to the volumes defined in Docker images/OCI image specs.

### PR DESCRIPTION
**Pull request by awprice**
This change updates the isSystemMount check for mountSharedDirMounts
when setting up shared directory mounts for the container and uses
the source of the mount instead of the destination for the check.

We want to exclude system mounts from the host side as they
shouldn't be mounted into the container.

We do however want to allow system mounts within the
container as denying them can prevent some containers from
running properly.

Fixes #1591

Signed-off-by: Alex Price <aprice@atlassian.com>

### CODE REVIEW

File: virtcontainers/container.go [hunk 1]
```diff
@@ -515,10 +515,11 @@ func (c *Container) mountSharedDirMounts(hostSharedDir, guestSharedDir string) (
...
 	var ignoredMounts []Mount
 	for idx, m := range c.mounts {
-		if isSystemMount(m.Destination) {
-			if !(IsDockerVolume(m.Source) || Isk8sHostEmptyDir(m.Source)) {
-				continue
-			}
+		// Skip mounting certain system paths from the source on the host side
+		// into the container as it does not make sense to do so.
+		// Example sources could be /sys/fs/cgroup etc.
+		if isSystemMount(m.Source) {
```
Comment (amshinde) [inline virtcontainers/container.go]: @awprice Your comment makes sense, we do not mount certain system paths from the host side into the guest, however it makes sense to do so for system paths that are docker volumes and k8s empty dirs.

Comment (awprice) [reply virtcontainers/container.go]: We are using containerd, maybe we need to update the logic to handle docker volumes, k8s empty dirs and containerd volumes?

I don't think containerd volumes have been factored in here and that's probably why we are running into this issue, as we don't use docker.

**Comment by jodh-intel** [comment]
Only the single centos CI failure which is known (https://github.com/kata-containers/runtime/issues/1604), so merging...
