### PR TITLE
cli: Don't wait for OCI delete to stop the sandbox

### LINKED ISSUE #197: "context deadline exceeded" when deleting a pod using openshift
# Description of problem

When trying Openshift using CRI-O and Kata-Containers, I can launch workloads, but when trying to delete a pod using: 
```
$ sudo -E oc delete pod hello-openshift
pod "hello-openshift" deleted
```
 I see `context deadline exceeded` errors in the logs:
```
Apr 10 19:00:29 openshift-test kata-runtime[9275]: time="2018-04-10T19:00:29.881459892Z" level=info msg="Container already stopped" arch=amd64 container-id=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a name=kata-runtime pid=9275 pod-id=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a source=virtcontainers subsystem=container
Apr 10 19:00:34 openshift-test kata-runtime[9275]: time="2018-04-10T19:00:34.881763723Z" level=error msg="context deadline exceeded" command=delete name=kata-runtime pid=9275 source=runtime
Apr 10 19:01:34 openshift-test kata-runtime[9552]: time="2018-04-10T19:01:34.895410205Z" level=debug msg="loaded configuration" command=delete format=TOML name=kata-runtime pid=9552 source=runtime
Apr 10 19:01:34 openshift-test kata-runtime[9552]: time="2018-04-10T19:01:34.895654206Z" level=info arguments="\"delete --force 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a\"" command=delete commit=59328030882945ef2026ea9a3da40bad0b4db472 name=kata-runtime pid=9552 source=runtime version=0.1.0
```

 Also, after deleting the pod,  `kata-runtime list` does not work correctly.
```
$ sudo kata-runtime list
stat /var/lib/containers/storage/devicemapper/mnt/3b81990183f99f803b18421317a8cf93d76b870c39d14a9a9d03fb76d2f7d93e/rootfs: no such file or directory
```
# Expected result

Pod should be removed correctly

# Actual result

Pod is not deleted correctly.
`kata-runtime list` does not work correctly. 

# Logs
Openshift node log:
```
E0410 19:22:15.254069    4577 remote_runtime.go:131] RemovePodSandbox "58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a" from runtime service failed: rpc error: code = 2 desc = failed to delete container k8s_POD_hello-openshift_default_92c7c393-3cef-11e8-a633-000d3afd2cb5_0 in pod sandbox 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a: `/usr/local/bin/kata-runtime delete --force 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a` failed: context deadline exceeded
  (exit status 1)
E0410 19:22:15.254116    4577 kuberuntime_gc.go:156] Failed to remove sandbox "58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a": rpc error: code = 2 desc = failed to delete container k8s_POD_hello-openshift_default_92c7c393-3cef-11e8-a633-000d3afd2cb5_0 in pod sandbox 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a: `/usr/local/bin/kata-runtime delete --force 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a` failed: context deadline exceeded
  (exit status 1)
```

CRI-O Logs:
```
Apr 10 18:59:47 openshift-test crio[4473]: ount{ContainerPath:/dev/termination-log,HostPath:/home/fuentess/go/src/github.com/kata-containers/tests/integration/openshift/openshift.local.volumes/pods/92c7c393-3cef
-11e8-a633-000d3afd2cb5/containers/hello-openshift/469e9463,Readonly:false,SelinuxRelabel:false,Propagation:PROPAGATION_PRIVATE,}],LogPath:,},Info:map[string]string{},}"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.351889607Z" level=debug msg="RemoveContainerRequest: &RemoveContainerRequest{ContainerId:dca6febc05d996125ea87bac34aa86241a652e6d4ad82632d59a2
3148f12eae9,}"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.367557161Z" level=debug msg="StopContainerResponse dca6febc05d996125ea87bac34aa86241a652e6d4ad82632d59a23148f12eae9: &StopContainerResponse{}"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.370281370Z" level=debug msg="devmapper: DeleteDevice START(hash=e21309cfc2ef674ae284ed2546276a06e7fec5b9adb0bdc3219e386dadd45cc3 syncDelete=fa
lse)"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.370341670Z" level=debug msg="devmapper: issueDiscard START(device: e21309cfc2ef674ae284ed2546276a06e7fec5b9adb0bdc3219e386dadd45cc3)."
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.370356270Z" level=debug msg="devmapper: activateDeviceIfNeeded(e21309cfc2ef674ae284ed2546276a06e7fec5b9adb0bdc3219e386dadd45cc3)"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.370396571Z" level=debug msg="StopPodSandboxRequest &StopPodSandboxRequest{PodSandboxId:58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47
d13c8246a,}"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.370443371Z" level=info msg="Got pod network {Name:hello-openshift Namespace:default ID:58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47
d13c8246a NetNS:/var/run/netns/k8s_hello-openshift_default_92c7c393-3cef-11e8-a633-000d3afd2cb5_0-6eac9e89 PortMappings:[]}"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.370464371Z" level=info msg="About to del CNI network mynet (type=bridge)"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.370748472Z" level=debug msg="event: "/var/run/crio/exits/dca6febc05d996125ea87bac34aa86241a652e6d4ad82632d59a23148f12eae9": REMOVE"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.439169608Z" level=debug msg="event: "/var/run/crio/exits/58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a.WVW7GZ": CREATE"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.439195609Z" level=debug msg="container or sandbox exited: 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a.WVW7GZ"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.439226709Z" level=debug msg="event: "/var/run/crio/exits/58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a.WVW7GZ": RENAME"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.439425709Z" level=debug msg="event: "/var/run/crio/exits/58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a": CREATE"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.439443709Z" level=debug msg="container or sandbox exited: 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.439456309Z" level=debug msg="sandbox exited and found: 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.722096087Z" level=debug msg="devmapper: issueDiscard END(device: e21309cfc2ef674ae284ed2546276a06e7fec5b9adb0bdc3219e386dadd45cc3)."
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.722446188Z" level=debug msg="devmapper: deactivateDevice START(e21309cfc2ef674ae284ed2546276a06e7fec5b9adb0bdc3219e386dadd45cc3)"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.722820490Z" level=debug msg="devmapper: removeDevice START(container-8:1-1285808-e21309cfc2ef674ae284ed2546276a06e7fec5b9adb0bdc3219e386dadd45
cc3)"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.759658217Z" level=debug msg="devmapper: removeDevice END(container-8:1-1285808-e21309cfc2ef674ae284ed2546276a06e7fec5b9adb0bdc3219e386dadd45cc
3)"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.759683517Z" level=debug msg="devmapper: deactivateDevice END(e21309cfc2ef674ae284ed2546276a06e7fec5b9adb0bdc3219e386dadd45cc3)"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.845801415Z" level=debug msg="ListPodSandboxRequest &ListPodSandboxRequest{Filter:&PodSandboxFilter{Id:,State:&PodSandboxStateValue{State:SANDB
OX_READY,},LabelSelector:map[string]string{},},}"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.917682164Z" level=debug msg="devmapper: unregisterDevice(e21309cfc2ef674ae284ed2546276a06e7fec5b9adb0bdc3219e386dadd45cc3)"
Apr 10 18:59:47 openshift-test crio[4473]: time="2018-04-10 18:59:47.925631091Z" level=debug msg="devmapper: DeleteDevice END(hash=e21309cfc2ef674ae284ed2546276a06e7fec5b9adb0bdc3219e386dadd45cc3 syncDelete=fals
e)"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.028076945Z" level=debug msg="RemoveContainerResponse: &RemoveContainerResponse{}"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.052716131Z" level=debug msg="ListPodSandboxResponse &ListPodSandboxResponse{Items:[],}"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.053154532Z" level=debug msg="ListContainersRequest &ListContainersRequest{Filter:&ContainerFilter{Id:,State:&ContainerStateValue{State:CONTAIN
ER_RUNNING,},PodSandboxId:,LabelSelector:map[string]string{},},}"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.053190032Z" level=debug msg="ListContainersResponse: &ListContainersResponse{Containers:[],}"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.063446768Z" level=debug msg="devmapper: UnmountDevice START(hash=3b81990183f99f803b18421317a8cf93d76b870c39d14a9a9d03fb76d2f7d93e)"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.063478468Z" level=debug msg="devmapper: Unmount(/var/lib/containers/storage/devicemapper/mnt/3b81990183f99f803b18421317a8cf93d76b870c39d14a9a9
d03fb76d2f7d93e)"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.132364206Z" level=debug msg="devmapper: Unmount done"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.132407106Z" level=debug msg="devmapper: deactivateDevice START(3b81990183f99f803b18421317a8cf93d76b870c39d14a9a9d03fb76d2f7d93e)"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.132490706Z" level=debug msg="devmapper: removeDevice START(container-8:1-1285808-3b81990183f99f803b18421317a8cf93d76b870c39d14a9a9d03fb76d2f7d
93e)"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.171648642Z" level=debug msg="devmapper: removeDevice END(container-8:1-1285808-3b81990183f99f803b18421317a8cf93d76b870c39d14a9a9d03fb76d2f7d93
e)"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.172239344Z" level=debug msg="devmapper: deactivateDevice END(3b81990183f99f803b18421317a8cf93d76b870c39d14a9a9d03fb76d2f7d93e)"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.172259044Z" level=debug msg="devmapper: UnmountDevice END(hash=3b81990183f99f803b18421317a8cf93d76b870c39d14a9a9d03fb76d2f7d93e)"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.186580093Z" level=debug msg="unmounted container "58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a""
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.186613393Z" level=debug msg="StopPodSandboxResponse 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a: &StopPodSandboxResponse{
}"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.349935158Z" level=debug msg="ListPodSandboxRequest &ListPodSandboxRequest{Filter:nil,}"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.349999558Z" level=debug msg="ListPodSandboxResponse &ListPodSandboxResponse{Items:[&PodSandbox{Id:58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271
090f227dc47d13c8246a,Metadata:&PodSandboxMetadata{Name:hello-openshift,Uid:92c7c393-3cef-11e8-a633-000d3afd2cb5,Namespace:default,Attempt:0,},State:SANDBOX_NOTREADY,CreatedAt:1523386034523581480,Labels:map[strin
g]string{io.kubernetes.container.name: POD,io.kubernetes.pod.name: hello-openshift,io.kubernetes.pod.namespace: default,io.kubernetes.pod.uid: 92c7c393-3cef-11e8-a633-000d3afd2cb5,name: hello-openshift,},Annotat
ions:map[string]string{io.kubernetes.cri-o.TrustedSandbox: false,kubernetes.io/config.seen: 2018-04-10T18:47:09.29505955Z,kubernetes.io/config.source: api,openshift.io/scc: anyuid,},}],}"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.350411660Z" level=debug msg="ListContainersRequest &ListContainersRequest{Filter:&ContainerFilter{Id:,State:nil,PodSandboxId:,LabelSelector:ma
p[string]string{},},}"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.350431560Z" level=debug msg="ListContainersResponse: &ListContainersResponse{Containers:[],}"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.350778561Z" level=debug msg="ListPodSandboxRequest &ListPodSandboxRequest{Filter:&PodSandboxFilter{Id:,State:nil,LabelSelector:map[string]stri
ng{io.kubernetes.pod.uid: 92c7c393-3cef-11e8-a633-000d3afd2cb5,},},}"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.350824861Z" level=debug msg="ListPodSandboxResponse &ListPodSandboxResponse{Items:[&PodSandbox{Id:58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271
090f227dc47d13c8246a,Metadata:&PodSandboxMetadata{Name:hello-openshift,Uid:92c7c393-3cef-11e8-a633-000d3afd2cb5,Namespace:default,Attempt:0,},State:SANDBOX_NOTREADY,CreatedAt:1523386034523581480,Labels:map[strin
g]string{io.kubernetes.container.name: POD,io.kubernetes.pod.name: hello-openshift,io.kubernetes.pod.namespace: default,io.kubernetes.pod.uid: 92c7c393-3cef-11e8-a633-000d3afd2cb5,name: hello-openshift,},Annotat
ions:map[string]string{io.kubernetes.cri-o.TrustedSandbox: false,kubernetes.io/config.seen: 2018-04-10T18:47:09.29505955Z,kubernetes.io/config.source: api,openshift.io/scc: anyuid,},}],}"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.351097962Z" level=debug msg="PodSandboxStatusRequest &PodSandboxStatusRequest{PodSandboxId:58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227
dc47d13c8246a,Verbose:false,}"
Apr 10 18:59:48 openshift-test crio[4473]: time="2018-04-10 18:59:48.351157262Z" level=debug msg="PodSandboxStatusResponse: &PodSandboxStatusResponse{Status:&PodSandboxStatus{Id:58b5cb85d95895239edc9fd0d0ba67c9b
ad5c28e6271090f227dc47d13c8246a,Metadata:&PodSandboxMetadata{Name:hello-openshift,Uid:92c7c393-3cef-11e8-a633-000d3afd2cb5,Namespace:default,Attempt:0,},State:SANDBOX_NOTREADY,CreatedAt:1523386034523581480,Netwo
rk:&PodSandboxNetworkStatus{Ip:10.88.0.3,},Linux:nil,Labels:map[string]string{io.kubernetes.container.name: POD,io.kubernetes.pod.name: hello-openshift,io.kubernetes.pod.namespace: default,io.kubernetes.pod.uid:
 92c7c393-3cef-11e8-a633-000d3afd2cb5,name: hello-openshift,},Annotations:map[string]string{io.kubernetes.cri-o.TrustedSandbox: false,kubernetes.io/config.seen: 2018-04-10T18:47:09.29505955Z,kubernetes.io/config
.source: api,openshift.io/scc: anyuid,},},Info:map[string]string{},}"
```

Kata runtime log:
```
Apr 10 18:59:47 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:47.426600565Z" level=debug msg="loaded configuration" command=kill format=TOML name=kata-runtime pid=9056 source=runtime
Apr 10 18:59:47 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:47.427034467Z" level=info arguments="\"kill 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a TERM\"" command=kill commit=
59328030882945ef2026ea9a3da40bad0b4db472 name=kata-runtime pid=9056 source=runtime version=0.1.0
Apr 10 18:59:47 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:47.429522075Z" level=info msg="Virtual endpoint unmarshalled [{{308bcf59-a117-4bf5-b6c0-820e49367f76 br0 {eth0 02:00:ca:fe:00:00 [10.88.0
.3/16 eth0]} {tap0 e6:36:b6:18:d7:d1 []} 2 [0xc42000e1b8 0xc42000e1c8 0xc42000e1d0 0xc42000e1d8 0xc42000e1e0 0xc42000e1e8 0xc42000e1f0 0xc42000e1f8] [0xc42000e200 0xc42000e208 0xc42000e210 0xc42000e218 0xc42000e
220 0xc42000e228 0xc42000e230 0xc42000e238]} {{{3 1500 0 eth0 e6:36:b6:18:d7:d1 up|broadcast|multicast 69699 5 0 <nil>  0xc420174240 0 0xc4200756a0 ether <nil> up 0 0 0} veth} [10.88.0.3/16 eth0 fe80::e436:b6ff:
fe18:d7d1/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.88.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.88.0.0/16 Src: 10.88.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> F
lags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=9056 source=virtcontainers
Apr 10 18:59:47 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:47.431430882Z" level=info msg="Virtual endpoint unmarshalled [{{308bcf59-a117-4bf5-b6c0-820e49367f76 br0 {eth0 02:00:ca:fe:00:00 [10.88.0
.3/16 eth0]} {tap0 e6:36:b6:18:d7:d1 []} 2 [0xc42000e2f0 0xc42000e2f8 0xc42000e300 0xc42000e308 0xc42000e310 0xc42000e318 0xc42000e320 0xc42000e328] [0xc42000e330 0xc42000e338 0xc42000e340 0xc42000e348 0xc42000e
350 0xc42000e358 0xc42000e360 0xc42000e368]} {{{3 1500 0 eth0 e6:36:b6:18:d7:d1 up|broadcast|multicast 69699 5 0 <nil>  0xc420174600 0 0xc420075de0 ether <nil> up 0 0 0} veth} [10.88.0.3/16 eth0 fe80::e436:b6ff:
fe18:d7d1/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.88.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.88.0.0/16 Src: 10.88.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> F
lags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=9056 source=virtcontainers
Apr 10 18:59:47 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:47.441579717Z" level=info msg="Virtual endpoint unmarshalled [{{308bcf59-a117-4bf5-b6c0-820e49367f76 br0 {eth0 02:00:ca:fe:00:00 [10.88.0
.3/16 eth0]} {tap0 e6:36:b6:18:d7:d1 []} 2 [0xc420290050 0xc420290058 0xc420290060 0xc420290068 0xc420290070 0xc420290078 0xc420290080 0xc420290088] [0xc420290090 0xc420290098 0xc4202900a0 0xc4202900a8 0xc420290
0b0 0xc4202900b8 0xc4202900c0 0xc4202900c8]} {{{3 1500 0 eth0 e6:36:b6:18:d7:d1 up|broadcast|multicast 69699 5 0 <nil>  0xc4202c2180 0 0xc4202784c0 ether <nil> up 0 0 0} veth} [10.88.0.3/16 eth0 fe80::e436:b6ff:
fe18:d7d1/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.88.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.88.0.0/16 Src: 10.88.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> F
lags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=9056 source=virtcontainers
Apr 10 18:59:48 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:48.011279487Z" level=info msg="unplugging block device" arch=amd64 container-id=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d1
3c8246a name=kata-runtime pid=9056 pod-id=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a source=virtcontainers subsystem=container
Apr 10 18:59:48 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:48.011443688Z" level=info msg="Unplugging block device" arch=amd64 container-id=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d1
3c8246a device-id=drive-58b5cb85d95895239edc9fd0d name=kata-runtime pid=9056 pod-id=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a source=virtcontainers subsystem=container
Apr 10 18:59:48 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:48.011855489Z" level=info msg="{\"QMP\": {\"version\": {\"qemu\": {\"micro\": 1, \"minor\": 11, \"major\": 2}, \"package\": \" (v2.11.1-d
irty)\"}, \"capabilities\": []}}" arch=amd64 name=kata-runtime pid=9056 source=virtcontainers subsystem=qmp
Apr 10 18:59:48 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:48.01213219Z" level=info msg="{\"execute\":\"qmp_capabilities\"}" arch=amd64 name=kata-runtime pid=9056 source=virtcontainers subsystem=q
mp
Apr 10 18:59:48 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:48.013092394Z" level=info msg="{\"return\": {}}" arch=amd64 name=kata-runtime pid=9056 source=virtcontainers subsystem=qmp
Apr 10 18:59:48 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:48.013644495Z" level=info msg="{\"arguments\":{\"id\":\"virtio-drive-58b5cb85d95895239edc9fd0d\"},\"execute\":\"device_del\"}" arch=amd64
 name=kata-runtime pid=9056 source=virtcontainers subsystem=qmp
Apr 10 18:59:48 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:48.015972004Z" level=info msg="{\"timestamp\": {\"seconds\": 1523386788, \"microseconds\": 15806}, \"event\": \"DEVICE_DELETED\", \"data\
": {\"device\": \"virtio-drive-58b5cb85d95895239edc9fd0d\", \"path\": \"/machine/peripheral/virtio-drive-58b5cb85d95895239edc9fd0d\"}}" arch=amd64 name=kata-runtime pid=9056 source=virtcontainers subsystem=qmp
Apr 10 18:59:48 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:48.016441205Z" level=info msg="{\"return\": {}}" arch=amd64 name=kata-runtime pid=9056 source=virtcontainers subsystem=qmp
Apr 10 18:59:48 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:48.016883007Z" level=info msg="{\"arguments\":{\"node-name\":\"drive-58b5cb85d95895239edc9fd0d\"},\"execute\":\"blockdev-del\"}" arch=amd
64 name=kata-runtime pid=9056 source=virtcontainers subsystem=qmp
Apr 10 18:59:48 openshift-test kata-runtime[9056]: time="2018-04-10T18:59:48.022047025Z" level=info msg="{\"return\": {}}" arch=amd64 name=kata-runtime pid=9056 source=virtcontainers subsystem=qmp
Apr 10 18:59:48 openshift-test kata-runtime[9075]: time="2018-04-10T18:59:48.036938376Z" level=debug msg="loaded configuration" command=state format=TOML name=kata-runtime pid=9075 source=runtime
Apr 10 18:59:48 openshift-test kata-runtime[9075]: time="2018-04-10T18:59:48.037227277Z" level=info arguments="\"state 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a\"" command=state commit=593
28030882945ef2026ea9a3da40bad0b4db472 name=kata-runtime pid=9075 source=runtime version=0.1.0
Apr 10 18:59:48 openshift-test kata-runtime[9075]: time="2018-04-10T18:59:48.039496985Z" level=info msg="Virtual endpoint unmarshalled [{{308bcf59-a117-4bf5-b6c0-820e49367f76 br0 {eth0 02:00:ca:fe:00:00 [10.88.0
.3/16 eth0]} {tap0 e6:36:b6:18:d7:d1 []} 2 [0xc4201cc158 0xc4201cc168 0xc4201cc170 0xc4201cc178 0xc4201cc180 0xc4201cc188 0xc4201cc190 0xc4201cc198] [0xc4201cc1a0 0xc4201cc1a8 0xc4201cc1b0 0xc4201cc1b8 0xc4201cc
1c0 0xc4201cc1c8 0xc4201cc1d0 0xc4201cc1d8]} {{{3 1500 0 eth0 e6:36:b6:18:d7:d1 up|broadcast|multicast 69699 5 0 <nil>  0xc420242180 0 0xc4201b3160 ether <nil> up 0 0 0} veth} [10.88.0.3/16 eth0 fe80::e436:b6ff:
fe18:d7d1/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.88.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.88.0.0/16 Src: 10.88.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> F
lags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=9075 source=virtcontainers
Apr 10 18:59:48 openshift-test kata-runtime[9082]: time="2018-04-10T18:59:48.047109311Z" level=debug msg="loaded configuration" command=state format=TOML name=kata-runtime pid=9082 source=runtime
Apr 10 18:59:48 openshift-test kata-runtime[9082]: time="2018-04-10T18:59:48.047456212Z" level=info arguments="\"state 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a\"" command=state commit=593
28030882945ef2026ea9a3da40bad0b4db472 name=kata-runtime pid=9082 source=runtime version=0.1.0
Apr 10 18:59:48 openshift-test kata-runtime[9082]: time="2018-04-10T18:59:48.050310322Z" level=info msg="Virtual endpoint unmarshalled [{{308bcf59-a117-4bf5-b6c0-820e49367f76 br0 {eth0 02:00:ca:fe:00:00 [10.88.0
.3/16 eth0]} {tap0 e6:36:b6:18:d7:d1 []} 2 [0xc42000e1c0 0xc42000e1d0 0xc42000e1d8 0xc42000e1e0 0xc42000e1e8 0xc42000e1f0 0xc42000e1f8 0xc42000e200] [0xc42000e208 0xc42000e210 0xc42000e218 0xc42000e220 0xc42000e
228 0xc42000e230 0xc42000e238 0xc42000e240]} {{{3 1500 0 eth0 e6:36:b6:18:d7:d1 up|broadcast|multicast 69699 5 0 <nil>  0xc420174240 0 0xc4200756a0 ether <nil> up 0 0 0} veth} [10.88.0.3/16 eth0 fe80::e436:b6ff:
fe18:d7d1/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.88.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.88.0.0/16 Src: 10.88.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> F
lags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=9082 source=virtcontainers
Apr 10 19:00:29 openshift-test kata-runtime[9275]: time="2018-04-10T19:00:29.876299875Z" level=debug msg="loaded configuration" command=delete format=TOML name=kata-runtime pid=9275 source=runtime
Apr 10 19:00:29 openshift-test kata-runtime[9275]: time="2018-04-10T19:00:29.876549976Z" level=info arguments="\"delete --force 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a\"" command=delete
commit=59328030882945ef2026ea9a3da40bad0b4db472 name=kata-runtime pid=9275 source=runtime version=0.1.0
Apr 10 19:00:29 openshift-test kata-runtime[9275]: time="2018-04-10T19:00:29.879083284Z" level=info msg="Virtual endpoint unmarshalled [{{308bcf59-a117-4bf5-b6c0-820e49367f76 br0 {eth0 02:00:ca:fe:00:00 [10.88.0
.3/16 eth0]} {tap0 e6:36:b6:18:d7:d1 []} 2 [0xc4201b2160 0xc4201b2170 0xc4201b2178 0xc4201b2180 0xc4201b2188 0xc4201b2190 0xc4201b2198 0xc4201b21a0] [0xc4201b21a8 0xc4201b21b0 0xc4201b21b8 0xc4201b21c0 0xc4201b2
1c8 0xc4201b21d0 0xc4201b21d8 0xc4201b21e0]} {{{3 1500 0 eth0 e6:36:b6:18:d7:d1 up|broadcast|multicast 69699 5 0 <nil>  0xc420222180 0 0xc420197160 ether <nil> up 0 0 0} veth} [10.88.0.3/16 eth0 fe80::e436:b6ff:
fe18:d7d1/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.88.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.88.0.0/16 Src: 10.88.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> F
lags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=9275 source=virtcontainers
Apr 10 19:00:29 openshift-test kata-runtime[9275]: time="2018-04-10T19:00:29.881131491Z" level=info msg="Virtual endpoint unmarshalled [{{308bcf59-a117-4bf5-b6c0-820e49367f76 br0 {eth0 02:00:ca:fe:00:00 [10.88.0
.3/16 eth0]} {tap0 e6:36:b6:18:d7:d1 []} 2 [0xc4201b22a0 0xc4201b22a8 0xc4201b22b0 0xc4201b22b8 0xc4201b22c0 0xc4201b22c8 0xc4201b22d0 0xc4201b22d8] [0xc4201b22e0 0xc4201b22e8 0xc4201b22f0 0xc4201b22f8 0xc4201b2
300 0xc4201b2308 0xc4201b2310 0xc4201b2318]} {{{3 1500 0 eth0 e6:36:b6:18:d7:d1 up|broadcast|multicast 69699 5 0 <nil>  0xc420222540 0 0xc420197ca0 ether <nil> up 0 0 0} veth} [10.88.0.3/16 eth0 fe80::e436:b6ff:
fe18:d7d1/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.88.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.88.0.0/16 Src: 10.88.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> F
lags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=9275 source=virtcontainers
Apr 10 19:00:29 openshift-test kata-runtime[9275]: time="2018-04-10T19:00:29.881459892Z" level=info msg="Container already stopped" arch=amd64 container-id=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47
d13c8246a name=kata-runtime pid=9275 pod-id=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a source=virtcontainers subsystem=container
Apr 10 19:00:34 openshift-test kata-runtime[9275]: time="2018-04-10T19:00:34.881763723Z" level=error msg="context deadline exceeded" command=delete name=kata-runtime pid=9275 source=runtime
Apr 10 19:01:34 openshift-test kata-runtime[9552]: time="2018-04-10T19:01:34.895410205Z" level=debug msg="loaded configuration" command=delete format=TOML name=kata-runtime pid=9552 source=runtime
Apr 10 19:01:34 openshift-test kata-runtime[9552]: time="2018-04-10T19:01:34.895654206Z" level=info arguments="\"delete --force 58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a\"" command=delete
commit=59328030882945ef2026ea9a3da40bad0b4db472 name=kata-runtime pid=9552 source=runtime version=0.1.0
Apr 10 19:01:34 openshift-test kata-runtime[9552]: time="2018-04-10T19:01:34.897685513Z" level=info msg="Virtual endpoint unmarshalled [{{308bcf59-a117-4bf5-b6c0-820e49367f76 br0 {eth0 02:00:ca:fe:00:00 [10.88.0
.3/16 eth0]} {tap0 e6:36:b6:18:d7:d1 []} 2 [0xc4201b8160 0xc4201b8170 0xc4201b8178 0xc4201b8180 0xc4201b8188 0xc4201b8190 0xc4201b8198 0xc4201b81a0] [0xc4201b81a8 0xc4201b81b0 0xc4201b81b8 0xc4201b81c0 0xc4201b8
1c8 0xc4201b81d0 0xc4201b81d8 0xc4201b81e0]} {{{3 1500 0 eth0 e6:36:b6:18:d7:d1 up|broadcast|multicast 69699 5 0 <nil>  0xc420228180 0 0xc42019d160 ether <nil> up 0 0 0} veth} [10.88.0.3/16 eth0 fe80::e436:b6ff:
fe18:d7d1/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.88.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.88.0.0/16 Src: 10.88.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> F
lags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=9552 source=virtcontainers
Apr 10 19:01:34 openshift-test kata-runtime[9552]: time="2018-04-10T19:01:34.899703319Z" level=info msg="Virtual endpoint unmarshalled [{{308bcf59-a117-4bf5-b6c0-820e49367f76 br0 {eth0 02:00:ca:fe:00:00 [10.88.0
.3/16 eth0]} {tap0 e6:36:b6:18:d7:d1 []} 2 [0xc4201b82a0 0xc4201b82a8 0xc4201b82b0 0xc4201b82b8 0xc4201b82c0 0xc4201b82c8 0xc4201b82d0 0xc4201b82d8] [0xc4201b82e0 0xc4201b82e8 0xc4201b82f0 0xc4201b82f8 0xc4201b8
300 0xc4201b8308 0xc4201b8310 0xc4201b8318]} {{{3 1500 0 eth0 e6:36:b6:18:d7:d1 up|broadcast|multicast 69699 5 0 <nil>  0xc420228540 0 0xc42019dca0 ether <nil> up 0 0 0} veth} [10.88.0.3/16 eth0 fe80::e436:b6ff:
fe18:d7d1/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.88.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.88.0.0/16 Src: 10.88.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> F
lags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=9552 source=virtcontainers
Apr 10 19:01:34 openshift-test kata-runtime[9552]: time="2018-04-10T19:01:34.900059421Z" level=info msg="Container already stopped" arch=amd64 container-id=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47
d13c8246a name=kata-runtime pid=9552 pod-id=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a source=virtcontainers subsystem=container
Apr 10 19:01:39 openshift-test kata-runtime[9552]: time="2018-04-10T19:01:39.900358807Z" level=error msg="context deadline exceeded" command=delete name=kata-runtime pid=9552 source=runtime
```

Kata Proxy Log:
```
Apr 10 18:59:46 openshift-test kata-proxy[5456]: time="2018-04-10T18:59:46.921075516Z" level=info msg="[  750.699448] systemd-journald[68]: Sent WATCHDOG=1 notification.\n" name=kata-proxy pid=5456 source=agent
Apr 10 18:59:46 openshift-test kata-proxy[5456]: time="2018-04-10T18:59:46.921765919Z" level=info msg="time=\"2018-04-10T18:59:46.891697001Z\" level=debug msg=\"process exited\" name=kata-agent pid=183 source=ag
ent status=2\n" name=kata-proxy pid=5456 source=agent
Apr 10 18:59:47 openshift-test kata-proxy[5456]: time="2018-04-10T18:59:47.025085476Z" level=info msg="[  750.803835] XFS (sdb): Unmounting Filesystem\n" name=kata-proxy pid=5456 source=agent
Apr 10 18:59:47 openshift-test kata-proxy[5456]: time="2018-04-10T18:59:47.210463617Z" level=info msg="[  750.988926] sd 0:0:0:1: [sdb] Synchronizing SCSI cache\n" name=kata-proxy pid=5456 source=agent
Apr 10 18:59:47 openshift-test kata-proxy[5456]: time="2018-04-10T18:59:47.212457424Z" level=info msg="[  750.990979] sd 0:0:0:1: [sdb] Synchronize Cache(10) failed: Result: hostbyte=0x00 driverbyte=0x08\n" name
=kata-proxy pid=5456 source=agent
Apr 10 18:59:47 openshift-test kata-proxy[5456]: time="2018-04-10T18:59:47.213100227Z" level=info msg="[  750.991714] sd 0:0:0:1: [sdb] Sense Key : 0x5 [current] \n" name=kata-proxy pid=5456 source=agent
Apr 10 18:59:47 openshift-test kata-proxy[5456]: time="2018-04-10T18:59:47.213749629Z" level=info msg="[  750.992390] sd 0:0:0:1: [sdb] ASC=0x25 ASCQ=0x0 \n" name=kata-proxy pid=5456 source=agent
Apr 10 18:59:47 openshift-test kata-proxy[5456]: time="2018-04-10T18:59:47.436432299Z" level=info msg="time=\"2018-04-10T18:59:47.413437003Z\" level=debug msg=\"process exited\" name=kata-agent pid=143 source=ag
ent status=2\n" name=kata-proxy pid=5456 source=agent
Apr 10 18:59:47 openshift-test kata-proxy[5456]: time="2018-04-10T18:59:47.446896735Z" level=info msg="[  751.225724] XFS (sda): Unmounting Filesystem\n" name=kata-proxy pid=5456 source=agent
Apr 10 18:59:48 openshift-test kata-proxy[5456]: time="2018-04-10T18:59:48.018391112Z" level=info msg="[  751.797095] sd 0:0:0:0: [sda] Synchronizing SCSI cache\n" name=kata-proxy pid=5456 source=agent
Apr 10 18:59:48 openshift-test kata-proxy[5456]: time="2018-04-10T18:59:48.020328919Z" level=info msg="[  751.798841] sd 0:0:0:0: [sda] Synchronize Cache(10) failed: Result: hostbyte=0x04 driverbyte=0x00\n" name
=kata-proxy pid=5456 source=agent
```

Kata Shim Log:
```
Apr 10 18:47:18 openshift-test kata-shim[5481]: time="2018-04-10T18:47:18.222300509Z" level=info container=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a exec-id=58b5cb85d95895239edc9fd0d0ba67c
9bad5c28e6271090f227dc47d13c8246a name=kata-shim pid=1 source=shim version=0.0.1-2bdea2e41109b6b71c600899e1bf5794b125200d
Apr 10 18:47:18 openshift-test kata-shim[5481]: time="2018-04-10T18:47:18.235241537Z" level=info msg="Error getting window size" container=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a error="
inappropriate ioctl for device" exec-id=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a fd=0 name=kata-shim pid=1 source=shim
Apr 10 18:47:23 openshift-test kata-shim[5611]: time="2018-04-10T18:47:23.619074256Z" level=info container=dca6febc05d996125ea87bac34aa86241a652e6d4ad82632d59a23148f12eae9 exec-id=dca6febc05d996125ea87bac34aa862
41a652e6d4ad82632d59a23148f12eae9 name=kata-shim pid=1 source=shim version=0.0.1-2bdea2e41109b6b71c600899e1bf5794b125200d
Apr 10 18:47:23 openshift-test kata-shim[5611]: time="2018-04-10T18:47:23.619730057Z" level=info msg="Error getting window size" container=dca6febc05d996125ea87bac34aa86241a652e6d4ad82632d59a23148f12eae9 error="
inappropriate ioctl for device" exec-id=dca6febc05d996125ea87bac34aa86241a652e6d4ad82632d59a23148f12eae9 fd=0 name=kata-shim pid=1 source=shim
Apr 10 18:59:46 openshift-test kata-shim[5611]: time="2018-04-10T18:59:46.924504728Z" level=info msg="using shim to proxy exit code" container=dca6febc05d996125ea87bac34aa86241a652e6d4ad82632d59a23148f12eae9 exe
c-id=dca6febc05d996125ea87bac34aa86241a652e6d4ad82632d59a23148f12eae9 exitcode=2 name=kata-shim pid=1 source=shim
Apr 10 18:59:47 openshift-test kata-shim[5481]: time="2018-04-10T18:59:47.437922404Z" level=info msg="using shim to proxy exit code" container=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a exe
c-id=58b5cb85d95895239edc9fd0d0ba67c9bad5c28e6271090f227dc47d13c8246a exitcode=2 name=kata-shim pid=1 source=shim
```

---

CRI-O version: 1.9
Openshift version: 3.7.1
Latest Kata containers.

### PR DESCRIPTION
**Pull request by sboeuf**
This commit tries to address uses cases where the caller of the
runtime expects a kill to stop the container representing the pod,
meaning in our case the end of the VM.

This leads to some rework of the delete command since we want a
delete --force to always work, even if the container/pod has been
killed before.

Fixes #197

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@chavafg could you please try this patch with both `openshift` and `k8s`, it should fix the common issue that we have about the pod that cannot be deleted.

File: cli/delete.go [hunk 1]
```diff
@@ -104,9 +105,15 @@ func delete(containerID string, force bool) error {
 	return removeCgroupsPath(containerID, cgroupsPathList)
 }
 
-func deleteSandbox(sandboxID string) error {
-	if _, err := vci.StopSandbox(sandboxID); err != nil {
-		return err
+func deleteSandbox(sandboxID, containerID string, forceStop bool) error {
+	if forceStop {
```
[the remark this answers is not in the document]
Comment (sboeuf) [reply cli/delete.go]: Yes but I need to make sure this is the right thing to do and it fixes all issues before I spend some time on those tests.

[the remark this answers is not in the document]
Comment (jodh-intel) [reply cli/delete.go]: @sboeuf - in which case, I wonder if @grahamwhaley's [soak test](https://github.com/clearcontainers/tests/blob/master/integration/stability/soak_parallel_rm.sh) could help us in this regard?

[the remark this answers is not in the document]
Comment (sboeuf) [reply cli/delete.go]: I have in mind a more global PR. I am currently working on https://github.com/kata-containers/runtime/pull/213 (the unit tests are a nightmare...), but I hope I can update this one tomorrow.

[the remark this answers is not in the document]
Comment (grahamwhaley) [reply cli/delete.go]: For the soak test, we should look at https://github.com/kata-containers/tests/issues/195 or maybe preferably https://github.com/kata-containers/tests/issues/215 to add that ability/check to kata.

**Comment by chavafg** [comment]
Hi @sboeuf 
I am still checking this. The issues on openshift disappear, but on k8s I still have some similar issues, I am debugging and will paste more information once I have it.

**Comment by chavafg** [comment]
I see 2 kata-runtime errors here, one regarding networking:
Errors: 
```
Apr 20 13:49:43 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:43.046385153Z" level=error msg="rpc error: code = Internal desc = Could not remove network route dest:\"10.244.0.0/16\" gateway:\"10.244.
0.1\" device:\"eth0\" : rpc error: code = Internal desc = Could not remove route dest(10.244.0.0/16)/gw(10.244.0.1)/dev(eth0): no such process" command=kill name=kata-runtime pid=39205 source=runtime
Apr 20 13:50:26 openshift-fix kata-runtime[39397]: time="2018-04-20T13:50:26.257210268Z" level=error msg="Sandbox not ready, paused or stopped, impossible to delete" command=delete name=kata-runtime pid=39397 source=runtime
```

Container ID:
`b3177caca69e3f640d7b08e1b622fce1486429a5cddfd46b3d6bedfb2a304365`

Pod ID:
`c5777808b4fbb86bd9a0aed4bea6ccd7b00c6947a597ecf829c3996257e90ce3`

Full log:
```
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.214796518Z" level=debug msg="loaded configuration" command=kill format=TOML name=kata-runtime pid=39135 source=runtime
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.215271622Z" level=info arguments="\"kill b3177caca69e3f640d7b08e1b622fce1486429a5cddfd46b3d6bedfb2a304365 TERM\"" command=kill commit=3dd37470b0f03ed8fd65bb79a5b684a7e47e5369 name=kata-runtime pid=39135 source=runtime version=0.0.1
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.220023656Z" level=info msg="Virtual endpoint unmarshalled [{{eb091a44-b5c0-4c6b-a693-4c48b54412fa br0 {eth0 02:00:ca:fe:00:00 [10.244.0.2/24 eth0]} {tap0 0a:58:0a:f4:00:02 []} 2 [0xc4201b2158 0xc4201b2168 0xc4201b2170 0xc4201b2178 0xc4201b2180 0xc4201b2188 0xc4201b2190 0xc4201b2198] [0xc4201b21a0 0xc4201b21a8 0xc4201b21b0 0xc4201b21b8 0xc4201b21c0 0xc4201b21c8 0xc4201b21d0 0xc4201b21d8]} {{{3 1450 0 eth0 0a:58:0a:f4:00:02 up|broadcast|multicast 69699 67 0 <nil>  0xc420244240 0 0xc420197dc0 ether <nil> up 0 0 0} veth} [10.244.0.2/24 eth0 fe80::d8f7:50ff:fe41:f5b3/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.2 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39135 source=virtcontainers
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.222778876Z" level=info msg="Virtual endpoint unmarshalled [{{a3646dcb-f0b6-4192-8ec5-032003d81994 br0 {eth0 02:00:ca:fe:00:00 [10.244.0.3/24 eth0]} {tap0 0a:58:0a:f4:00:03 []} 2 [0xc4201b2308 0xc4201b2310 0xc4201b2318 0xc4201b2320 0xc4201b2328 0xc4201b2330 0xc4201b2338 0xc4201b2340] [0xc4201b2348 0xc4201b2350 0xc4201b2358 0xc4201b2360 0xc4201b2368 0xc4201b2370 0xc4201b2378 0xc4201b2380]} {{{3 1450 0 eth0 0a:58:0a:f4:00:03 up|broadcast|multicast 69699 68 0 <nil>  0xc420244600 0 0xc4202848c0 ether <nil> up 0 0 0} veth} [10.244.0.3/24 eth0 fe80::b408:87ff:fe33:9723/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39135 source=virtcontainers
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.547421732Z" level=info msg="unplugging block device" arch=amd64 container-id=b3177caca69e3f640d7b08e1b622fce1486429a5cddfd46b3d6bedfb2a304365 name=kata-runtime pid=39135 sandbox-id=c5777808b4fbb86bd9a0aed4bea6ccd7b00c6947a597ecf829c3996257e90ce3 source=virtcontainers subsystem=container
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.547607634Z" level=info msg="Unplugging block device" arch=amd64 container-id=b3177caca69e3f640d7b08e1b622fce1486429a5cddfd46b3d6bedfb2a304365 device-id=drive-b3177caca69e3f640d7b08e1b name=kata-runtime pid=39135 sandbox-id=c5777808b4fbb86bd9a0aed4bea6ccd7b00c6947a597ecf829c3996257e90ce3 source=virtcontainers subsystem=container
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.548050037Z" level=info msg="{\"QMP\": {\"version\": {\"qemu\": {\"micro\": 1, \"minor\": 11, \"major\": 2}, \"package\": \" (v2.11.1-dirty)\"}, \"capabilities\": []}}" arch=amd64 name=kata-runtime pid=39135 source=virtcontainers subsystem=qmp
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.548407139Z" level=info msg="{\"execute\":\"qmp_capabilities\"}" arch=amd64 name=kata-runtime pid=39135 source=virtcontainers subsystem=qmp
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.549298946Z" level=info msg="{\"return\": {}}" arch=amd64 name=kata-runtime pid=39135 source=virtcontainers subsystem=qmp
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.549461747Z" level=info msg="{\"arguments\":{\"id\":\"virtio-drive-b3177caca69e3f640d7b08e1b\"},\"execute\":\"device_del\"}" arch=amd64 name=kata-runtime pid=39135 source=virtcontainers subsystem=qmp
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.551762164Z" level=info msg="{\"timestamp\": {\"seconds\": 1524232182, \"microseconds\": 551667}, \"event\": \"DEVICE_DELETED\", \"data\": {\"device\": \"virtio-drive-b3177caca69e3f640d7b08e1b\", \"path\": \"/machine/peripheral/virtio-drive-b3177caca69e3f640d7b08e1b\"}}" arch=amd64 name=kata-runtime pid=39135 source=virtcontainers subsystem=qmp
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.551973665Z" level=info msg="{\"return\": {}}" arch=amd64 name=kata-runtime pid=39135 source=virtcontainers subsystem=qmp
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.552169367Z" level=info msg="{\"arguments\":{\"node-name\":\"drive-b3177caca69e3f640d7b08e1b\"},\"execute\":\"blockdev-del\"}" arch=amd64 name=kata-runtime pid=39135 source=virtcontainers subsystem=qmp
Apr 20 13:49:42 openshift-fix kata-runtime[39135]: time="2018-04-20T13:49:42.554691085Z" level=info msg="{\"return\": {}}" arch=amd64 name=kata-runtime pid=39135 source=virtcontainers subsystem=qmp
Apr 20 13:49:42 openshift-fix kata-runtime[39152]: time="2018-04-20T13:49:42.57741825Z" level=debug msg="loaded configuration" command=state format=TOML name=kata-runtime pid=39152 source=runtime
Apr 20 13:49:42 openshift-fix kata-runtime[39152]: time="2018-04-20T13:49:42.577783952Z" level=info arguments="\"state b3177caca69e3f640d7b08e1b622fce1486429a5cddfd46b3d6bedfb2a304365\"" command=state commit=3dd37470b0f03ed8fd65bb79a5b684a7e47e5369 name=kata-runtime pid=39152 source=runtime version=0.0.1
Apr 20 13:49:42 openshift-fix kata-runtime[39152]: time="2018-04-20T13:49:42.581947983Z" level=info msg="Virtual endpoint unmarshalled [{{eb091a44-b5c0-4c6b-a693-4c48b54412fa br0 {eth0 02:00:ca:fe:00:00 [10.244.0.2/24 eth0]} {tap0 0a:58:0a:f4:00:02 []} 2 [0xc4201b8158 0xc4201b8168 0xc4201b8170 0xc4201b8178 0xc4201b8180 0xc4201b8188 0xc4201b8190 0xc4201b8198] [0xc4201b81a0 0xc4201b81a8 0xc4201b81b0 0xc4201b81b8 0xc4201b81c0 0xc4201b81c8 0xc4201b81d0 0xc4201b81d8]} {{{3 1450 0 eth0 0a:58:0a:f4:00:02 up|broadcast|multicast 69699 67 0 <nil>  0xc42024e240 0 0xc42019fdc0 ether <nil> up 0 0 0} veth} [10.244.0.2/24 eth0 fe80::d8f7:50ff:fe41:f5b3/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.2 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39152 source=virtcontainers
Apr 20 13:49:42 openshift-fix kata-runtime[39152]: time="2018-04-20T13:49:42.58572591Z" level=info msg="Virtual endpoint unmarshalled [{{a3646dcb-f0b6-4192-8ec5-032003d81994 br0 {eth0 02:00:ca:fe:00:00 [10.244.0.3/24 eth0]} {tap0 0a:58:0a:f4:00:03 []} 2 [0xc4201b8308 0xc4201b8310 0xc4201b8318 0xc4201b8320 0xc4201b8328 0xc4201b8330 0xc4201b8338 0xc4201b8340] [0xc4201b8348 0xc4201b8350 0xc4201b8358 0xc4201b8360 0xc4201b8368 0xc4201b8370 0xc4201b8378 0xc4201b8380]} {{{3 1450 0 eth0 0a:58:0a:f4:00:03 up|broadcast|multicast 69699 68 0 <nil>  0xc42024e600 0 0xc4202888c0 ether <nil> up 0 0 0} veth} [10.244.0.3/24 eth0 fe80::b408:87ff:fe33:9723/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39152 source=virtcontainers
Apr 20 13:49:42 openshift-fix kata-runtime[39159]: time="2018-04-20T13:49:42.595099778Z" level=debug msg="loaded configuration" command=state format=TOML name=kata-runtime pid=39159 source=runtime
Apr 20 13:49:42 openshift-fix kata-runtime[39159]: time="2018-04-20T13:49:42.595437281Z" level=info arguments="\"state b3177caca69e3f640d7b08e1b622fce1486429a5cddfd46b3d6bedfb2a304365\"" command=state commit=3dd37470b0f03ed8fd65bb79a5b684a7e47e5369 name=kata-runtime pid=39159 source=runtime version=0.0.1
Apr 20 13:49:42 openshift-fix kata-runtime[39159]: time="2018-04-20T13:49:42.598956606Z" level=info msg="Virtual endpoint unmarshalled [{{eb091a44-b5c0-4c6b-a693-4c48b54412fa br0 {eth0 02:00:ca:fe:00:00 [10.244.0.2/24 eth0]} {tap0 0a:58:0a:f4:00:02 []} 2 [0xc42000e1b8 0xc42000e1c8 0xc42000e1d0 0xc42000e1d8 0xc42000e1e0 0xc42000e1e8 0xc42000e1f0 0xc42000e1f8] [0xc42000e200 0xc42000e208 0xc42000e210 0xc42000e218 0xc42000e220 0xc42000e228 0xc42000e230 0xc42000e238]} {{{3 1450 0 eth0 0a:58:0a:f4:00:02 up|broadcast|multicast 69699 67 0 <nil>  0xc420174300 0 0xc420218380 ether <nil> up 0 0 0} veth} [10.244.0.2/24 eth0 fe80::d8f7:50ff:fe41:f5b3/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.2 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39159 source=virtcontainers
Apr 20 13:49:42 openshift-fix kata-runtime[39159]: time="2018-04-20T13:49:42.602497832Z" level=info msg="Virtual endpoint unmarshalled [{{a3646dcb-f0b6-4192-8ec5-032003d81994 br0 {eth0 02:00:ca:fe:00:00 [10.244.0.3/24 eth0]} {tap0 0a:58:0a:f4:00:03 []} 2 [0xc42000e368 0xc42000e370 0xc42000e378 0xc42000e380 0xc42000e388 0xc42000e390 0xc42000e398 0xc42000e3a0] [0xc42000e3a8 0xc42000e3b0 0xc42000e3b8 0xc42000e3c0 0xc42000e3c8 0xc42000e3d0 0xc42000e3d8 0xc42000e3e0]} {{{3 1450 0 eth0 0a:58:0a:f4:00:03 up|broadcast|multicast 69699 68 0 <nil>  0xc4201746c0 0 0xc420218e80 ether <nil> up 0 0 0} veth} [10.244.0.3/24 eth0 fe80::b408:87ff:fe33:9723/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39159 source=virtcontainers
Apr 20 13:49:42 openshift-fix kata-runtime[39170]: time="2018-04-20T13:49:42.701603251Z" level=debug msg="loaded configuration" command=state format=TOML name=kata-runtime pid=39170 source=runtime
Apr 20 13:49:42 openshift-fix kata-runtime[39170]: time="2018-04-20T13:49:42.701974954Z" level=info arguments="\"state b3177caca69e3f640d7b08e1b622fce1486429a5cddfd46b3d6bedfb2a304365\"" command=state commit=3dd37470b0f03ed8fd65bb79a5b684a7e47e5369 name=kata-runtime pid=39170 source=runtime version=0.0.1
Apr 20 13:49:42 openshift-fix kata-runtime[39170]: time="2018-04-20T13:49:42.705499079Z" level=info msg="Virtual endpoint unmarshalled [{{eb091a44-b5c0-4c6b-a693-4c48b54412fa br0 {eth0 02:00:ca:fe:00:00 [10.244.0.2/24 eth0]} {tap0 0a:58:0a:f4:00:02 []} 2 [0xc4201ba158 0xc4201ba168 0xc4201ba170 0xc4201ba178 0xc4201ba180 0xc4201ba188 0xc4201ba190 0xc4201ba198] [0xc4201ba1a0 0xc4201ba1a8 0xc4201ba1b0 0xc4201ba1b8 0xc4201ba1c0 0xc4201ba1c8 0xc4201ba1d0 0xc4201ba1d8]} {{{3 1450 0 eth0 0a:58:0a:f4:00:02 up|broadcast|multicast 69699 67 0 <nil>  0xc420250240 0 0xc42019fdc0 ether <nil> up 0 0 0} veth} [10.244.0.2/24 eth0 fe80::d8f7:50ff:fe41:f5b3/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.2 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39170 source=virtcontainers
Apr 20 13:49:42 openshift-fix kata-runtime[39170]: time="2018-04-20T13:49:42.708512501Z" level=info msg="Virtual endpoint unmarshalled [{{a3646dcb-f0b6-4192-8ec5-032003d81994 br0 {eth0 02:00:ca:fe:00:00 [10.244.0.3/24 eth0]} {tap0 0a:58:0a:f4:00:03 []} 2 [0xc4201ba308 0xc4201ba310 0xc4201ba318 0xc4201ba320 0xc4201ba328 0xc4201ba330 0xc4201ba338 0xc4201ba340] [0xc4201ba348 0xc4201ba350 0xc4201ba358 0xc4201ba360 0xc4201ba368 0xc4201ba370 0xc4201ba378 0xc4201ba380]} {{{3 1450 0 eth0 0a:58:0a:f4:00:03 up|broadcast|multicast 69699 68 0 <nil>  0xc420250600 0 0xc42028a8c0 ether <nil> up 0 0 0} veth} [10.244.0.3/24 eth0 fe80::b408:87ff:fe33:9723/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39170 source=virtcontainers
Apr 20 13:49:42 openshift-fix kata-runtime[39177]: time="2018-04-20T13:49:42.726384431Z" level=debug msg="loaded configuration" command=state format=TOML name=kata-runtime pid=39177 source=runtime
Apr 20 13:49:42 openshift-fix kata-runtime[39177]: time="2018-04-20T13:49:42.726649833Z" level=info arguments="\"state b3177caca69e3f640d7b08e1b622fce1486429a5cddfd46b3d6bedfb2a304365\"" command=state commit=3dd37470b0f03ed8fd65bb79a5b684a7e47e5369 name=kata-runtime pid=39177 source=runtime version=0.0.1
Apr 20 13:49:42 openshift-fix kata-runtime[39177]: time="2018-04-20T13:49:42.730301159Z" level=info msg="Virtual endpoint unmarshalled [{{eb091a44-b5c0-4c6b-a693-4c48b54412fa br0 {eth0 02:00:ca:fe:00:00 [10.244.0.2/24 eth0]} {tap0 0a:58:0a:f4:00:02 []} 2 [0xc42000e1b8 0xc42000e1c8 0xc42000e1d0 0xc42000e1d8 0xc42000e1e0 0xc42000e1e8 0xc42000e1f0 0xc42000e1f8] [0xc42000e200 0xc42000e208 0xc42000e210 0xc42000e218 0xc42000e220 0xc42000e228 0xc42000e230 0xc42000e238]} {{{3 1450 0 eth0 0a:58:0a:f4:00:02 up|broadcast|multicast 69699 67 0 <nil>  0xc42017c300 0 0xc420216380 ether <nil> up 0 0 0} veth} [10.244.0.2/24 eth0 fe80::d8f7:50ff:fe41:f5b3/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.2 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39177 source=virtcontainers
Apr 20 13:49:42 openshift-fix kata-runtime[39177]: time="2018-04-20T13:49:42.73316618Z" level=info msg="Virtual endpoint unmarshalled [{{a3646dcb-f0b6-4192-8ec5-032003d81994 br0 {eth0 02:00:ca:fe:00:00 [10.244.0.3/24 eth0]} {tap0 0a:58:0a:f4:00:03 []} 2 [0xc42000e368 0xc42000e370 0xc42000e378 0xc42000e380 0xc42000e388 0xc42000e390 0xc42000e398 0xc42000e3a0] [0xc42000e3a8 0xc42000e3b0 0xc42000e3b8 0xc42000e3c0 0xc42000e3c8 0xc42000e3d0 0xc42000e3d8 0xc42000e3e0]} {{{3 1450 0 eth0 0a:58:0a:f4:00:03 up|broadcast|multicast 69699 68 0 <nil>  0xc42017c6c0 0 0xc420216e80 ether <nil> up 0 0 0} veth} [10.244.0.3/24 eth0 fe80::b408:87ff:fe33:9723/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39177 source=virtcontainers
Apr 20 13:49:42 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:42.807110717Z" level=debug msg="loaded configuration" command=kill format=TOML name=kata-runtime pid=39205 source=runtime
Apr 20 13:49:42 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:42.807448419Z" level=info arguments="\"kill c5777808b4fbb86bd9a0aed4bea6ccd7b00c6947a597ecf829c3996257e90ce3 TERM\"" command=kill commit=3dd37470b0f03ed8fd65bb79a5b684a7e47e5369 name=kata-runtime pid=39205 source=runtime version=0.0.1
Apr 20 13:49:42 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:42.810975945Z" level=info msg="Virtual endpoint unmarshalled [{{eb091a44-b5c0-4c6b-a693-4c48b54412fa br0 {eth0 02:00:ca:fe:00:00 [10.244.0.2/24 eth0]} {tap0 0a:58:0a:f4:00:02 []} 2 [0xc42000e1b8 0xc42000e1c8 0xc42000e1d0 0xc42000e1d8 0xc42000e1e0 0xc42000e1e8 0xc42000e1f0 0xc42000e1f8] [0xc42000e200 0xc42000e208 0xc42000e210 0xc42000e218 0xc42000e220 0xc42000e228 0xc42000e230 0xc42000e238]} {{{3 1450 0 eth0 0a:58:0a:f4:00:02 up|broadcast|multicast 69699 67 0 <nil>  0xc420176300 0 0xc42020e380 ether <nil> up 0 0 0} veth} [10.244.0.2/24 eth0 fe80::d8f7:50ff:fe41:f5b3/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.2 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39205 source=virtcontainers
Apr 20 13:49:42 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:42.813965766Z" level=info msg="Virtual endpoint unmarshalled [{{a3646dcb-f0b6-4192-8ec5-032003d81994 br0 {eth0 02:00:ca:fe:00:00 [10.244.0.3/24 eth0]} {tap0 0a:58:0a:f4:00:03 []} 2 [0xc42000e368 0xc42000e370 0xc42000e378 0xc42000e380 0xc42000e388 0xc42000e390 0xc42000e398 0xc42000e3a0] [0xc42000e3a8 0xc42000e3b0 0xc42000e3b8 0xc42000e3c0 0xc42000e3c8 0xc42000e3d0 0xc42000e3d8 0xc42000e3e0]} {{{3 1450 0 eth0 0a:58:0a:f4:00:03 up|broadcast|multicast 69699 68 0 <nil>  0xc4201766c0 0 0xc42020ee80 ether <nil> up 0 0 0} veth} [10.244.0.3/24 eth0 fe80::b408:87ff:fe33:9723/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39205 source=virtcontainers
Apr 20 13:49:43 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:43.019021754Z" level=info msg="unplugging block device" arch=amd64 container-id=c5777808b4fbb86bd9a0aed4bea6ccd7b00c6947a597ecf829c3996257e90ce3 name=kata-runtime pid=39205 sandbox-id=c5777808b4fbb86bd9a0aed4bea6ccd7b00c6947a597ecf829c3996257e90ce3 source=virtcontainers subsystem=container
Apr 20 13:49:43 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:43.019558858Z" level=info msg="Unplugging block device" arch=amd64 container-id=c5777808b4fbb86bd9a0aed4bea6ccd7b00c6947a597ecf829c3996257e90ce3 device-id=drive-c5777808b4fbb86bd9a0aed4b name=kata-runtime pid=39205 sandbox-id=c5777808b4fbb86bd9a0aed4bea6ccd7b00c6947a597ecf829c3996257e90ce3 source=virtcontainers subsystem=container
Apr 20 13:49:43 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:43.020042562Z" level=info msg="{\"QMP\": {\"version\": {\"qemu\": {\"micro\": 1, \"minor\": 11, \"major\": 2}, \"package\": \" (v2.11.1-dirty)\"}, \"capabilities\": []}}" arch=amd64 name=kata-runtime pid=39205 source=virtcontainers subsystem=qmp
Apr 20 13:49:43 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:43.020557865Z" level=info msg="{\"execute\":\"qmp_capabilities\"}" arch=amd64 name=kata-runtime pid=39205 source=virtcontainers subsystem=qmp
Apr 20 13:49:43 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:43.021595873Z" level=info msg="{\"return\": {}}" arch=amd64 name=kata-runtime pid=39205 source=virtcontainers subsystem=qmp
Apr 20 13:49:43 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:43.022105577Z" level=info msg="{\"arguments\":{\"id\":\"virtio-drive-c5777808b4fbb86bd9a0aed4b\"},\"execute\":\"device_del\"}" arch=amd64 name=kata-runtime pid=39205 source=virtcontainers subsystem=qmp
Apr 20 13:49:43 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:43.024642295Z" level=info msg="{\"timestamp\": {\"seconds\": 1524232183, \"microseconds\": 24525}, \"event\": \"DEVICE_DELETED\", \"data\": {\"device\": \"virtio-drive-c5777808b4fbb86bd9a0aed4b\", \"path\": \"/machine/peripheral/virtio-drive-c5777808b4fbb86bd9a0aed4b\"}}" arch=amd64 name=kata-runtime pid=39205 source=virtcontainers subsystem=qmp
Apr 20 13:49:43 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:43.024739296Z" level=info msg="{\"return\": {}}" arch=amd64 name=kata-runtime pid=39205 source=virtcontainers subsystem=qmp
Apr 20 13:49:43 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:43.024939097Z" level=info msg="{\"arguments\":{\"node-name\":\"drive-c5777808b4fbb86bd9a0aed4b\"},\"execute\":\"blockdev-del\"}" arch=amd64 name=kata-runtime pid=39205 source=virtcontainers subsystem=qmp
Apr 20 13:49:43 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:43.028973226Z" level=info msg="{\"return\": {}}" arch=amd64 name=kata-runtime pid=39205 source=virtcontainers subsystem=qmp
Apr 20 13:49:43 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:43.02949713Z" level=info msg="Container already stopped" arch=amd64 container-id=b3177caca69e3f640d7b08e1b622fce1486429a5cddfd46b3d6bedfb2a304365 name=kata-runtime pid=39205 sandbox-id=c5777808b4fbb86bd9a0aed4bea6ccd7b00c6947a597ecf829c3996257e90ce3 source=virtcontainers subsystem=container
Apr 20 13:49:43 openshift-fix kata-runtime[39205]: time="2018-04-20T13:49:43.046385153Z" level=error msg="rpc error: code = Internal desc = Could not remove network route dest:\"10.244.0.0/16\" gateway:\"10.244.0.1\" device:\"eth0\" : rpc error: code = Internal desc = Could not remove route dest(10.244.0.0/16)/gw(10.244.0.1)/dev(eth0): no such process" command=kill name=kata-runtime pid=39205 source=runtime
Apr 20 13:49:43 openshift-fix kata-runtime[39217]: time="2018-04-20T13:49:43.059678549Z" level=debug msg="loaded configuration" command=state format=TOML name=kata-runtime pid=39217 source=runtime
Apr 20 13:49:43 openshift-fix kata-runtime[39217]: time="2018-04-20T13:49:43.060313654Z" level=info arguments="\"state c5777808b4fbb86bd9a0aed4bea6ccd7b00c6947a597ecf829c3996257e90ce3\"" command=state commit=3dd37470b0f03ed8fd65bb79a5b684a7e47e5369 name=kata-runtime pid=39217 source=runtime version=0.0.1
Apr 20 13:49:43 openshift-fix kata-runtime[39217]: time="2018-04-20T13:49:43.064180382Z" level=info msg="Virtual endpoint unmarshalled [{{eb091a44-b5c0-4c6b-a693-4c48b54412fa br0 {eth0 02:00:ca:fe:00:00 [10.244.0.2/24 eth0]} {tap0 0a:58:0a:f4:00:02 []} 2 [0xc4200761b0 0xc4200761c0 0xc4200761c8 0xc4200761d0 0xc4200761d8 0xc4200761e0 0xc4200761e8 0xc4200761f0] [0xc4200761f8 0xc420076200 0xc420076208 0xc420076210 0xc420076218 0xc420076220 0xc420076228 0xc420076230]} {{{3 1450 0 eth0 0a:58:0a:f4:00:02 up|broadcast|multicast 69699 67 0 <nil>  0xc420194300 0 0xc420256380 ether <nil> up 0 0 0} veth} [10.244.0.2/24 eth0 fe80::d8f7:50ff:fe41:f5b3/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.2 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39217 source=virtcontainers
Apr 20 13:49:43 openshift-fix kata-runtime[39217]: time="2018-04-20T13:49:43.07073443Z" level=info msg="Virtual endpoint unmarshalled [{{a3646dcb-f0b6-4192-8ec5-032003d81994 br0 {eth0 02:00:ca:fe:00:00 [10.244.0.3/24 eth0]} {tap0 0a:58:0a:f4:00:03 []} 2 [0xc420076360 0xc420076368 0xc420076370 0xc420076378 0xc420076380 0xc420076388 0xc420076390 0xc420076398] [0xc4200763a0 0xc4200763a8 0xc4200763b0 0xc4200763b8 0xc4200763c0 0xc4200763c8 0xc4200763d0 0xc4200763d8]} {{{3 1450 0 eth0 0a:58:0a:f4:00:03 up|broadcast|multicast 69699 68 0 <nil>  0xc4201946c0 0 0xc420256e80 ether <nil> up 0 0 0} veth} [10.244.0.3/24 eth0 fe80::b408:87ff:fe33:9723/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39217 source=virtcontainers
Apr 20 13:49:43 openshift-fix kata-runtime[39227]: time="2018-04-20T13:49:43.084908032Z" level=debug msg="loaded configuration" command=state format=TOML name=kata-runtime pid=39227 source=runtime
Apr 20 13:49:43 openshift-fix kata-runtime[39227]: time="2018-04-20T13:49:43.085775539Z" level=info arguments="\"state c5777808b4fbb86bd9a0aed4bea6ccd7b00c6947a597ecf829c3996257e90ce3\"" command=state commit=3dd37470b0f03ed8fd65bb79a5b684a7e47e5369 name=kata-runtime pid=39227 source=runtime version=0.0.1
Apr 20 13:49:43 openshift-fix kata-runtime[39227]: time="2018-04-20T13:49:43.091386379Z" level=info msg="Virtual endpoint unmarshalled [{{eb091a44-b5c0-4c6b-a693-4c48b54412fa br0 {eth0 02:00:ca:fe:00:00 [10.244.0.2/24 eth0]} {tap0 0a:58:0a:f4:00:02 []} 2 [0xc42000e168 0xc42000e178 0xc42000e180 0xc42000e188 0xc42000e190 0xc42000e198 0xc42000e1a0 0xc42000e1a8] [0xc42000e1b0 0xc42000e1b8 0xc42000e1c0 0xc42000e1c8 0xc42000e1d0 0xc42000e1d8 0xc42000e1e0 0xc42000e1e8]} {{{3 1450 0 eth0 0a:58:0a:f4:00:02 up|broadcast|multicast 69699 67 0 <nil>  0xc420248240 0 0xc4201a3dc0 ether <nil> up 0 0 0} veth} [10.244.0.2/24 eth0 fe80::d8f7:50ff:fe41:f5b3/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.2 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39227 source=virtcontainers
Apr 20 13:49:43 openshift-fix kata-runtime[39227]: time="2018-04-20T13:49:43.094494202Z" level=info msg="Virtual endpoint unmarshalled [{{a3646dcb-f0b6-4192-8ec5-032003d81994 br0 {eth0 02:00:ca:fe:00:00 [10.244.0.3/24 eth0]} {tap0 0a:58:0a:f4:00:03 []} 2 [0xc42000e318 0xc42000e320 0xc42000e328 0xc42000e330 0xc42000e338 0xc42000e340 0xc42000e348 0xc42000e350] [0xc42000e358 0xc42000e360 0xc42000e368 0xc42000e370 0xc42000e378 0xc42000e380 0xc42000e388 0xc42000e390]} {{{3 1450 0 eth0 0a:58:0a:f4:00:03 up|broadcast|multicast 69699 68 0 <nil>  0xc420248600 0 0xc4202808c0 ether <nil> up 0 0 0} veth} [10.244.0.3/24 eth0 fe80::b408:87ff:fe33:9723/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39227 source=virtcontainers
Apr 20 13:49:43 openshift-fix kata-runtime[39239]: time="2018-04-20T13:49:43.224805748Z" level=debug msg="loaded configuration" command=delete format=TOML name=kata-runtime pid=39239 source=runtime
Apr 20 13:49:43 openshift-fix kata-runtime[39239]: time="2018-04-20T13:49:43.225250951Z" level=info arguments="\"delete --force b3177caca69e3f640d7b08e1b622fce1486429a5cddfd46b3d6bedfb2a304365\"" command=deletecommit=3dd37470b0f03ed8fd65bb79a5b684a7e47e5369 name=kata-runtime pid=39239 source=runtime version=0.0.1
Apr 20 13:49:43 openshift-fix kata-runtime[39239]: time="2018-04-20T13:49:43.229024478Z" level=info msg="Virtual endpoint unmarshalled [{{eb091a44-b5c0-4c6b-a693-4c48b54412fa br0 {eth0 02:00:ca:fe:00:00 [10.244.0.2/24 eth0]} {tap0 0a:58:0a:f4:00:02 []} 2 [0xc42007a1b0 0xc42007a1c0 0xc42007a1c8 0xc42007a1d0 0xc42007a1d8 0xc42007a1e0 0xc42007a1e8 0xc42007a1f0] [0xc42007a1f8 0xc42007a200 0xc42007a208 0xc42007a210 0xc42007a218 0xc42007a220 0xc42007a228 0xc42007a230]} {{{3 1450 0 eth0 0a:58:0a:f4:00:02 up|broadcast|multicast 69699 67 0 <nil>  0xc420190300 0 0xc420230380 ether <nil> up 0 0 0} veth} [10.244.0.2/24 eth0 fe80::d8f7:50ff:fe41:f5b3/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.2 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39239 source=virtcontainers
Apr 20 13:49:43 openshift-fix kata-runtime[39239]: time="2018-04-20T13:49:43.232375902Z" level=info msg="Virtual endpoint unmarshalled [{{a3646dcb-f0b6-4192-8ec5-032003d81994 br0 {eth0 02:00:ca:fe:00:00 [10.244.0.3/24 eth0]} {tap0 0a:58:0a:f4:00:03 []} 2 [0xc42007a360 0xc42007a368 0xc42007a370 0xc42007a378 0xc42007a380 0xc42007a388 0xc42007a390 0xc42007a398] [0xc42007a3a0 0xc42007a3a8 0xc42007a3b0 0xc42007a3b8 0xc42007a3c0 0xc42007a3c8 0xc42007a3d0 0xc42007a3d8]} {{{3 1450 0 eth0 0a:58:0a:f4:00:03 up|broadcast|multicast 69699 68 0 <nil>  0xc4201906c0 0 0xc420230e80 ether <nil> up 0 0 0} veth} [10.244.0.3/24 eth0 fe80::b408:87ff:fe33:9723/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39239 source=virtcontainers
Apr 20 13:49:43 openshift-fix kata-runtime[39239]: time="2018-04-20T13:49:43.235127722Z" level=info msg="path mounted" command=delete name=kata-runtime path=/sys/fs/cgroup/cpu pid=39239 source=runtime type=cgroup
Apr 20 13:49:43 openshift-fix kata-runtime[39239]: time="2018-04-20T13:49:43.235189523Z" level=info msg="path mounted" command=delete name=kata-runtime path=/sys/fs/cgroup/pids pid=39239 source=runtime type=cgroup
Apr 20 13:50:26 openshift-fix kata-runtime[39397]: time="2018-04-20T13:50:26.249670013Z" level=debug msg="loaded configuration" command=delete format=TOML name=kata-runtime pid=39397 source=runtime
Apr 20 13:50:26 openshift-fix kata-runtime[39397]: time="2018-04-20T13:50:26.249950015Z" level=info arguments="\"delete --force c5777808b4fbb86bd9a0aed4bea6ccd7b00c6947a597ecf829c3996257e90ce3\"" command=deletecommit=3dd37470b0f03ed8fd65bb79a5b684a7e47e5369 name=kata-runtime pid=39397 source=runtime version=0.0.1
Apr 20 13:50:26 openshift-fix kata-runtime[39397]: time="2018-04-20T13:50:26.253789943Z" level=info msg="Virtual endpoint unmarshalled [{{eb091a44-b5c0-4c6b-a693-4c48b54412fa br0 {eth0 02:00:ca:fe:00:00 [10.244.0.2/24 eth0]} {tap0 0a:58:0a:f4:00:02 []} 2 [0xc42000e1c0 0xc42000e1d0 0xc42000e1d8 0xc42000e1e0 0xc42000e1e8 0xc42000e1f0 0xc42000e1f8 0xc42000e200] [0xc42000e208 0xc42000e210 0xc42000e218 0xc42000e220 0xc42000e228 0xc42000e230 0xc42000e238 0xc42000e240]} {{{3 1450 0 eth0 0a:58:0a:f4:00:02 up|broadcast|multicast 69699 67 0 <nil>  0xc420170300 0 0xc420216380 ether <nil> up 0 0 0} veth} [10.244.0.2/24 eth0 fe80::d8f7:50ff:fe41:f5b3/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.2 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39397 source=virtcontainers
Apr 20 13:50:26 openshift-fix kata-runtime[39397]: time="2018-04-20T13:50:26.256278861Z" level=info msg="Virtual endpoint unmarshalled [{{a3646dcb-f0b6-4192-8ec5-032003d81994 br0 {eth0 02:00:ca:fe:00:00 [10.244.0.3/24 eth0]} {tap0 0a:58:0a:f4:00:03 []} 2 [0xc42000e370 0xc42000e378 0xc42000e380 0xc42000e388 0xc42000e390 0xc42000e398 0xc42000e3a0 0xc42000e3a8] [0xc42000e3b0 0xc42000e3b8 0xc42000e3c0 0xc42000e3c8 0xc42000e3d0 0xc42000e3d8 0xc42000e3e0 0xc42000e3e8]} {{{3 1450 0 eth0 0a:58:0a:f4:00:03 up|broadcast|multicast 69699 68 0 <nil>  0xc420170600 0 0xc420216c40 ether <nil> up 0 0 0} veth} [10.244.0.3/24 eth0 fe80::b408:87ff:fe33:9723/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=39397 source=virtcontainers
Apr 20 13:50:26 openshift-fix kata-runtime[39397]: time="2018-04-20T13:50:26.257210268Z" level=error msg="Sandbox not ready, paused or stopped, impossible to delete" command=delete name=kata-runtime pid=39397 source=runtime
```

**Comment by sboeuf** [comment]
Thanks @chavafg , I'll have to investigate a bit more on this one!

**Comment by sboeuf** [comment]
@chavafg @egernst FWIW, I could properly run a `kata-runtime list` after I have started `bats nginx.bats`, and it returned:
```
ID                                                                 PID         STATUS      BUNDLE                                                                                                                      CREATED                          OWNER
b158e54c68f225d6fd8e741da1ce53fa2c54e8b1b8e5a7a4b891c6e2264b9296   92575       running     /run/containers/storage/devicemapper-containers/b158e54c68f225d6fd8e741da1ce53fa2c54e8b1b8e5a7a4b891c6e2264b9296/userdata   2018-04-20T22:23:35.483591908Z   #0
d03a2966c354988fd723d0cdf75c4d68e46e1c4e123e7d3d09b9c2f8aef91f80   92702       running     /run/containers/storage/devicemapper-containers/d03a2966c354988fd723d0cdf75c4d68e46e1c4e123e7d3d09b9c2f8aef91f80/userdata   2018-04-20T22:23:43.259297608Z   #0
65366cc1b16cf4e1c25b82642b60ecef47581579be701cd29f02de3b3edb9bd2   92966       running     /run/containers/storage/devicemapper-containers/65366cc1b16cf4e1c25b82642b60ecef47581579be701cd29f02de3b3edb9bd2/userdata   2018-04-20T22:23:53.276836704Z   #0
66c57c1d34714ffbd2e1b0aeb2ae3b18c4e81342f8aff0e54d4e0f1e3186c0d3   93113       running     /run/containers/storage/devicemapper-containers/66c57c1d34714ffbd2e1b0aeb2ae3b18c4e81342f8aff0e54d4e0f1e3186c0d3/userdata   2018-04-20T22:24:00.145826271Z   #0
```

But something went wrong with `sudo -E kubeadm reset --cri-socket /var/run/crio/crio.sock`:
```
[preflight] Running pre-flight checks.
[reset] Stopping the kubelet service.
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Removing kubernetes-managed containers.
[reset] Cleaning up running containers using crictl with socket /var/run/crio/crio.sock
[reset] Failed to stop the running containers using crictl. Trying using docker instead.
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes /var/lib/etcd]
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
```

Resulting in error when running `kata-runtime list` again:
```
stat /var/lib/containers/storage/devicemapper/mnt/89e81282013b156bbb84307630b07f7d36386d5c2205eafbacb052bd6cadb28b/rootfs: no such file or directory
```

**Comment by sboeuf** [comment]
Ready to be reviewed.
@bergwolf @jodh-intel @chavafg @egernst @grahamwhaley PTAL

File: cli/delete.go [hunk 2]
```diff
@@ -77,6 +78,15 @@ func delete(containerID string, force bool) error {
 			return fmt.Errorf("Container still running, should be stopped")
 		}
 
+		// Force killing the container in case the container is still
+		// running, but don't throw an error if it failed for any
+		// reason because that's the behavior of "--force". Also, a
+		// previous call to kill might have been performed earlier,
+		// causing this one to fail.
+		if err := vci.KillContainer(sandboxID, containerID, syscall.SIGKILL, true); err != nil {
```
Comment (bergwolf) [inline cli/delete.go]: deleteContainer(forceStop==true) will also send SIGKILL to the container. Is there any reason that we need to do it here before virtcontainers does it?

Comment (bergwolf) [reply cli/delete.go]: well, deleteSandbox() also sends it. I do not see why we need it here.

Comment (sboeuf) [reply cli/delete.go]: Where are we killing the containers ?

Comment (sboeuf) [reply cli/delete.go]: Oh nevermind, I forgot this was handled through virtcontainers...

Comment (sboeuf) [reply cli/delete.go]: I have addressed your comment.

**Comment by sboeuf** [comment]
@WeiZhang555 @laijs @bergwolf PTAL

File: cli/kill.go [hunk 3]
```diff
@@ -115,7 +116,20 @@ func kill(containerID, signal string, all bool) error {
...
 	}
 
-	_, err = vci.StopContainer(sandboxID, containerID)
+	containerType, err := oci.GetContainerType(status.Annotations)
+	if err != nil {
+		return err
+	}
+
+	switch containerType {
+	case vc.PodSandbox:
```
Comment (bergwolf) [inline cli/kill.go]: @sboeuf when do crio/cri-containerd/docker-shim etc. set the podsandbox annotation? It is set for the first container created in a sandbox?

Comment (sboeuf) [reply cli/kill.go]: It is set for the container representing the sandbox, and yes it is usually the first one. In case of CRIO, they create what they call an `infra` container as being the sandbox, and then they spawn a bunch of other containers later.

File: cli/kill.go [hunk 4]
```diff
@@ -115,7 +116,20 @@ func kill(containerID, signal string, all bool) error {
...
+		_, err = vci.StopSandbox(sandboxID)
+	case vc.PodContainer:
+		_, err = vci.StopContainer(sandboxID, containerID)
+	default:
+		return fmt.Errorf("Invalid container type found")
```
Comment (jodh-intel) [inline cli/kill.go]: Can you add `containerID` to this error?

**Comment by jodh-intel** [comment]
I think the changes make, but I see them as two separate changesets, hence better as two separate commits.

Also, I am finding the description of the PR (what has this got to do with "wait"-ing?) and the commit description confusing.

**Comment by sboeuf** [comment]
@jodh-intel I can split them into 2 commits but this means the first one won't be working without the second, which should be fine since we only care about the status of the whole PR.
Now, about your comment regarding the PR description, I don't know what to add here, do you have any suggestion ?

**Comment by sboeuf** [comment]
@jodh-intel I have just split into 2 different commits, providing a separate description for `kill.go` and `delete.go` changes.

**Comment by jodh-intel** [comment]
Thanks @sboeuf! I appreciate that that's a lot of text to describe a relatively small code change, but I do think it makes the behaviour and rationale for the change much clearer.

lgtm

**Comment by jodh-intel** [comment]
@sboeuf - I'll let you remove the dnm label when you're ready.
