### PR TITLE
virtcontainers: fix unit tests

### LINKED ISSUE #192: TestContainerAddResources fails
```
--- FAIL: TestContainerAddResources (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xc87264]

goroutine 132 [running]:
testing.tRunner.func1(0xc42020e960)
	/usr/local/go/src/testing/testing.go:711 +0x5d9
panic(0xe526a0, 0x15a2340)
	/usr/local/go/src/runtime/panic.go:491 +0x2a2
github.com/kata-containers/runtime/virtcontainers.(*Container).addResources(0xc42047de58, 0x118, 0x0)
	github.com/kata-containers/runtime/virtcontainers/_test/_obj_test/container.go:935 +0x394
github.com/kata-containers/runtime/virtcontainers.TestContainerAddResources(0xc42020e960)
	/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers/container_test.go:311 +0x5a3
testing.tRunner(0xc42020e960, 0xf4e4c0)
	/usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x569
exit status 2
```

### PR DESCRIPTION
**Pull request by devimc**
Fix unit tests according with new changes introduced recently.
Use noopAgent in unit tests to add online fake resources.
Factorize configuration and hardware support for hotplugging block
devices into a single function and use that.

fixes #192

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: virtcontainers/container_test.go [hunk 1]
```diff
@@ -255,10 +261,9 @@ func TestContainerAddDriveDir(t *testing.T) {
 		t.Fatalf("Error with hotplugDrive :%v", err)
 	}
 
-	if container.state.Fstype == "" || !container.state.HotpluggedDrive {
+	if container.state.Fstype != "" && container.state.HotpluggedDrive {
```
Comment (amshinde) [inline virtcontainers/container_test.go]: So you are actually checking here that the drive is not hotplugged, which changes what the test is supposed to verify.
I think you need to add a noopAgent for the pod and have the noopAgent advertise the block support for the test.

**Comment by amshinde** [comment]
lgtm

**Comment by sboeuf** [comment]
@devimc CI not passing because of CNI unit tests.

**Comment by chavafg** [comment]
https://github.com/kata-containers/tests/pull/219 makes the CI to run the virtcontainers unit tests with root user only. But now I see a panic in the CI logs of the ubuntu 16.04 job. and an issue with the `log-parser` tool in the 17.10 job

File: virtcontainers/container.go [hunk 2]
```diff
@@ -432,6 +432,19 @@ func (c *Container) rollbackFailingContainerCreation() {
 	}
 }
 
+func (c *Container) checkBlockDeviceSupport() bool {
```
Comment (bergwolf) [inline virtcontainers/container.go]: This is part of #138, why include it here?

Comment (devimc) [reply virtcontainers/container.go]: @amshinde ^^  ?

**Comment by grahamwhaley** [comment]
For the PID log fix that was btw...

File: virtcontainers/container.go (hunk 2 above)
Comment (amshinde) [reply virtcontainers/container.go]: @bergwolf Without this factorization we need to introduce changes in the noopAgent implementation to support capabilities related to block device support since this code was moved into hotplugDrive which we are testing here. I think this is not necessary since we anyways need to factorize and reuse in #138. So I have moved it here to avoid the unnecessary implementation changes for noopAgent.

**Comment by amshinde** [comment]
@sboeuf Can we merge this one?
