### PR TITLE
virtcontainer/cgroup: create cgroup manager after creating the network

### LINKED ISSUE #2774: vfio(sriov+switchdev) device passthrough fails with “Operation not permitted”
# Description of problem

Using kata-runtime from with latest version(1.11.1), I test sriov NIC with config "sandbox_cgroup_only=true", also report error with “Operation not permitted”, and qemu vm started failed. But if I set sandbox_cgroup_only=false，there is no error, vm is started successfully.

I use k8s+containerd+kata-runtime-shimv2+qemu and network mode is switchdev+sriov. Kata-runtime consider the sriov interface in the sandbox netns as physical interface, so it use vfio to mount into the vm.

This issue is migrated from #2605 .

# Expected result
The pod  starts and has sriov device(/dev/vfio/{id}) attached.

# Actual result
The same error.
Warning FailedCreatePodSandBox 2s (x4 over 46s) kubelet, Failed create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-x86_64: -device vfio-pci,host=0000:3b:00.4,x-pci-vendor-id=0x15b3,x-pci-device-id=0x1018,romfile=: vfio error: 0000:3b:00.4: failed to open /dev/vfio/84: Operation not permitted

The log belows:
Jun 12 11:14:40 kata[1850343]: time="2020-06-12T11:14:40.767948982+08:00" level=info msg="loaded configuration" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 file=/data/kata/share/defaults/kata-containers/configuration-qemu.toml format=TOML source=katautils Jun 12 11:14:40 kata[1850343]: time="2020-06-12T11:14:40.768039539+08:00" level=debug ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 default-kernel-parameters="systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket" source=katautils Jun 12 11:14:40 kata[1850343]: time="2020-06-12T11:14:40.768465049+08:00" level=debug msg="container rootfs: /root/tce/containerd/run/daemon/io.containerd.runtime.v2.task/k8s.io/3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074/rootfs" source=virtcontainers subsystem=oci Jun 12 11:14:40 kata[1850343]: time="2020-06-12T11:14:40.770638839+08:00" level=debug msg="restore sandbox failed" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 error="open /run/vc/sbs/3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074/persist.json: no such file or directory" sandbox=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 source=virtcontainers subsystem=sandbox Jun 12 11:14:40 kata[1850343]: time="2020-06-12T11:14:40.770685291+08:00" level=debug msg="Creating bridges" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 source=virtcontainers subsystem=qemu Jun 12 11:14:40 kata[1850343]: time="2020-06-12T11:14:40.77070504+08:00" level=debug msg="Creating UUID" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 source=virtcontainers subsystem=qemu Jun 12 11:14:40 kata[1850343]: time="2020-06-12T11:14:40.771238099+08:00" level=debug msg="Disable nesting environment checks" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 inside-vm=false source=virtcontainers subsystem=qemu Jun 12 11:14:40 kata[1850343]: time="2020-06-12T11:14:40.771565033+08:00" level=info msg="adding volume" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 source=virtcontainers subsystem=qemu volume-type=virtio-9p Jun 12 11:14:40 kata[1850343]: time="2020-06-12T11:14:40.772286581+08:00" level=info msg="Physical network interface found" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 interface=eth0 source=virtcontainers subsystem=network Jun 12 11:14:40 kata[1850343]: time="2020-06-12T11:14:40.772815577+08:00" level=info msg="Endpoints found after scan" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 endpoints="[0xc0000f2a00]" source=virtcontainers subsystem=network Jun 12 11:14:40 kata[1850343]: time="2020-06-12T11:14:40.7728695+08:00" level=info msg="Attaching endpoint" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 endpoint-type=physical hotplug=false source=virtcontainers subsystem=network Jun 12 11:14:40 kata[1850343]: time="2020-06-12T11:14:40.772894941+08:00" level=info msg="Unbinding device from driver" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 device-bdf="0000:3b:00.3" driver-path="/sys/bus/pci/devices/0000:3b:00.3/driver/unbind" source=virtcontainers subsystem=device Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.3118116+08:00" level=info msg="Writing vendor-device-id to vfio new-id path" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 source=virtcontainers subsystem=device vendor-device-id="0x15b3 0x1018" vfio-new-id-path=/sys/bus/pci/drivers/vfio-pci/new_id Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.312110237+08:00" level=info msg="Binding device to vfio driver" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 device-bdf="0000:3b:00.3" driver-path=/sys/bus/pci/drivers/vfio-pci/bind source=virtcontainers subsystem=device Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.312243935+08:00" level=debug msg="Network added" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 source=virtcontainers subsystem=network Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.334822937+08:00" level=info msg="Starting VM" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 sandbox=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 source=virtcontainers subsystem=sandbox Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.334915029+08:00" level=debug ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 default-kernel-parameters="tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug" source=virtcontainers subsystem=qemu Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.335072446+08:00" level=info msg="launching /data/kata/bin/qemu-system-x86_64 with: [-name sandbox-3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 -uuid 767679a8-99d6-4e64-877c-3fa806398490 -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host -qmp unix:/run/vc/vm/3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=386179M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/data/kata/share/kata-containers/kata-containers.img,size=402653184 -device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,romfile= -device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 -chardev socket,id=charch0,path=/run/vc/vm/3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074/kata.sock,server,nowait -device virtio-9p-pci,disable-modern=false,fsdev=extra-9p-kataShared,mount_tag=kataShared,romfile= -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes/3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074/shared,security_model=none -device vfio-pci,host=0000:3b:00.3,x-pci-vendor-id=0x15b3,x-pci-device-id=0x1018,romfile= -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -object memory-backend-ram,id=dimm1,size=2048M -numa node,memdev=dimm1 -kernel /data/kata/share/kata-containers/vmlinuz-4.19.86-60 -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug panic=1 nr_cpus=96 agent.use_vsock=false systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none rw -pidfile /run/vc/vm/3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074/pid -D /run/vc/vm/3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074/qemu.log -smp 1,cores=1,threads=1,sockets=96,maxcpus=96]" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 source=virtcontainers subsystem=qmp Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.370674027+08:00" level=error msg="Unable to launch /data/kata/bin/qemu-system-x86_64: exit status 1" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 source=virtcontainers subsystem=qmp Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.370727817+08:00" level=error ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 source=virtcontainers subsystem=qmp Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.370769312+08:00" level=error msg="failed to launch qemu: qemu-system-x86_64: -device vfio-pci,host=0000:3b:00.3,x-pci-vendor-id=0x15b3,x-pci-device-id=0x1018,romfile=: vfio error: 0000:3b:00.3: failed to open /dev/vfio/83: Operation not permitted\n" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 error="exit status 1" source=virtcontainers subsystem=qemu Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.370873008+08:00" level=info msg="Detaching endpoint" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 endpoint-type=physical source=virtcontainers subsystem=network Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.370898209+08:00" level=info msg="Unbinding device from driver" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 device-bdf="0000:3b:00.3" driver-path="/sys/bus/pci/devices/0000:3b:00.3/driver/unbind" source=virtcontainers subsystem=device Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.371167118+08:00" level=info msg="Binding back device to host driver" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 device-bdf="0000:3b:00.3" driver-path=/sys/bus/pci/drivers/mlx5_core/bind source=virtcontainers subsystem=device Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.765714726+08:00" level=debug msg="Network removed" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 source=virtcontainers subsystem=network Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.765764816+08:00" level=debug msg="Deleting sandbox cgroup" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 sandbox=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 source=virtcontainers subsystem=sandbox Jun 12 11:14:41 kata[1850343]: time="2020-06-12T11:14:41.7858325+08:00" level=info msg="cleanup agent" ID=3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074 path=/run/kata-containers/shared/sandboxes/3656ccc016ed2c4efca0795472f14e055c89be54fd8ef260e9c29d52576fc074/shared source=virtcontainers subsystem=kata_agent

### PR DESCRIPTION
**Pull request by devimc**
Create the cgroup manager once the network has been created, this way the
list of device will include the network VFIO devices attached to the sandbox,
when the physical enpoint is the network driver.

fixes #2774

Signed-off-by: Julio Montes <julio.montes@intel.com>

 @yadzhang please take a look

### CODE REVIEW

**Comment by yadzhang** [comment]
I took a test with this pr and add some log for sandbox `AddDevice` func.

```
	var err error
	b, err := s.devManager.NewDevice(info)
	if err != nil {
		s.Logger().Errorf("add device error failed %+v", err)
		return nil, err
	}
	s.Logger().Infof("add device333 %+v", info)
	defer func() {
		if err != nil {
			s.Logger().Errorf("Add device failed %+v", err)

			s.devManager.RemoveDevice(b.DeviceID())
		}
	}()

```

 And it reports errors `Empty path provided for device`  when call `s.devManager.NewDevice(info)` to createDevice. detail logs are belows:

`
Jun 16 17:03:37 docker-containerd[3296]: time="2020-06-16T17:03:37.942705111+08:00" level=info msg="Writing vendor-device-id to vfio new-id path" ID=3e7605d1ba58f78a771bd6355989bc4111355fc898bce5364cbafea72952e9d1 source=virtcontainers subsystem=device vendor-device-id="0x15b3 0x1018" vfio-new-id-path=/sys/bus/pci/drivers/vfio-pci/new_id
Jun 16 17:03:37 docker-containerd[3296]: time="2020-06-16T17:03:37.942959222+08:00" level=info msg="Binding device to vfio driver" ID=3e7605d1ba58f78a771bd6355989bc4111355fc898bce5364cbafea72952e9d1 device-bdf="0000:3b:00.4" driver-path=/sys/bus/pci/drivers/vfio-pci/bind source=virtcontainers subsystem=device
Jun 16 17:03:37 kata[61853]: time="2020-06-16T17:03:37.942959222+08:00" level=info msg="Binding device to vfio driver" ID=3e7605d1ba58f78a771bd6355989bc4111355fc898bce5364cbafea72952e9d1 device-bdf="0000:3b:00.4" driver-path=/sys/bus/pci/drivers/vfio-pci/bind source=virtcontainers subsystem=device
Jun 16 17:03:37 docker-containerd[3296]: time="2020-06-16T17:03:37.943079464+08:00" level=info msg="add device 111 {HostPath:/dev/vfio/84 ContainerPath: DevType:c Major:246 Minor:3 Pmem:false ColdPlug:true FileMode:---------- UID:0 GID:0 ID: DriverOptions:map[]}" ID=3e7605d1ba58f78a771bd6355989bc4111355fc898bce5364cbafea72952e9d1 sandbox=3e7605d1ba58f78a771bd6355989bc4111355fc898bce5364cbafea72952e9d1 source=virtcontainers subsystem=sandbox
Jun 16 17:03:37 docker-containerd[3296]: time="2020-06-16T17:03:37.943106137+08:00" level=info msg="add device222 {HostPath:/dev/vfio/84 ContainerPath: DevType:c Major:246 Minor:3 Pmem:false ColdPlug:true FileMode:---------- UID:0 GID:0 ID: DriverOptions:map[]}" ID=3e7605d1ba58f78a771bd6355989bc4111355fc898bce5364cbafea72952e9d1 sandbox=3e7605d1ba58f78a771bd6355989bc4111355fc898bce5364cbafea72952e9d1 source=virtcontainers subsystem=sandbox
Jun 16 17:03:37 docker-containerd[3296]: time="2020-06-16T17:03:37.943128127+08:00" level=error msg="add device error failed Empty path provided for device" ID=3e7605d1ba58f78a771bd6355989bc4111355fc898bce5364cbafea72952e9d1 sandbox=3e7605d1ba58f78a771bd6355989bc4111355fc898bce5364cbafea72952e9d1 source=virtcontainers subsystem=sandbox
Jun 16 17:03:37 docker-containerd[3296]: time="2020-06-16T17:03:37.943152522+08:00" level=debug msg="Deleting sandbox cgroup" ID=3e7605d1ba58f78a771bd6355989bc4111355fc898bce5364cbafea72952e9d1 sandbox=3e7605d1ba58f78a771bd6355989bc4111355fc898bce5364cbafea72952e9d1 source=virtcontainers subsystem=sandbox
`

**Comment by devimc** [comment]
@yadzhang fixed, please try again

**Comment by yadzhang** [comment]
> @yadzhang fixed, please try again

another two errors report:
1. `can not find slot for bdf of pci device`
2. `updateInterface: rpc error: code = NotFound desc = Could not find the link corresponding to HwAddr \"e0:e0:aa:01:0e:0e\"`

detail logs belows:

`
Jun 16 21:46:03 kata[45866]: time="2020-06-16T21:46:03.357528095+08:00" level=info msg="Physical network interface found" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 interface=eth0 source=virtcontainers subsystem=network
Jun 16 21:46:03 kata[45866]: time="2020-06-16T21:46:03.357843451+08:00" level=info msg="Endpoints found after scan" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 endpoints="[0xc0000cf200]" source=virtcontainers subsystem=network
Jun 16 21:46:03 kata[45866]: time="2020-06-16T21:46:03.357897181+08:00" level=info msg="Attaching endpoint" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 endpoint-type=physical hotplug=false source=virtcontainers subsystem=network
Jun 16 21:46:03 kata[45866]: time="2020-06-16T21:46:03.357920546+08:00" level=info msg="Unbinding device from driver" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 device-bdf="0000:3b:00.3" driver-path="/sys/bus/pci/devices/0000:3b:00.3/driver/unbind" source=virtcontainers subsystem=device
Jun 16 21:46:03 kata[45866]: time="2020-06-16T21:46:03.789674923+08:00" level=info msg="Writing vendor-device-id to vfio new-id path" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 source=virtcontainers subsystem=device vendor-device-id="0x15b3 0x1018" vfio-new-id-path=/sys/bus/pci/drivers/vfio-pci/new_id
Jun 16 21:46:03 kata[45866]: time="2020-06-16T21:46:03.789954788+08:00" level=info msg="Binding device to vfio driver" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 device-bdf="0000:3b:00.3" driver-path=/sys/bus/pci/drivers/vfio-pci/bind source=virtcontainers subsystem=device
Jun 16 21:46:03 kata[45866]: time="2020-06-16T21:46:03.791151713+08:00" level=debug msg="can not find slot for bdf of pci device" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 dev-bdf="0000:3b:00.3" source=virtcontainers subsystem=device
Jun 16 21:46:03 kata[45866]: time="2020-06-16T21:46:03.791230856+08:00" level=info msg="Device group attached" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 device-group=/dev/vfio/83 device-type=vfio-passthrough source=virtcontainers subsystem=device
Jun 16 21:46:03 kata[45866]: time="2020-06-16T21:46:03.791277268+08:00" level=debug msg="Network added" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 source=virtcontainers subsystem=network
Jun 16 21:46:03 kata[45866]: time="2020-06-16T21:46:03.807154104+08:00" level=info msg="Starting VM" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 sandbox=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 source=virtcontainers subsystem=sandbox
Jun 16 21:46:03 kata[45866]: time="2020-06-16T21:46:03.807227322+08:00" level=debug ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 default-kernel-parameters="tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug" source=virtcontainers subsystem=qemu


Jun 16 21:46:05 kata[45866]: time="2020-06-16T21:46:05.869890994+08:00" level=debug msg="sending request" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 name=grpc.UpdateInterfaceRequest req="interface:<device:\"eth0\" name:\"eth0\" IPAddresses:<address:\"11.0.11.2\" mask:\"32\" > IPAddresses:<family:v6 address:\"fdbd:1111::2\" mask:\"128\" > mtu:1450 hwAddr:\"e0:e0:aa:01:0e:0e\" > " source=virtcontainers subsystem=kata_agent
Jun 16 21:46:05 kata[45866]: time="2020-06-16T21:46:05.870561682+08:00" level=debug msg="reading guest console" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 sandbox=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 source=virtcontainers subsystem=kata_agent vmconsole="time=\"2020-06-16T13:46:05.857143508Z\" level=info msg=\"Getting interface from MAC address\" debug_console=false interface-name=eth0 mac-address=\"e0:e0:aa:01:0e:0e\" name=kata-agent pci-address= pid=95 source=agent"
Jun 16 21:46:05 kata[45866]: time="2020-06-16T21:46:05.870931235+08:00" level=error msg="update interface request failed" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 error="rpc error: code = Internal desc = updateInterface: rpc error: code = NotFound desc = Could not find the link corresponding to HwAddr \"e0:e0:aa:01:0e:0e\"" interface-requested="&{Device:eth0 Name:eth0 IPAddresses:[0xc0003f2a80 0xc0003f2ab0] Mtu:1450 RawFlags:0 HwAddr:e0:e0:aa:01:0e:0e PciAddr: LinkType:}" resulting-interface="<nil>" source=virtcontainers subsystem=kata_agent
`

my qemu-img start args:

`
qemu-system-x86_64 with: [-name sandbox-fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 -uuid 5047bba2-6fb0-4ec9-82fd-c51f54b6f228 -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host -qmp unix:/run/vc/vm/fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=386179M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/data00/tiger/tce/kata/share/kata-containers/kata-containers.img,size=402653184 -device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,romfile= -device vhost-vsock-pci,disable-modern=false,vhostfd=3,id=vsock-2513586045,guest-cid=2513586045,romfile= -device virtio-9p-pci,disable-modern=false,fsdev=extra-9p-kataShared,mount_tag=kataShared,romfile= -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes/fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075/shared,security_model=none -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -object memory-backend-ram,id=dimm1,size=2048M -numa node,memdev=dimm1 -kernel /data00/tiger/tce/kata/share/kata-containers/vmlinuz-4.19.86-60 -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug panic=1 nr_cpus=96 agent.use_vsock=true systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none rw -pidfile /run/vc/vm/fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075/pid -D /run/vc/vm/fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075/qemu.log -smp 1,cores=1,threads=1,sockets=96,maxcpus=96]" ID=fc4df3cd434737aca5679a12fdba4908c311617df28b80ae4b5f7347998c0075 source=virtcontainers subsystem=qmp
`

**Comment by devimc** [comment]
@yadzhang fixed, and thanks for testing this, I really appreciate it :+1: 

/test-vfio

**Comment by yadzhang** [comment]
🤝 Thanks for fixing, too.
If the pod was not set resource limit(cpu and memory), the kata container could running successfully and sriov was configured correct. 
But if I specify pod resource limit, qemu process will be killed by OOM.

1. qemu-img launching log with no resource limit(success):
`
"launching /data00/tiger/tce/kata/bin/qemu-system-x86_64 with: [-name sandbox-04711e6d46a6a876a5a64c165f640e063773a03990328e190500574c9392b787 -uuid 520ff07e-0671-43ca-a6d6-031cf2168de7 -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host -qmp unix:/run/vc/vm/04711e6d46a6a876a5a64c165f640e063773a03990328e190500574c9392b787/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=386179M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/04711e6d46a6a876a5a64c165f640e063773a03990328e190500574c9392b787/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/data00/tiger/tce/kata/share/kata-containers/kata-containers.img,size=402653184 -device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,romfile= -device vhost-vsock-pci,disable-modern=false,vhostfd=3,id=vsock-1571542733,guest-cid=1571542733,romfile= -device virtio-9p-pci,disable-modern=false,fsdev=extra-9p-kataShared,mount_tag=kataShared,romfile= -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes/04711e6d46a6a876a5a64c165f640e063773a03990328e190500574c9392b787/shared,security_model=none -device vfio-pci,host=3b:00.2,romfile= -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -object memory-backend-ram,id=dimm1,size=2048M -numa node,memdev=dimm1 -kernel /data00/tiger/tce/kata/share/kata-containers/vmlinuz-4.19.86-60 -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug panic=1 nr_cpus=96 agent.use_vsock=true systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none rw -pidfile /run/vc/vm/04711e6d46a6a876a5a64c165f640e063773a03990328e190500574c9392b787/pid -D /run/vc/vm/04711e6d46a6a876a5a64c165f640e063773a03990328e190500574c9392b787/qemu.log -smp 1,cores=1,threads=1,sockets=96,maxcpus=96]" ID=04711e6d46a6a876a5a64c165f640e063773a03990328e190500574c9392b787 source=virtcontainers subsystem=qmp
`

2. pod with resource limit: 1C1G (OOM when lauching vm)

- kubelet pod event:
`
 Failed create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to launch qemu: exit status 1, error messages from qemu log: : unknown
`

- qemu-img launching log :
`
Jun 17 10:37:22  kata[1849461]: time="2020-06-17T10:37:22.755468479+08:00" level=info msg="Adding extra file [0xc0004949d0]"  source=virtcontainers subsystem=qmp
Jun 17 10:37:22  kata[1849461]: time="2020-06-17T10:37:22.755521617+08:00" level=info msg="launching /data00/tiger/tce/kata/bin/qemu-system-x86_64 with: [-name sandbox-fa0b7d3d96479b5e679868df1d24e695a55a325264935932988f02bfd07ca2e1 -uuid 03224092-e352-4097-92d6-7e547896f445 -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host -qmp unix:/run/vc/vm/fa0b7d3d96479b5e679868df1d24e695a55a325264935932988f02bfd07ca2e1/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=386179M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/fa0b7d3d96479b5e679868df1d24e695a55a325264935932988f02bfd07ca2e1/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/data00/tiger/tce/kata/share/kata-containers/kata-containers.img,size=402653184 -device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,romfile= -device vhost-vsock-pci,disable-modern=false,vhostfd=3,id=vsock-3337070505,guest-cid=3337070505,romfile= -device virtio-9p-pci,disable-modern=false,fsdev=extra-9p-kataShared,mount_tag=kataShared,romfile= -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes/fa0b7d3d96479b5e679868df1d24e695a55a325264935932988f02bfd07ca2e1/shared,security_model=none -device vfio-pci,host=3b:00.5,romfile= -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -object memory-backend-ram,id=dimm1,size=2048M -numa node,memdev=dimm1 -kernel /data00/tiger/tce/kata/share/kata-containers/vmlinuz-4.19.86-60 -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug panic=1 nr_cpus=96 agent.use_vsock=true systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none rw -pidfile /run/vc/vm/fa0b7d3d96479b5e679868df1d24e695a55a325264935932988f02bfd07ca2e1/pid -D /run/vc/vm/fa0b7d3d96479b5e679868df1d24e695a55a325264935932988f02bfd07ca2e1/qemu.log -smp 1,cores=1,threads=1,sockets=96,maxcpus=96]"  source=virtcontainers subsystem=qmp
Jun 17 10:37:23  kata[1849461]: time="2020-06-17T10:37:23.022083171+08:00" level=error msg="Unable to launch /data00/tiger/tce/kata/bin/qemu-system-x86_64: exit status 1"  source=virtcontainers subsystem=qmp
Jun 17 10:37:23  kata[1849461]: time="2020-06-17T10:37:23.022126778+08:00" level=error  source=virtcontainers subsystem=qmp
Jun 17 10:37:23  kata[1849461]: time="2020-06-17T10:37:23.022163597+08:00" level=error msg="failed to launch qemu: "  error="exit status 1" source=virtcontainers subsystem=qemu
Jun 17 10:37:23  kata[1849461]: time="2020-06-17T10:37:23.03166635+08:00" level=info msg="Detaching endpoint"  endpoint-type=physical source=virtcontainers subsystem=network
Jun 17 10:37:23  kata[1849461]: time="2020-06-17T10:37:23.031701915+08:00" level=info msg="Unbinding device from driver"  device-bdf="0000:3b:00.5" driver-path="/sys/bus/pci/devices/0000:3b:00.5/driver/unbind" source=virtcontainers subsystem=device
Jun 17 10:37:23  kata[1849461]: time="2020-06-17T10:37:23.031930855+08:00" level=info msg="Binding back device to host driver"  device-bdf="0000:3b:00.5" driver-path=/sys/bus/pci/drivers/mlx5_core/bind source=virtcontainers subsystem=device
Jun 17 10:37:23  kata[1849461]: time="2020-06-17T10:37:23.424253237+08:00" level=debug msg="Network removed"  source=virtcontainers subsystem=network
Jun 17 10:37:23  kata[1849461]: time="2020-06-17T10:37:23.424290244+08:00" level=debug msg="Deleting sandbox cgroup"  sandbox=fa0b7d3d96479b5e679868df1d24e695a55a325264935932988f02bfd07ca2e1 source=virtcontainers subsystem=sandbox
Jun 17 10:37:23  kata[1849461]: time="2020-06-17T10:37:23.444075268+08:00" level=info msg="cleanup agent"  path=/run/kata-containers/shared/sandboxes/fa0b7d3d96479b5e679868df1d24e695a55a325264935932988f02bfd07ca2e1/shared source=virtcontainers subsystem=kata_agent

`

- dmesg oom log:

[Wed Jun 17 10:37:10 2020] memory: usage 1048576kB, limit 1048576kB, failcnt 153
[Wed Jun 17 10:37:10 2020] memory+swap: usage 1048576kB, limit 9007199254740988kB, failcnt 0
[Wed Jun 17 10:37:10 2020] kmem: usage 10568kB, limit 9007199254740988kB, failcnt 0
[Wed Jun 17 10:37:10 2020] Memory cgroup stats for /kubepods/pod200f55f9-b043-11ea-b578-fa163e82605e:
[Wed Jun 17 10:37:10 2020] anon 1062739968
                           file 0
                           kernel_stack 0
                           slab 2801664
                           sock 0
                           shmem 0
                           file_mapped 0
                           file_dirty 0
                           file_writeback 0
                           anon_thp 1040187392
                           inactive_anon 0
                           active_anon 1062469632
                           inactive_file 0
                           active_file 0
                           unevictable 0
                           slab_reclaimable 847872
                           slab_unreclaimable 1953792
                           pgfault 25609
                           pgmajfault 0
                           workingset_refault 0
                           workingset_activate 0
                           workingset_nodereclaim 0
                           pgrefill 0
                           pgscan 0
                           pgsteal 0
                           pgactivate 0
                           pgdeactivate 0
                           pglazyfree 0
                           pglazyfreed 0
                           thp_fault_alloc 1983
                           thp_collapse_alloc 0
[Wed Jun 17 10:37:10 2020] Tasks state (memory values in pages):
[Wed Jun 17 10:37:10 2020] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[Wed Jun 17 10:37:10 2020] [1848842]     0 1848842   248449     5100   204800        0          -500 containerd-shim
[Wed Jun 17 10:37:10 2020] [1848858]     0 1848858     6374     1865    69632        0          -500 qemu-system-x86
[Wed Jun 17 10:37:10 2020] [1848862]     0 1848862   655255   260868  2199552        0          -500 qemu-system-x86
[Wed Jun 17 10:37:10 2020] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=kata_49c2ae835b9fcfe1ac0794344727c25642f6a84adea8da6a0bb8d5a81d5767f0,mems_allowed=0-1,oom_memcg=/kubepods/pod200f55f9-b043-11ea-b578-fa163e82605e,task_memcg=/kubepods/pod200f55f9-b043-11ea-b578-fa163e82605e/kata_49c2ae835b9fcfe1ac0794344727c25642f6a84adea8da6a0bb8d5a81d5767f0,task=qemu-system-x86,pid=1848862,uid=0
[Wed Jun 17 10:37:10 2020] Memory cgroup out of memory: Killed process 1848862 (qemu-system-x86) total-vm:2621020kB, anon-rss:1037584kB, file-rss:6088kB, shmem-rss:4kB, UID:0 pgtables:2148kB oom_score_adj:-500
[Wed Jun 17 10:37:10 2020] oom_reaper: reaped process 1848862 (qemu-system-x86), now anon-rss:0kB, file-rss:4kB, shmem-rss:4kB
[Wed Jun 17 10:37:10 2020] mlx5_core 0000:3b:00.5: enabling device (0000 -> 0002)
[Wed Jun 17 10:37:10 2020] mlx5_core 0000:3b:00.5: firmware version: 16.27.2008
[Wed Jun 17 10:37:10 2020] mlx5_core 0000:3b:00.5: Rate limit: 127 rates are supported, range: 0Mbps to 24414Mbps
[Wed Jun 17 10:37:10 2020] mlx5_core 0000:3b:00.5: MLX5E: StrdRq(1) RqSz(8) StrdSz(2048) RxCqeCmprss(0)
[Wed Jun 17 10:37:10 2020] mlx5_core 0000:3b:00.5 enp59s0f5: renamed from eth4
[Wed Jun 17 10:37:21 2020] mlx5_core 0000:3b:00.5 eth0: renamed from enp59s0f5



3. pod with resource limit: 1C4G (OOM when hotplug memory):

- kubelet pod event:
`
  Warning  Failed          5s               kubelet,  Error: failed to create containerd task: exitting QMP loop, command cancelled: unknown
  Normal   Pulled          4s (x2 over 6s)  kubelet,  Container image "dockerhub.faastobsy.com/busybox:1.31.1" already present on machine
  Normal   Created         4s (x2 over 6s)  kubelet, Created container busybox
  Warning  Failed          4s               kubelet,  Error: failed to create containerd task: Dead agent: unknown
  Normal   SandboxChanged  3s               kubelet,  Pod sandbox changed, it will be killed and re-created.
`

- qemu lauching log:
`
"launching qemu-system-x86_64 with: [-name sandbox- -uuid cef665db-dacf-42f0-a74a-8fcd250c64ec -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host -qmp unix:/run/vc/vm//qmp.sock,server,nowait -m 2048M,slots=10,maxmem=386179M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm//console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/data00/tiger/tce/kata/share/kata-containers/kata-containers.img,size=402653184 -device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,romfile= -device vhost-vsock-pci,disable-modern=false,vhostfd=3,id=vsock-2757507435,guest-cid=2757507435,romfile= -device virtio-9p-pci,disable-modern=false,fsdev=extra-9p-kataShared,mount_tag=kataShared,romfile= -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes//shared,security_model=none -device vfio-pci,host=3b:00.3,romfile= -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -object memory-backend-ram,id=dimm1,size=2048M -numa node,memdev=dimm1 -kernel /data00/tiger/tce/kata/share/kata-containers/vmlinuz-4.19.86-60 -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug panic=1 nr_cpus=96 agent.use_vsock=true systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none rw -pidfile /run/vc/vm//pid -D /run/vc/vm//qemu.log -smp 1,cores=1,threads=1,sockets=96,maxcpus=96]



Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.186617203+08:00" level=debug msg="Sandbox CPUs: 2" ID= sandbox= source=virtcontainers subsystem=sandbox
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.18664789+08:00" level=debug msg="Request to hypervisor to update memory" ID= memory-sandbox-size-byte=6442450944 sandbox= source=virtcontainers subsystem=sandbox
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.186681573+08:00" level=debug msg="requested memory hotplug" ID= hotplug=memory hotplug-memory-mb=4096 source=virtcontainers subsystem=qemu
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.186703152+08:00" level=debug msg="Requested to add memory: 4096 MB" ID= hotplug=memory operation=add source=virtcontainers subsystem=qemu
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.186785821+08:00" level=info msg="{\"execute\":\"query-memory-devices\"}" ID= source=virtcontainers subsystem=qmp
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.186921388+08:00" level=debug msg="reading guest console" ID= sandbox= source=virtcontainers subsystem=kata_agent vmconsole="[  302.902643] x86: Booting SMP configuration:"
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.186974252+08:00" level=debug msg="reading guest console" ID= sandbox= source=virtcontainers subsystem=kata_agent vmconsole="[  302.902691] smpboot: Booting Node 0 Processor 1 APIC 0x5f"
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.187905651+08:00" level=info msg="{\"return\": [{\"type\": \"dimm\", \"data\": {\"memdev\": \"/objects/mem0\", \"hotplugged\": false, \"addr\": 4294967296, \"hotpluggable\": true, \"size\": 402653184, \"slot\": 0, \"node\": 0, \"id\": \"nv0\"}}]}" ID= source=virtcontainers subsystem=qmp
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.188044706+08:00" level=info msg="{\"arguments\":{\"id\":\"mem1\",\"props\":{\"size\":4294967296},\"qom-type\":\"memory-backend-ram\"},\"execute\":\"object-add\"}" ID= source=virtcontainers subsystem=qmp
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.188209068+08:00" level=debug msg="reading guest console" ID= sandbox= source=virtcontainers subsystem=kata_agent vmconsole="[  302.902842] kvm-clock: cpu 1, msr 26df041, secondary cpu clock"
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.188301792+08:00" level=debug msg="reading guest console" ID= sandbox= source=virtcontainers subsystem=kata_agent vmconsole="[  302.902970] x86/cpu: Activated the Intel User Mode Instruction Prevention (UMIP) CPU feature"
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.188374406+08:00" level=debug msg="reading guest console" ID= sandbox= source=virtcontainers subsystem=kata_agent vmconsole="[  302.903059] smpboot: CPU 1 Converting physical 95 to logical package 1"
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.18840945+08:00" level=debug msg="reading guest console" ID= sandbox= source=virtcontainers subsystem=kata_agent vmconsole="[  302.903723] KVM setup async PF for cpu 1"
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.18847503+08:00" level=debug msg="reading guest console" ID= sandbox= source=virtcontainers subsystem=kata_agent vmconsole="[  302.904054] kvm-stealtime: cpu 1, msr 7c454ec0"
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.188646486+08:00" level=debug msg="reading guest console" ID= sandbox= source=virtcontainers subsystem=kata_agent vmconsole="time=\"2020-06-17T03:03:14.172191561Z\" level=info msg=\"Received add uevent\" debug_console=false name=kata-agent pid=102 source=agent subsystem=udevlistener uevent-action=add uevent-devname=cpu/1/msr uevent-devpath=/devices/virtual/msr/msr1 uevent-seqnum=1050 uevent-subsystem=msr"
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.188778947+08:00" level=debug msg="reading guest console" ID= sandbox= source=virtcontainers subsystem=kata_agent vmconsole="[  302.904338] Will online and itime=\"2020-06-17T03:03:14.172307868Z\" level=info msg=\"Received add uevent\" debug_console=false name=kata-agent pid=102 source=agent subsystem=udevlistener uevent-action=add uevent-devname=cpu/1/cpuid uevent-devpath=/devices/virtual/cpuid/cpu1 uevent-seqnum=1051 uevent-subsystem=cpuidnit hotplugged C"
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.188814851+08:00" level=debug msg="reading guest console" ID= sandbox= source=virtcontainers subsystem=kata_agent vmconsole="PU: 1"
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.188945781+08:00" level=debug msg="reading guest console" ID= sandbox= source=virtcontainers subsystem=kata_agent vmconsole="time=\"2020-06-17T03:03:14.172464597Z\" level=info msg=\"Received add uevent\" debug_console=false name=kata-agent pid=102 source=agent subsystem=udevlistener uevent-action=add uevent-devname= uevent-devpath=/devices/virtual/thermal/cooling_device1 uevent-seqnum=1052 uevent-subsystem=thermal"
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.189488124+08:00" level=info msg="{\"return\": {}}" ID= source=virtcontainers subsystem=qmp
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.189530715+08:00" level=info msg="{\"arguments\":{\"driver\":\"pc-dimm\",\"id\":\"dimmmem1\",\"memdev\":\"mem1\"},\"execute\":\"device_add\"}" ID= source=virtcontainers subsystem=qmp
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.564956193+08:00" level=info msg="sanner return error: read unix @->/run/vc/vm//qmp.sock: read: connection reset by peer" ID= source=virtcontainers subsystem=qmp
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.565054125+08:00" level=info msg="mark agent dead" ID= source=virtcontainers subsystem=kata_agent
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.565066775+08:00" level=error msg="Unable to add memory device mem1: exitting QMP loop, command cancelled" ID= source=virtcontainers subsystem=qmp
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.565179272+08:00" level=warning msg="Unable to clean up memory object mem1: exitting QMP loop, command cancelled" ID= source=virtcontainers subsystem=qmp
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.565207438+08:00" level=error msg="hotplug memory" ID= error="exitting QMP loop, command cancelled" source=virtcontainers subsystem=qemu
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.565123884+08:00" level=info msg="mark agent dead" ID= source=virtcontainers subsystem=kata_agent
Jun 17 11:03:14  kata[1884629]: time="2020-06-17T11:03:14.565181801+08:00" level=error msg="Wait for process failed" container= error="rpc error: code = Unavailable desc = transport is closing" pid=
J

`

- dmesg oom log 

[Wed Jun 17 11:03:13 2020] memory: usage 4194304kB, limit 4194304kB, failcnt 210
[Wed Jun 17 11:03:13 2020] memory+swap: usage 4194304kB, limit 9007199254740988kB, failcnt 0
[Wed Jun 17 11:03:13 2020] kmem: usage 46084kB, limit 9007199254740988kB, failcnt 0
[Wed Jun 17 11:03:13 2020] Memory cgroup stats for /kubepods/pod4f0d402b-b045-11ea-b578-fa163e82605e:
[Wed Jun 17 11:03:13 2020] anon 4242911232
                           file 229376
                           kernel_stack 1327104
                           slab 23441408
                           sock 0
                           shmem 0
                           file_mapped 0
                           file_dirty 135168
                           file_writeback 0
                           anon_thp 3800039424
                           inactive_anon 0
                           active_anon 4247564288
                           inactive_file 0
                           active_file 0
                           unevictable 0
                           slab_reclaimable 13037568
                           slab_unreclaimable 10403840
                           pgfault 907533
                           pgmajfault 0
                           workingset_refault 0
                           workingset_activate 0
                           workingset_nodereclaim 0
                           pgrefill 135
                           pgscan 329
                           pgsteal 113
                           pgactivate 66
                           pgdeactivate 135
                           pglazyfree 627
                           pglazyfreed 99
                           thp_fault_alloc 12606
                           thp_collapse_alloc 0
[Wed Jun 17 11:03:13 2020] Tasks state (memory values in pages):
[Wed Jun 17 11:03:13 2020] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[Wed Jun 17 11:03:13 2020] [1884629]     0 1884629   232065     5640   200704        0          -500 containerd-shim
[Wed Jun 17 11:03:13 2020] [1884648]     0 1884648  1774713  1038431  8577024        0          -500 qemu-system-x86
[Wed Jun 17 11:03:13 2020] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=kata_2b0e7d5c46727f885d1cf37ad45e5d39c4ad24822347ac51a483139eb2cad313,mems_allowed=0-1,oom_memcg=/kubepods/pod4f0d402b-b045-11ea-b578-fa163e82605e,task_memcg=/kubepods/pod4f0d402b-b045-11ea-b578-fa163e82605e/kata_2b0e7d5c46727f885d1cf37ad45e5d39c4ad24822347ac51a483139eb2cad313,task=qemu-system-x86,pid=1884648,uid=0
[Wed Jun 17 11:03:13 2020] Memory cgroup out of memory: Killed process 1884648 (qemu-system-x86) total-vm:7098852kB, anon-rss:4147772kB, file-rss:6164kB, shmem-rss:4kB, UID:0 pgtables:8376kB oom_score_adj:-500
[Wed Jun 17 11:03:14 2020] oom_reaper: reaped process 1884648 (qemu-system-x86), now anon-rss:0kB, file-rss:16kB, shmem-rss:4kB
[Wed Jun 17 11:03:14 2020] vfio-pci 0000:3b:00.3: vfio_pci: Relaying device request to user (#0)
[Wed Jun 17 11:03:14 2020] mlx5_core 0000:3b:00.3: enabling device (0000 -> 0002)
[Wed Jun 17 11:03:14 2020] mlx5_core 0000:3b:00.3: firmware version: 16.27.2008
[Wed Jun 17 11:03:14 2020] mlx5_core 0000:3b:00.3: Rate limit: 127 rates are supported, range: 0Mbps to 24414Mbps
[Wed Jun 17 11:03:14 2020] mlx5_core 0000:3b:00.3: MLX5E: StrdRq(1) RqSz(8) StrdSz(2048) RxCqeCmprss(0)
[Wed Jun 17 11:03:14 2020] mlx5_core 0000:3b:00.3 enp59s0f3: renamed from eth4
[Wed Jun 17 11:03:15 2020] mlx5_core 0000:3b:00.3 eth0: renamed from enp59s0f3

**Comment by devimc** [comment]
@yadzhang thanks for confirming that this works,  when `sandbox_cgroup_only` is enabled, all the cgroups in the host are honooured, including memory cgroup, so to fix the OOM issue you can:

Option 1: Use PodOverhead https://kubernetes.io/docs/concepts/configuration/pod-overhead/

Option 2 (not sure if this option will work):
a) Change default_memory to 640M in the configuration file
b) Use a smaller rootfs image 128M (currently you are using a custom rootfs which size is 384M)
c) Use the latest kata kernel, it's small and can consume less memory

Option 3: increase memory constraint

**Comment by yadzhang** [comment]
> @yadzhang thanks for confirming that this works, when `sandbox_cgroup_only` is enabled, all the cgroups in the host are honooured, including memory cgroup, so to fix the OOM issue you can:
> 
> Option 1: Use PodOverhead https://kubernetes.io/docs/concepts/configuration/pod-overhead/
> 
> Option 2 (not sure if this option will work):
> a) Change default_memory to 640M in the configuration file
> b) Use a smaller rootfs image 128M (currently you are using a custom rootfs whose size is 384M)
> c) Use the latest kata kernel, it's small and can consume less memory
> d) Use the kata-agent as init process , add init=/usr/bin/kata-agent to kernel_params in the configuration file
> 
> Option 3: increase memory constraint

OK, thanks. I will take a try. And what I want to confirm is why there is no OOM when `sandbox_cgroup_only` is enabled and not using sriov.

**Comment by devimc** [comment]
> And what I want to confirm is why there is no OOM when sandbox_cgroup_only is enabled and not using sriov.

it's expected, you're cold pluging a vfio device, qemu requires more memory to handle it

File: virtcontainers/sandbox.go [hunk 1]
```diff
@@ -1769,7 +1771,16 @@ func (s *Sandbox) AppendDevice(device api.Device) error {
 	switch device.DeviceType() {
 	case config.VhostUserSCSI, config.VhostUserNet, config.VhostUserBlk, config.VhostUserFS:
 		return s.hypervisor.addDevice(device.GetDeviceInfo().(*config.VhostUserDeviceAttrs), vhostuserDev)
+	case config.DeviceVFIO:
+		vfioDevs := device.GetDeviceInfo().([]*config.VFIODev)
+		for _, d := range vfioDevs {
```
Comment (tedyu) [inline virtcontainers/sandbox.go:1776]: Maybe add a check that vfioDevs has only one device.

Comment (devimc) [reply virtcontainers/sandbox.go:1776]: is that check really needed? I don't think so, could you elaborate on this?

Comment (tedyu) [reply virtcontainers/sandbox.go:1776]: If the slice wouldn't have 0 element or more than one element, accessing vfioDevs[0] directly seems to be more readable.

Comment (devimc) [reply virtcontainers/sandbox.go:1776]: thanks, I consider that the current code is readable enough, @kata-containers/runtime wdyt?

Comment (fidencio) [reply virtcontainers/sandbox.go:1776]: I, personally, am not in favour of special-casing a single device unless there's a specific special-case that would only fit a single device.

**Comment by tedyu** [comment]
lgtm

File: virtcontainers/device/drivers/vfio.go [hunk 2]
```diff
@@ -128,6 +141,15 @@ func (device *VFIODevice) Detach(devReceiver api.DeviceReceiver) (retErr error)
 		}
 	}()
 
+	if device.GenericDevice.DeviceInfo.ColdPlug {
+		// nothing to detach, device was cold plugged
+		deviceLogger().WithFields(logrus.Fields{
+			"device-group": device.DeviceInfo.HostPath,
+			"device-type":  "vfio-passthrough",
+		}).Info("Nothing to detach. VFIO device was cold plugged")
```
Comment (egernst) [inline virtcontainers/device/drivers/vfio.go:149]: Question for my own clarity:

Theoretically a container/pod could be created with a device attached, and then the device could be removed as part of an update later on, right?

Is this limitation on our ability to hot-remove a cold-plugged device?

**Comment by egernst** [comment]
First -- sorry for delay in looking at this. 

I think that the current behavior of the cgroup-manager pkg is too static; pod lifecycle is a bit open-ended and we should, theoretically, be able to handle devices being added later, and general container resources being updated. 

Or, am I missing something?

I'm not sure what the cgroup-manager is buying us, tbh. AFAICT, we could just either (1) scan through containers each time we get a new container / container update which would introduce new devices, or (2) keep track of [].spec.LinuxDevices as part of the sandbox config and amend this list when getting new container/container-update. (2) is closer to what's done w/ cgroup-manager, but tied directly to the sandbox struct, rather than dealing with more indirection/global state that may be duplicated? (1) is how we (should) handle cpusets.

**Comment by devimc** [comment]
@egernst thanks for raising your concerns, however, I think this is not the right place to discuss whether the cgroup-manager is a good idea or not, since I'm not reimplmenting  or modifying it in this PR (the cgroup-manager landed **two months ago** https://github.com/kata-containers/runtime/pull/2606). If you consider that there is something to improve or fix, please file an issue, pull requests are welcome too.

**Comment by egernst** [comment]
I understand, and don't intend to frustrate or suggest changing here. I do want to understand the problem though.

Is the VFIO device available as one of the devices in the container's Resource.Devices list? Should we be able to use this as a reference, rather than changing the ordering?

As is, this still sounded a bit fragile?

**Comment by devimc** [comment]
> Is the VFIO device available as one of the devices in the container's Resource.Devices list? Should we be able to use this as a reference, rather than changing the ordering?

No, we remove the vfio devices from the list of devices passed to the agent, since it's a PCI device, the guest kernel driver is responsible for setting it up.

**Comment by egernst** [comment]
Ok. PR LGTM, and we should look at updating the api that the virtcontainers/pkg/cgroups provides in a future PR...

**Comment by yadzhang** [comment]
I take a test with new kernel(config-5.4.32) from [1.11.1 release](https://github.com/kata-containers/runtime/releases/tag/1.11.1) for kata using sriov device. There is error log below and the pod started failed: 

` updateInterface: rpc error: code = NotFound desc = Could not find the link corresponding to HwAddr \"e0:e0:aa:01:0e:0e\"`

The error is reported when kata-runtime prepares to update interface in vm. I add some log and find that there is only a loopback interface in vm and no vfio-pci device for sriov vf. So I think that the ` -device vfio-pci,host=3b:00.3,romfile=` params for qemu-img commands  take no effect and the guest vm does not load vfio-pci device. Also, I can not see any pci-related outputs in  the guest kernel starting log.

And I switch to kernel config 4.19.86 which build with mlx4 and mxl5 module  enabled, the pod is started successfully, and kernel started log has pci output.
```
ixgbevf: Intel(R) 10 Gigabit PCI Express Virtual Function Network Driver - version 4.1.0-k
...
mlx5_core 0000:00:08.0: firmware version: 16.27.2008
...
pci 0000:00:02.0: PCI bridge to [bus 01]
```

So I want to confirm the pod started failed if it is caused by mlx-related config not set in default kernel 5.4.32.

**Comment by devimc** [comment]
@yadzhang thanks, since the last error you're reporting is related to a missing config in the guest kernel, I think we can proceed and merge this change
