### PR TITLE
virtcontainers: honor OCI cgroupsPath

### LINKED ISSUE #1357: Missing cgroupsPath in config.json not tolerated
If you generate a `config.json` spec file using `kata-runtime spec`, you cannot create a container in [standalone](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#running-standalone) mode:

```sh
$ bundle="/tmp/bundle"
$ rootfs="$bundle/rootfs"
$ mkdir -p "$rootfs" && (cd "$bundle" && kata-runtime spec)
$ sudo docker export $(sudo docker create busybox) | tar -C "$rootfs" -xvf -
$ sudo kata-runtime --log=/dev/stdout run --bundle="$bundle" --console= --pid-file=/tmp/pid foo
Could not create cgroup for : cpuset: cgroup parent path outside cgroup root
```

As @devimc points out, adding [the following](https://github.com/kata-containers/tests/blob/master/data/config.json#L125) to the `config.json` makes it work:

```diff
--- config.json 2019-03-12 15:40:22.342576440 +0000
+++ config-fixed.json   2019-03-12 15:40:05.218076822 +0000
@@ -140,6 +140,7 @@
                                }
                        ]
                },
+               "cgroupsPath": "kata",
                "namespaces": [
                        {
                                "type": "pid"

```

### LINKED ISSUE #1365: Error running a container with --cgroup-parent for a specific path
While running
```
$ docker run -d --runtime kata-runtime --cgroup-parent "../../../../" busybox
ca2363e8058f873d2df77b702758f3fd0020cc675caec577431ebf8cff63eb6d
```
We are getting the following error
```
docker: Error response from daemon: OCI runtime create failed: Could not create cgroup for ../../../../ca2363e8058f873d2df77b702758f3fd0020cc675caec577431ebf8cff63eb6d: cpuset: cgroup parent path
```
And it is leaving a directory at
```
$ ls /
ca2363e8058f873d2df77b702758f3fd0020cc675caec577431ebf8cff63eb6d
```
This behaviour is not seen with `runc`

/cc @devimc

### PR DESCRIPTION
**Pull request by devimc**
Create cgroup path relative the cgroups mount point if it's absolute,
or create it relative to a runtime-determined location if the path
is relative.

fixes #1365
fixes #1357

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: virtcontainers/utils/utils_test.go [hunk 1]
```diff
@@ -325,3 +325,12 @@ func TestSupportsVsocks(t *testing.T) {
 
 	assert.True(SupportsVsocks())
 }
+
+func TestValidCgroupPath(t *testing.T) {
+	assert := assert.New(t)
+
+	assert.Equal(defaultCgroupPath, ValidCgroupPath("../../../"))
```
Comment (jodh-intel) [inline virtcontainers/utils/utils_test.go]: Nit: Might be useful to add in a few more scenarios such as `""`, `"/"`, `"../"`, `"."`, `"./../"`, `"o / m /../ g"`, *etc* ;)

**Comment by devimc** [comment]
@jodh-intel change applied, thanks
