### PR TITLE
virtcontainers: check PCI resource format before using it

### LINKED ISSUE #2542: q35: runtime crashes trying to hotplug a VFIO device
```
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.446716727-06:00" level=error msg="fatal error" arch=amd64 name=kata-runtime panic="runtime error: index out of range" pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.550592537-06:00" level=error msg="heap profile: 2: 2432 [8: 12160] @ heap/1048576" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.550697954-06:00" level=error msg="1: 2304 [1: 2304] @ 0x557c5b294807 0x557c5b313db6 0x557c5b3ac58f 0x557c5b3ab4d1 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750b1a 0x557c5b7484d9 0x557c5b7484d4 0x557c5b748434 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.550769986-06:00" level=error msg="#\t0x557c5b294806\treflect.unsafe_NewArray+0x36\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/malloc.go:1090" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.550823161-06:00" level=error msg="#\t0x557c5b313db5\treflect.MakeSlice+0xc5\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/reflect/value.go:2204" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.550867979-06:00" level=error msg="#\t0x557c5b3ac58e\tencoding/json.(*decodeState).array+0x6fe\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:549" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.550912449-06:00" level=error msg="#\t0x557c5b3ab4d0\tencoding/json.(*decodeState).value+0x100\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:371" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55095636-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.550997725-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551040088-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551082766-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551125007-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551172679-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551227581-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55127264-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551314328-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551357086-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551399253-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551442461-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551484851-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551527445-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551574059-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551615945-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55167002-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551714306-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551755759-06:00" level=error msg="#\t0x557c5b750b19\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.JSONSchemaDraft04+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:58" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551802551-06:00" level=error msg="#\t0x557c5b7484d8\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadJSONSchemaDraft04+0x58\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:43" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551848485-06:00" level=error msg="#\t0x557c5b7484d3\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.initResolutionCache+0x53\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/expander.go:62" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551898125-06:00" level=error msg="#\t0x557c5b748433\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.1+0x23\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/expander.go:55" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551947664-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.551987834-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552025622-06:00" level=error msg="1: 128 [1: 128] @ 0x557c5b491257 0x557c5b490da4 0x557c5b746f2d 0x557c5b74d832 0x557c5b74d804 0x557c5b7505a1 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750fc7 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750b1a" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552086557-06:00" level=error msg="#\t0x557c5b491256\tnet/url.parse+0x86\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/net/url/url.go:523" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552137502-06:00" level=error msg="#\t0x557c5b490da3\tnet/url.Parse+0xa3\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/net/url/url.go:482" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552179549-06:00" level=error msg="#\t0x557c5b746f2c\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/jsonreference.(*Ref).parse+0x7c\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/jsonreference/reference.go:117" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55222623-06:00" level=error msg="#\t0x557c5b74d831\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/jsonreference.New+0xe1\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/jsonreference/reference.go:45" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552276366-06:00" level=error msg="#\t0x557c5b74d803\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Ref).fromMap+0xb3\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/ref.go:182" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552323537-06:00" level=error msg="#\t0x557c5b7505a0\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x1b0\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:609" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552369817-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552412519-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552454531-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552500944-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552545251-06:00" level=error msg="#\t0x557c5b750fc6\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*SchemaOrBool).UnmarshalJSON+0xf6\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/swagger.go:129" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552593176-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55264133-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552701104-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552742713-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552783401-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552832438-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552845254-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552859553-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552872202-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552901435-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552935236-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.552948212-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55299774-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553011121-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553041308-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553075309-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553089728-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553102391-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553115179-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553129485-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553142546-06:00" level=error msg="#\t0x557c5b750b19\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.JSONSchemaDraft04+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:58" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553156878-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553167852-06:00" level=error msg="0: 0 [1: 16] @ 0x557c5b3b2b6f 0x557c5b3b23b1 0x557c5b3b2492 0x557c5b3b231f 0x557c5b3b27a5 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3aecbe 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750570 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750c4a 0x557c5b7509d1 0x557c5b7509cc 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553185213-06:00" level=error msg="#\t0x557c5b3b2b6e\tencoding/json.(*decodeState).literalInterface+0x24e\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1135" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553198593-06:00" level=error msg="#\t0x557c5b3b23b0\tencoding/json.(*decodeState).valueInterface+0xe0\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1033" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553211769-06:00" level=error msg="#\t0x557c5b3b2491\tencoding/json.(*decodeState).arrayInterface+0xa1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1048" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.5533929-06:00" level=error msg="#\t0x557c5b3b231e\tencoding/json.(*decodeState).valueInterface+0x4e\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1027" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55342554-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553447643-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55347368-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553497853-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553539466-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553562191-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553583662-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553605384-06:00" level=error msg="#\t0x557c5b3aecbd\tencoding/json.(*decodeState).object+0x215d\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:623" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553624476-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553650649-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553670943-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553694889-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553717849-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553736526-06:00" level=error msg="#\t0x557c5b75056f\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x17f\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:605" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553759532-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553777986-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553799216-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553836595-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553860786-06:00" level=error msg="#\t0x557c5b750c49\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.Swagger20Schema+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:82" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553883574-06:00" level=error msg="#\t0x557c5b7509d0\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema+0x60\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:66" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553909547-06:00" level=error msg="#\t0x557c5b7509cb\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.4+0x5b\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:38" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553933867-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553957953-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.553979808-06:00" level=error msg="0: 0 [1: 512] @ 0x557c5b750434 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750c4a 0x557c5b7509d1 0x557c5b7509cc 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554006839-06:00" level=error msg="#\t0x557c5b750433\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x43\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:591" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554035852-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554056635-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554080399-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554104661-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554126622-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554149762-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554173782-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55419891-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554223638-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55424651-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554271107-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554292006-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554315862-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554340153-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554362027-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554385782-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554406169-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554429991-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554455474-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554475708-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554568902-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554610373-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554638654-06:00" level=error msg="#\t0x557c5b750c49\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.Swagger20Schema+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:82" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554674556-06:00" level=error msg="#\t0x557c5b7509d0\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema+0x60\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:66" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554698913-06:00" level=error msg="#\t0x557c5b7509cb\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.4+0x5b\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:38" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554726897-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55475104-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554770697-06:00" level=error msg="0: 0 [1: 80] @ 0x557c5b3b2b4d 0x557c5b3b2b03 0x557c5b3b23b1 0x557c5b3b27a5 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3aecbe 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750570 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750c4a 0x557c5b7509d1 0x557c5b7509cc 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554802328-06:00" level=error msg="#\t0x557c5b3b2b4c\tencoding/json.unquote+0x22c\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1176" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.554823752-06:00" level=error msg="#\t0x557c5b3b2b02\tencoding/json.(*decodeState).literalInterface+0x1e2\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1131" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555003016-06:00" level=error msg="#\t0x557c5b3b23b0\tencoding/json.(*decodeState).valueInterface+0xe0\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1033" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555030004-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555048187-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555064215-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555080434-06:00" level=error msg="#\t0x557c5b3aecbd\tencoding/json.(*decodeState).object+0x215d\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:623" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555096204-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555114027-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555129808-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555144494-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555159291-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555174142-06:00" level=error msg="#\t0x557c5b75056f\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x17f\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:605" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555190863-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555205496-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555220488-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555235498-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555249994-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555264576-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555279499-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555294304-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555308992-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555324999-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555339296-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555355302-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555370612-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55538553-06:00" level=error msg="#\t0x557c5b750c49\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.Swagger20Schema+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:82" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555401982-06:00" level=error msg="#\t0x557c5b7509d0\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema+0x60\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:66" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55541798-06:00" level=error msg="#\t0x557c5b7509cb\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.4+0x5b\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:38" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555434183-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555448616-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555461691-06:00" level=error msg="0: 0 [1: 640] @ 0x557c5b71c37e 0x557c5b75064c 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750c4a 0x557c5b7509d1 0x557c5b7509cc 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555481591-06:00" level=error msg="#\t0x557c5b71c37d\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/swag.(*NameProvider).GetJSONNames+0x1cd\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/swag/json.go:264" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555497561-06:00" level=error msg="#\t0x557c5b75064b\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x25b\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:614" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555513706-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555528643-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555542868-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555557715-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555576511-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555592019-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55560869-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555622947-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555637934-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555661173-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555676625-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555691332-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555705839-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555720052-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555736497-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555751026-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555765602-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555779951-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555796527-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555812599-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555828229-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555842897-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555857436-06:00" level=error msg="#\t0x557c5b750c49\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.Swagger20Schema+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:82" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555873405-06:00" level=error msg="#\t0x557c5b7509d0\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema+0x60\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:66" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555889625-06:00" level=error msg="#\t0x557c5b7509cb\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.4+0x5b\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:38" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555905339-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555919032-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555931909-06:00" level=error msg="0: 0 [0: 0] @ 0x557c5b354d03 0x557c5b35480f 0x557c5b3527cb 0x557c5b35284f 0x557c5bbca95f 0x557c5bc1038f 0x557c5bc0dbb8 0x557c5bbb87da 0x557c5bbbc397 0x557c5bbeb277 0x557c5bb5deff 0x557c5bb5dc10 0x557c5bb92ee1 0x557c5bc88529 0x557c5bcb7197 0x557c5bcd2862 0x557c5bc974fa 0x557c5bc986c8 0x557c5bc95831 0x557c5bcc77ed 0x557c5bcc7cac 0x557c5bcc7d7e 0x557c5b2b7364 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555950486-06:00" level=error msg="#\t0x557c5b354d02\tos.statNolog+0x32\t\t\t\t\t\t\t\t\t/usr/local/go/src/os/stat_unix.go:30" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555964297-06:00" level=error msg="#\t0x557c5b35480e\tos.Stat+0x4e\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/os/stat.go:13" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555978744-06:00" level=error msg="#\t0x557c5b3527ca\tos.MkdirAll+0x3a\t\t\t\t\t\t\t\t\t/usr/local/go/src/os/path.go:20" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.555992556-06:00" level=error msg="#\t0x557c5b35284e\tos.MkdirAll+0xbe\t\t\t\t\t\t\t\t\t/usr/local/go/src/os/path.go:41" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556006875-06:00" level=error msg="#\t0x557c5bbca95e\tgithub.com/kata-containers/runtime/virtcontainers.(*qemu).startSandbox+0x18e\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/qemu.go:780" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556022447-06:00" level=error msg="#\t0x557c5bc1038e\tgithub.com/kata-containers/runtime/virtcontainers.(*Sandbox).startVM.func1+0x22e\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/sandbox.go:1020" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556039358-06:00" level=error msg="#\t0x557c5bc0dbb7\tgithub.com/kata-containers/runtime/virtcontainers.(*Network).Run.func1+0x27\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:1234" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556055792-06:00" level=error msg="#\t0x557c5bbb87d9\tgithub.com/kata-containers/runtime/virtcontainers.doNetNS+0x149\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:920" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556073737-06:00" level=error msg="#\t0x557c5bbbc396\tgithub.com/kata-containers/runtime/virtcontainers.(*Network).Run+0xd6\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:1233" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556089935-06:00" level=error msg="#\t0x557c5bbeb276\tgithub.com/kata-containers/runtime/virtcontainers.(*Sandbox).startVM+0x2d6\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/sandbox.go:1003" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556108604-06:00" level=error msg="#\t0x557c5bb5defe\tgithub.com/kata-containers/runtime/virtcontainers.createSandboxFromConfig+0x21e\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/api.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556125516-06:00" level=error msg="#\t0x557c5bb5dc0f\tgithub.com/kata-containers/runtime/virtcontainers.CreateSandbox+0x11f\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/api.go:61" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556141157-06:00" level=error msg="#\t0x557c5bb92ee0\tgithub.com/kata-containers/runtime/virtcontainers.(*VCImpl).CreateSandbox+0x90\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/implementation.go:41" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556156572-06:00" level=error msg="#\t0x557c5bc88528\tgithub.com/kata-containers/runtime/pkg/katautils.CreateSandbox+0x418\t\t\t/home/X/go/src/github.com/kata-containers/runtime/pkg/katautils/create.go:161" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556172253-06:00" level=error msg="#\t0x557c5bcb7196\tmain.create+0x7c6\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/create.go:137" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556186865-06:00" level=error msg="#\t0x557c5bcd2861\tmain.glob..func1+0x3e1\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/create.go:79" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556202122-06:00" level=error msg="#\t0x557c5bc974f9\tgithub.com/kata-containers/runtime/vendor/github.com/urfave/cli.HandleAction+0xc9\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/app.go:490" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556217851-06:00" level=error msg="#\t0x557c5bc986c7\tgithub.com/kata-containers/runtime/vendor/github.com/urfave/cli.Command.Run+0x997\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/command.go:210" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55623503-06:00" level=error msg="#\t0x557c5bc95830\tgithub.com/kata-containers/runtime/vendor/github.com/urfave/cli.(*App).Run+0x6b0\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/app.go:255" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556253351-06:00" level=error msg="#\t0x557c5bcc77ec\tmain.createRuntimeApp+0x22c\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:530" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556270182-06:00" level=error msg="#\t0x557c5bcc7cab\tmain.createRuntime+0x7b\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:573" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556284889-06:00" level=error msg="#\t0x557c5bcc7d7d\tmain.main+0x9d\t\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:605" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556299528-06:00" level=error msg="#\t0x557c5b2b7363\truntime.main+0x213\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:200" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556313439-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556326448-06:00" level=error msg="0: 0 [0: 0] @ 0x557c5b617753 0x557c5b64be0e 0x557c5b64bc49 0x557c5b64aae9 0x557c5bbb3cdf 0x557c5bbb365b 0x557c5bbb6560 0x557c5bbb4635 0x557c5bbff07b 0x557c5bc0e059 0x557c5bbb87da 0x557c5bbbc59b 0x557c5bbe9a69 0x557c5bb5de91 0x557c5bb5dc10 0x557c5bb92ee1 0x557c5bc88529 0x557c5bcb7197 0x557c5bcd2862 0x557c5bc974fa 0x557c5bc986c8 0x557c5bc95831 0x557c5bcc77ed 0x557c5bcc7cac 0x557c5bcc7d7e 0x557c5b2b7364 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556345186-06:00" level=error msg="#\t0x557c5b617752\tgithub.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink/nl.ParseRouteAttr+0x182\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:720" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556361554-06:00" level=error msg="#\t0x557c5b64be0d\tgithub.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink.LinkDeserialize+0x8d\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink/link_linux.go:1397" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556377274-06:00" level=error msg="#\t0x557c5b64bc48\tgithub.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink.execGetLink+0x288\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink/link_linux.go:1385" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556393197-06:00" level=error msg="#\t0x557c5b64aae8\tgithub.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink.(*Handle).LinkByName+0x358\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink/link_linux.go:1305" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556408962-06:00" level=error msg="#\t0x557c5bbb3cde\tgithub.com/kata-containers/runtime/virtcontainers.getLinkByName+0x5e\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:371" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556424546-06:00" level=error msg="#\t0x557c5bbb365a\tgithub.com/kata-containers/runtime/virtcontainers.createLink+0x38a\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:347" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556441624-06:00" level=error msg="#\t0x557c5bbb655f\tgithub.com/kata-containers/runtime/virtcontainers.setupTCFiltering+0x12f\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:635" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556457235-06:00" level=error msg="#\t0x557c5bbb4634\tgithub.com/kata-containers/runtime/virtcontainers.xConnectVMNetwork+0x1c4\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:429" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556473601-06:00" level=error msg="#\t0x557c5bbff07a\tgithub.com/kata-containers/runtime/virtcontainers.(*VethEndpoint).Attach+0x6a\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/veth_endpoint.go:91" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556490961-06:00" level=error msg="#\t0x557c5bc0e058\tgithub.com/kata-containers/runtime/virtcontainers.(*Network).Add.func1+0x478\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:1256" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55650658-06:00" level=error msg="#\t0x557c5bbb87d9\tgithub.com/kata-containers/runtime/virtcontainers.doNetNS+0x149\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:920" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556522026-06:00" level=error msg="#\t0x557c5bbbc59a\tgithub.com/kata-containers/runtime/virtcontainers.(*Network).Add+0x1ba\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:1248" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556537356-06:00" level=error msg="#\t0x557c5bbe9a68\tgithub.com/kata-containers/runtime/virtcontainers.(*Sandbox).createNetwork+0x1c8\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/sandbox.go:866" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55655252-06:00" level=error msg="#\t0x557c5bb5de90\tgithub.com/kata-containers/runtime/virtcontainers.createSandboxFromConfig+0x1b0\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/api.go:94" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556569127-06:00" level=error msg="#\t0x557c5bb5dc0f\tgithub.com/kata-containers/runtime/virtcontainers.CreateSandbox+0x11f\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/api.go:61" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556586532-06:00" level=error msg="#\t0x557c5bb92ee0\tgithub.com/kata-containers/runtime/virtcontainers.(*VCImpl).CreateSandbox+0x90\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/implementation.go:41" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556602519-06:00" level=error msg="#\t0x557c5bc88528\tgithub.com/kata-containers/runtime/pkg/katautils.CreateSandbox+0x418\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/pkg/katautils/create.go:161" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556617986-06:00" level=error msg="#\t0x557c5bcb7196\tmain.create+0x7c6\t\t\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/create.go:137" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556632569-06:00" level=error msg="#\t0x557c5bcd2861\tmain.glob..func1+0x3e1\t\t\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/create.go:79" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556652925-06:00" level=error msg="#\t0x557c5bc974f9\tgithub.com/kata-containers/runtime/vendor/github.com/urfave/cli.HandleAction+0xc9\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/app.go:490" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556670492-06:00" level=error msg="#\t0x557c5bc986c7\tgithub.com/kata-containers/runtime/vendor/github.com/urfave/cli.Command.Run+0x997\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/command.go:210" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556687725-06:00" level=error msg="#\t0x557c5bc95830\tgithub.com/kata-containers/runtime/vendor/github.com/urfave/cli.(*App).Run+0x6b0\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/app.go:255" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556704178-06:00" level=error msg="#\t0x557c5bcc77ec\tmain.createRuntimeApp+0x22c\t\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:530" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556718594-06:00" level=error msg="#\t0x557c5bcc7cab\tmain.createRuntime+0x7b\t\t\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:573" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556733362-06:00" level=error msg="#\t0x557c5bcc7d7d\tmain.main+0x9d\t\t\t\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:605" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556748004-06:00" level=error msg="#\t0x557c5b2b7363\truntime.main+0x213\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:200" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556761925-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556774183-06:00" level=error msg="0: 0 [1: 8192] @ 0x557c5b37876f 0x557c5b3780a1 0x557c5b37855d 0x557c5b32461e 0x557c5b74765e 0x557c5b747624 0x557c5b7479af 0x557c5b747972 0x557c5b747e8a 0x557c5b750a9c 0x557c5b7484d9 0x557c5b7484d4 0x557c5b748434 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556791154-06:00" level=error msg="#\t0x557c5b37876e\tbytes.makeSlice+0x6e\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/bytes/buffer.go:232" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556805824-06:00" level=error msg="#\t0x557c5b3780a0\tbytes.(*Buffer).grow+0x170\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/bytes/buffer.go:145" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556820118-06:00" level=error msg="#\t0x557c5b37855c\tbytes.(*Buffer).ReadFrom+0x4c\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/bytes/buffer.go:205" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556834408-06:00" level=error msg="#\t0x557c5b32461d\tio.copyBuffer+0x2fd\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/io/io.go:388" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556848747-06:00" level=error msg="#\t0x557c5b74765d\tio.Copy+0x24d\t\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/io/io.go:364" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556862739-06:00" level=error msg="#\t0x557c5b747623\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.bindataRead+0x213\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/bindata.go:28" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556879491-06:00" level=error msg="#\t0x557c5b7479ae\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.jsonschemaDraft04JSONBytes+0x6e\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/bindata.go:75" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556895983-06:00" level=error msg="#\t0x557c5b747971\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.jsonschemaDraft04JSON+0x31\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/bindata.go:82" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556913457-06:00" level=error msg="#\t0x557c5b747e89\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.Asset+0xc9\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/bindata.go:118" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556929776-06:00" level=error msg="#\t0x557c5b750a9b\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.JSONSchemaDraft04+0x3b\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:52" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556945897-06:00" level=error msg="#\t0x557c5b7484d8\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadJSONSchemaDraft04+0x58\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:43" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556963161-06:00" level=error msg="#\t0x557c5b7484d3\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.initResolutionCache+0x53\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/expander.go:62" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556979083-06:00" level=error msg="#\t0x557c5b748433\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.1+0x23\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/expander.go:55" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.556994923-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557009097-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557023407-06:00" level=error msg="0: 0 [1: 288] @ 0x557c5b29b09e 0x557c5b3b27e7 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3aecbe 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750570 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750c4a 0x557c5b7484a9 0x557c5b7484a4 0x557c5b748434 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557041882-06:00" level=error msg="#\t0x557c5b3b27e6\tencoding/json.(*decodeState).objectInterface+0x1c6\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557056723-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55707132-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55708889-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557105064-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557120356-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557140653-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557157475-06:00" level=error msg="#\t0x557c5b3aecbd\tencoding/json.(*decodeState).object+0x215d\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:623" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557172175-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557189535-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557204039-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557217833-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557231998-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557246444-06:00" level=error msg="#\t0x557c5b75056f\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x17f\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:605" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55726433-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557279067-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557294148-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557308599-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557323548-06:00" level=error msg="#\t0x557c5b750c49\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.Swagger20Schema+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:82" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557339059-06:00" level=error msg="#\t0x557c5b7484a8\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema+0x28\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:66" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557354725-06:00" level=error msg="#\t0x557c5b7484a3\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.initResolutionCache+0x23\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/expander.go:61" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557373227-06:00" level=error msg="#\t0x557c5b748433\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.1+0x23\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/expander.go:55" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557390017-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557403929-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557416182-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557428231-06:00" level=error msg="# runtime.MemStats" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557442426-06:00" level=error msg="# Alloc = 2095112" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557455615-06:00" level=error msg="# TotalAlloc = 8442504" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55746826-06:00" level=error msg="# Sys = 71762168" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557481071-06:00" level=error msg="# Lookups = 0" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557493889-06:00" level=error msg="# Mallocs = 71517" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557506639-06:00" level=error msg="# Frees = 54816" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557519999-06:00" level=error msg="# HeapAlloc = 2095112" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557534676-06:00" level=error msg="# HeapSys = 66551808" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557547796-06:00" level=error msg="# HeapIdle = 62562304" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557562103-06:00" level=error msg="# HeapInuse = 3989504" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557574958-06:00" level=error msg="# HeapReleased = 0" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55758743-06:00" level=error msg="# HeapObjects = 16701" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557600451-06:00" level=error msg="# Stack = 557056 / 557056" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557613213-06:00" level=error msg="# MSpan = 71136 / 81920" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557625751-06:00" level=error msg="# MCache = 3472 / 16384" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557638802-06:00" level=error msg="# BuckHashSys = 1448143" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557655592-06:00" level=error msg="# GCSys = 2385920" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557669955-06:00" level=error msg="# OtherSys = 720937" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557682616-06:00" level=error msg="# NextGC = 4194304" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557697353-06:00" level=error msg="# LastGC = 1584721520446517984" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557712201-06:00" level=error msg="# PauseNs = [148026 4402 12571 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557734693-06:00" level=error msg="# PauseEnd = [1584721519921685513 1584721519929164810 1584721520446517984 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55775787-06:00" level=error msg="# NumGC = 3" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557770592-06:00" level=error msg="# NumForcedGC = 0" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557782866-06:00" level=error msg="# GCCPUFraction = 0.001401758890938325" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557795916-06:00" level=error msg="# DebugGC = false" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557808211-06:00" level=error msg="--- contention:" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557820884-06:00" level=error msg="cycles/second=3096020753" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557833452-06:00" level=error msg="goroutine 1 [running, locked to thread]:" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557846507-06:00" level=error msg="runtime/pprof.writeGoroutineStacks(0x557c5c2dcee0, 0xc00035b1d0, 0xc000205000, 0x1000)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557860573-06:00" level=error msg="\t/usr/local/go/src/runtime/pprof/pprof.go:679 +0x9f" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557873416-06:00" level=error msg="runtime/pprof.writeGoroutine(0x557c5c2dcee0, 0xc00035b1d0, 0x2, 0x0, 0x0)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557887146-06:00" level=error msg="\t/usr/local/go/src/runtime/pprof/pprof.go:668 +0x46" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557900364-06:00" level=error msg="runtime/pprof.(*Profile).WriteTo(0x557c5cb16680, 0x557c5c2dcee0, 0xc00035b1d0, 0x2, 0x0, 0x0)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557917103-06:00" level=error msg="\t/usr/local/go/src/runtime/pprof/pprof.go:329 +0x392" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557930563-06:00" level=error msg="github.com/kata-containers/runtime/pkg/signals.Backtrace()" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557945459-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/pkg/signals/signals.go:73 +0xb8" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557961669-06:00" level=error msg="github.com/kata-containers/runtime/pkg/signals.Die(0xc0005bdf70)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55797606-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/pkg/signals/signals.go:119 +0x32" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.557990652-06:00" level=error msg="github.com/kata-containers/runtime/pkg/signals.HandlePanic(0xc0005bdf70)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558006045-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/pkg/signals/signals.go:60 +0x1f7" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558021869-06:00" level=error msg="panic(0x557c5c187540, 0x557c5cb128d0)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558034918-06:00" level=error msg="\t/usr/local/go/src/runtime/panic.go:522 +0x1b9" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558048612-06:00" level=error msg="github.com/kata-containers/runtime/virtcontainers/device/manager.isLargeBarSpace(0xc000366040, 0x38, 0x3, 0xc000366040, 0x38)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558065196-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/device/manager/utils.go:108 +0x904" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558082545-06:00" level=error msg="github.com/kata-containers/runtime/virtcontainers/device/manager.IsVFIOLargeBarSpaceDevice(0xc0003d5e20, 0xb, 0x0, 0xc00030f080, 0x0)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558098595-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/device/manager/utils.go:64 +0x921" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558112631-06:00" level=error msg="github.com/kata-containers/runtime/virtcontainers.(*Container).create(0xc00030f080, 0x0, 0x0)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558127262-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/container.go:875 +0x1d7" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558143029-06:00" level=error msg="github.com/kata-containers/runtime/virtcontainers.(*Sandbox).createContainers(0xc0004e3340, 0x0, 0x0)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558157526-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/sandbox.go:1463 +0x17c" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55817181-06:00" level=error msg="github.com/kata-containers/runtime/virtcontainers.createSandboxFromConfig(0x557c5c2fce80, 0xc0004a1260, 0x7fffb255ce26, 0x40, 0xc0003d58d0, 0xc, 0x557c5bce3c58, 0x4, 0x800000001, 0x100000800, ...)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558187577-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/api.go:124 +0x30c" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558202587-06:00" level=error msg="github.com/kata-containers/runtime/virtcontainers.CreateSandbox(0x557c5c2fce80, 0xc0004a1230, 0x7fffb255ce26, 0x40, 0xc0003d58d0, 0xc, 0x557c5bce3c58, 0x4, 0x800000001, 0x100000800, ...)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55822093-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/api.go:61 +0x120" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558236333-06:00" level=error msg="github.com/kata-containers/runtime/virtcontainers.(*VCImpl).CreateSandbox(0x557c5cb6f6f0, 0x557c5c2fce80, 0xc0004a1050, 0x7fffb255ce26, 0x40, 0xc0003d58d0, 0xc, 0x557c5bce3c58, 0x4, 0x800000001, ...)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558252685-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/implementation.go:41 +0x91" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558268087-06:00" level=error msg="github.com/kata-containers/runtime/pkg/katautils.CreateSandbox(0x557c5c2fce80, 0xc0004a1050, 0x557c5c317740, 0x557c5cb6f6f0, 0xc0003d52d0, 0x9, 0xc0000323c0, 0xc000430b60, 0xc0003d58d0, 0xc, ...)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558285335-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/pkg/katautils/create.go:161 +0x419" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558299609-06:00" level=error msg="main.create(0x557c5c2fce80, 0xc000459b90, 0x7fffb255ce26, 0x40, 0xc00009aa80, 0x74, 0xc00043d480, 0xa, 0x7fffb255cd7c, 0x7d, ...)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558313819-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/cli/create.go:137 +0x7c7" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558327198-06:00" level=error msg="main.glob..func1(0xc0004e3080, 0x10100, 0xc0004e3080)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558341413-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/cli/create.go:79 +0x3e2" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558355975-06:00" level=error msg="github.com/kata-containers/runtime/vendor/github.com/urfave/cli.HandleAction(0x557c5c13d980, 0x557c5c2c0b60, 0xc0004e3080, 0xc000192400, 0x0)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558371021-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/app.go:490 +0xca" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558384738-06:00" level=error msg="github.com/kata-containers/runtime/vendor/github.com/urfave/cli.Command.Run(0x557c5bce5897, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x557c5bcf2f75, 0x12, 0x0, ...)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558400072-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/command.go:210 +0x998" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558413987-06:00" level=error msg="github.com/kata-containers/runtime/vendor/github.com/urfave/cli.(*App).Run(0xc0002f4000, 0xc0000320f0, 0xf, 0xf, 0x0, 0x0)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558428068-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/app.go:255 +0x6b1" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558441535-06:00" level=error msg="main.createRuntimeApp(0x557c5c2fce00, 0xc000036028, 0xc0000320f0, 0xf, 0xf, 0x0, 0xc0004f9f58)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558455263-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:530 +0x22d" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558469953-06:00" level=error msg="main.createRuntime(0x557c5c2fce00, 0xc000036028)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558483362-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:573 +0x7c" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558499119-06:00" level=error msg="main.main()" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558512117-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:605 +0x9e" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.5585259-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558540378-06:00" level=error msg="goroutine 8 [syscall]:" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558555375-06:00" level=error msg="os/signal.signal_recv(0x0)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558568472-06:00" level=error msg="\t/usr/local/go/src/runtime/sigqueue.go:139 +0x9e" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558581912-06:00" level=error msg="os/signal.loop()" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558594686-06:00" level=error msg="\t/usr/local/go/src/os/signal/signal_unix.go:23 +0x24" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558609853-06:00" level=error msg="created by os/signal.init.0" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558624028-06:00" level=error msg="\t/usr/local/go/src/os/signal/signal_unix.go:29 +0x43" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55863736-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558653602-06:00" level=error msg="goroutine 18 [chan receive]:" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558667194-06:00" level=error msg="main.setupSignalHandler.func2(0xc00007cba0, 0xc00046a020)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558680368-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:206 +0x5d" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558694032-06:00" level=error msg="created by main.setupSignalHandler" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558706997-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:204 +0x14d" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558720612-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558733713-06:00" level=error msg="goroutine 23 [syscall]:" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558746505-06:00" level=error msg="syscall.Syscall6(0xf7, 0x1, 0x3fbb, 0xc0004f0638, 0x1000004, 0x0, 0x0, 0xc0001251b8, 0xc0004f0778, 0xc0000114b0)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558761119-06:00" level=error msg="\t/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558790836-06:00" level=error msg="os.(*Process).blockUntilWaitable(0xc00054bbf0, 0xc00009af80, 0x77, 0x77)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55880575-06:00" level=error msg="\t/usr/local/go/src/os/wait_waitid.go:31 +0x9a" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558823301-06:00" level=error msg="os.(*Process).wait(0xc00054bbf0, 0xc0004f06f8, 0x1, 0x0)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558840059-06:00" level=error msg="\t/usr/local/go/src/os/exec_unix.go:22 +0x3b" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558854434-06:00" level=error msg="os.(*Process).Wait(...)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558868106-06:00" level=error msg="\t/usr/local/go/src/os/exec.go:125" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558882271-06:00" level=error msg="os/exec.(*Cmd).Wait(0xc0004e3760, 0x6, 0x6)" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558896269-06:00" level=error msg="\t/usr/local/go/src/os/exec/exec.go:474 +0x63" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558910391-06:00" level=error msg="created by github.com/kata-containers/runtime/virtcontainers.(*kataProxy).start" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558925047-06:00" level=error msg="\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/kata_proxy.go:57 +0x2e4" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55894009-06:00" level=error msg="heap profile: 2: 2432 [8: 12160] @ heap/1048576" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558955747-06:00" level=error msg="1: 2304 [1: 2304] @ 0x557c5b294807 0x557c5b313db6 0x557c5b3ac58f 0x557c5b3ab4d1 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750b1a 0x557c5b7484d9 0x557c5b7484d4 0x557c5b748434 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558978479-06:00" level=error msg="#\t0x557c5b294806\treflect.unsafe_NewArray+0x36\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/malloc.go:1090" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.558994222-06:00" level=error msg="#\t0x557c5b313db5\treflect.MakeSlice+0xc5\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/reflect/value.go:2204" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559010923-06:00" level=error msg="#\t0x557c5b3ac58e\tencoding/json.(*decodeState).array+0x6fe\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:549" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559026312-06:00" level=error msg="#\t0x557c5b3ab4d0\tencoding/json.(*decodeState).value+0x100\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:371" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559041827-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559058571-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559074363-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559091131-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559110348-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559129-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55914486-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559161545-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559177229-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559193315-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559208776-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559224104-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559241275-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559256778-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559273882-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559289458-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559306217-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559321813-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559336549-06:00" level=error msg="#\t0x557c5b750b19\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.JSONSchemaDraft04+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:58" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559356107-06:00" level=error msg="#\t0x557c5b7484d8\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadJSONSchemaDraft04+0x58\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:43" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559375763-06:00" level=error msg="#\t0x557c5b7484d3\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.initResolutionCache+0x53\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/expander.go:62" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559393248-06:00" level=error msg="#\t0x557c5b748433\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.1+0x23\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/expander.go:55" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559410147-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559427824-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559441611-06:00" level=error msg="1: 128 [1: 128] @ 0x557c5b491257 0x557c5b490da4 0x557c5b746f2d 0x557c5b74d832 0x557c5b74d804 0x557c5b7505a1 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750fc7 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750b1a" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559463195-06:00" level=error msg="#\t0x557c5b491256\tnet/url.parse+0x86\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/net/url/url.go:523" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559480022-06:00" level=error msg="#\t0x557c5b490da3\tnet/url.Parse+0xa3\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/net/url/url.go:482" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559496523-06:00" level=error msg="#\t0x557c5b746f2c\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/jsonreference.(*Ref).parse+0x7c\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/jsonreference/reference.go:117" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559516146-06:00" level=error msg="#\t0x557c5b74d831\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/jsonreference.New+0xe1\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/jsonreference/reference.go:45" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559533824-06:00" level=error msg="#\t0x557c5b74d803\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Ref).fromMap+0xb3\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/ref.go:182" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559551183-06:00" level=error msg="#\t0x557c5b7505a0\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x1b0\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:609" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559569129-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559586729-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559602989-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559618704-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559633856-06:00" level=error msg="#\t0x557c5b750fc6\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*SchemaOrBool).UnmarshalJSON+0xf6\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/swagger.go:129" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559655333-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559672998-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559688652-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559703818-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55971898-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559734763-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559749987-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559769248-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559785281-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559803121-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559819143-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559837418-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559853444-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559868838-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559884177-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55990188-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559919552-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559935189-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.55995026-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559965874-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559981445-06:00" level=error msg="#\t0x557c5b750b19\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.JSONSchemaDraft04+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:58" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.559998367-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560011634-06:00" level=error msg="0: 0 [1: 16] @ 0x557c5b3b2b6f 0x557c5b3b23b1 0x557c5b3b2492 0x557c5b3b231f 0x557c5b3b27a5 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3aecbe 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750570 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750c4a 0x557c5b7509d1 0x557c5b7509cc 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560032027-06:00" level=error msg="#\t0x557c5b3b2b6e\tencoding/json.(*decodeState).literalInterface+0x24e\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1135" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560051396-06:00" level=error msg="#\t0x557c5b3b23b0\tencoding/json.(*decodeState).valueInterface+0xe0\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1033" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560067675-06:00" level=error msg="#\t0x557c5b3b2491\tencoding/json.(*decodeState).arrayInterface+0xa1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1048" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560084763-06:00" level=error msg="#\t0x557c5b3b231e\tencoding/json.(*decodeState).valueInterface+0x4e\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1027" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560101183-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560118407-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560135948-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560153069-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560176338-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560192273-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560207754-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560222939-06:00" level=error msg="#\t0x557c5b3aecbd\tencoding/json.(*decodeState).object+0x215d\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:623" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560238443-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560253896-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560269135-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56028443-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560301558-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560317182-06:00" level=error msg="#\t0x557c5b75056f\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x17f\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:605" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560334204-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560352466-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560369755-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560385466-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560400712-06:00" level=error msg="#\t0x557c5b750c49\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.Swagger20Schema+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:82" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560417697-06:00" level=error msg="#\t0x557c5b7509d0\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema+0x60\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:66" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560434351-06:00" level=error msg="#\t0x557c5b7509cb\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.4+0x5b\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:38" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56045466-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560469676-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560484165-06:00" level=error msg="0: 0 [1: 512] @ 0x557c5b750434 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750c4a 0x557c5b7509d1 0x557c5b7509cc 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56050503-06:00" level=error msg="#\t0x557c5b750433\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x43\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:591" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560522086-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560537834-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560553324-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560568565-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560587036-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560604245-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560620189-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560636136-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560655159-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560672958-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560688294-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560703659-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560719013-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560734375-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560749495-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56076497-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560780213-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560797106-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560815835-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560834515-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560852096-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560868904-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560886001-06:00" level=error msg="#\t0x557c5b750c49\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.Swagger20Schema+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:82" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560909012-06:00" level=error msg="#\t0x557c5b7509d0\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema+0x60\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:66" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560927123-06:00" level=error msg="#\t0x557c5b7509cb\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.4+0x5b\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:38" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560944138-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560959081-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560972169-06:00" level=error msg="0: 0 [1: 80] @ 0x557c5b3b2b4d 0x557c5b3b2b03 0x557c5b3b23b1 0x557c5b3b27a5 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3aecbe 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750570 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750c4a 0x557c5b7509d1 0x557c5b7509cc 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.560998065-06:00" level=error msg="#\t0x557c5b3b2b4c\tencoding/json.unquote+0x22c\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1176" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561013902-06:00" level=error msg="#\t0x557c5b3b2b02\tencoding/json.(*decodeState).literalInterface+0x1e2\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1131" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561029408-06:00" level=error msg="#\t0x557c5b3b23b0\tencoding/json.(*decodeState).valueInterface+0xe0\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1033" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561044767-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561060009-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561076988-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561093916-06:00" level=error msg="#\t0x557c5b3aecbd\tencoding/json.(*decodeState).object+0x215d\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:623" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561109912-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561127727-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561143637-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561161603-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561178349-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56119537-06:00" level=error msg="#\t0x557c5b75056f\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x17f\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:605" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561212498-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561227817-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561244337-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561259317-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561274754-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56129001-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561306129-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561321784-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561337261-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561355861-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561371818-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561387688-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561403426-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561418746-06:00" level=error msg="#\t0x557c5b750c49\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.Swagger20Schema+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:82" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561435726-06:00" level=error msg="#\t0x557c5b7509d0\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema+0x60\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:66" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561454464-06:00" level=error msg="#\t0x557c5b7509cb\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.4+0x5b\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:38" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561473243-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561489401-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561502479-06:00" level=error msg="0: 0 [1: 640] @ 0x557c5b71c37e 0x557c5b75064c 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b75047a 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750c4a 0x557c5b7509d1 0x557c5b7509cc 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561525126-06:00" level=error msg="#\t0x557c5b71c37d\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/swag.(*NameProvider).GetJSONNames+0x1cd\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/swag/json.go:264" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561545691-06:00" level=error msg="#\t0x557c5b75064b\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x25b\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:614" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56156342-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561581719-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561597708-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56161332-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56162901-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561644399-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561667985-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561686331-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.561701896-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.5649952-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565021137-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565041421-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565058346-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565075959-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565092087-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565109125-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565124804-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565143223-06:00" level=error msg="#\t0x557c5b750479\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x89\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:595" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565162158-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.5651801-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565196031-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565212098-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565227713-06:00" level=error msg="#\t0x557c5b750c49\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.Swagger20Schema+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:82" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565245143-06:00" level=error msg="#\t0x557c5b7509d0\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema+0x60\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:66" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565262832-06:00" level=error msg="#\t0x557c5b7509cb\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.4+0x5b\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:38" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565280225-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565295331-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565310626-06:00" level=error msg="0: 0 [0: 0] @ 0x557c5b354d03 0x557c5b35480f 0x557c5b3527cb 0x557c5b35284f 0x557c5bbca95f 0x557c5bc1038f 0x557c5bc0dbb8 0x557c5bbb87da 0x557c5bbbc397 0x557c5bbeb277 0x557c5bb5deff 0x557c5bb5dc10 0x557c5bb92ee1 0x557c5bc88529 0x557c5bcb7197 0x557c5bcd2862 0x557c5bc974fa 0x557c5bc986c8 0x557c5bc95831 0x557c5bcc77ed 0x557c5bcc7cac 0x557c5bcc7d7e 0x557c5b2b7364 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565331317-06:00" level=error msg="#\t0x557c5b354d02\tos.statNolog+0x32\t\t\t\t\t\t\t\t\t/usr/local/go/src/os/stat_unix.go:30" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565346061-06:00" level=error msg="#\t0x557c5b35480e\tos.Stat+0x4e\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/os/stat.go:13" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565361188-06:00" level=error msg="#\t0x557c5b3527ca\tos.MkdirAll+0x3a\t\t\t\t\t\t\t\t\t/usr/local/go/src/os/path.go:20" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565376453-06:00" level=error msg="#\t0x557c5b35284e\tos.MkdirAll+0xbe\t\t\t\t\t\t\t\t\t/usr/local/go/src/os/path.go:41" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565392865-06:00" level=error msg="#\t0x557c5bbca95e\tgithub.com/kata-containers/runtime/virtcontainers.(*qemu).startSandbox+0x18e\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/qemu.go:780" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56541034-06:00" level=error msg="#\t0x557c5bc1038e\tgithub.com/kata-containers/runtime/virtcontainers.(*Sandbox).startVM.func1+0x22e\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/sandbox.go:1020" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565427114-06:00" level=error msg="#\t0x557c5bc0dbb7\tgithub.com/kata-containers/runtime/virtcontainers.(*Network).Run.func1+0x27\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:1234" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565445296-06:00" level=error msg="#\t0x557c5bbb87d9\tgithub.com/kata-containers/runtime/virtcontainers.doNetNS+0x149\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:920" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565461999-06:00" level=error msg="#\t0x557c5bbbc396\tgithub.com/kata-containers/runtime/virtcontainers.(*Network).Run+0xd6\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:1233" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56547855-06:00" level=error msg="#\t0x557c5bbeb276\tgithub.com/kata-containers/runtime/virtcontainers.(*Sandbox).startVM+0x2d6\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/sandbox.go:1003" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565498311-06:00" level=error msg="#\t0x557c5bb5defe\tgithub.com/kata-containers/runtime/virtcontainers.createSandboxFromConfig+0x21e\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/api.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565515346-06:00" level=error msg="#\t0x557c5bb5dc0f\tgithub.com/kata-containers/runtime/virtcontainers.CreateSandbox+0x11f\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/api.go:61" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565532182-06:00" level=error msg="#\t0x557c5bb92ee0\tgithub.com/kata-containers/runtime/virtcontainers.(*VCImpl).CreateSandbox+0x90\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/implementation.go:41" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56555054-06:00" level=error msg="#\t0x557c5bc88528\tgithub.com/kata-containers/runtime/pkg/katautils.CreateSandbox+0x418\t\t\t/home/X/go/src/github.com/kata-containers/runtime/pkg/katautils/create.go:161" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565567253-06:00" level=error msg="#\t0x557c5bcb7196\tmain.create+0x7c6\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/create.go:137" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565584976-06:00" level=error msg="#\t0x557c5bcd2861\tmain.glob..func1+0x3e1\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/create.go:79" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565601452-06:00" level=error msg="#\t0x557c5bc974f9\tgithub.com/kata-containers/runtime/vendor/github.com/urfave/cli.HandleAction+0xc9\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/app.go:490" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565621411-06:00" level=error msg="#\t0x557c5bc986c7\tgithub.com/kata-containers/runtime/vendor/github.com/urfave/cli.Command.Run+0x997\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/command.go:210" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565640165-06:00" level=error msg="#\t0x557c5bc95830\tgithub.com/kata-containers/runtime/vendor/github.com/urfave/cli.(*App).Run+0x6b0\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/app.go:255" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565667783-06:00" level=error msg="#\t0x557c5bcc77ec\tmain.createRuntimeApp+0x22c\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:530" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565683593-06:00" level=error msg="#\t0x557c5bcc7cab\tmain.createRuntime+0x7b\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:573" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565699442-06:00" level=error msg="#\t0x557c5bcc7d7d\tmain.main+0x9d\t\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:605" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565714947-06:00" level=error msg="#\t0x557c5b2b7363\truntime.main+0x213\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:200" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565729963-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565743097-06:00" level=error msg="0: 0 [0: 0] @ 0x557c5b617753 0x557c5b64be0e 0x557c5b64bc49 0x557c5b64aae9 0x557c5bbb3cdf 0x557c5bbb365b 0x557c5bbb6560 0x557c5bbb4635 0x557c5bbff07b 0x557c5bc0e059 0x557c5bbb87da 0x557c5bbbc59b 0x557c5bbe9a69 0x557c5bb5de91 0x557c5bb5dc10 0x557c5bb92ee1 0x557c5bc88529 0x557c5bcb7197 0x557c5bcd2862 0x557c5bc974fa 0x557c5bc986c8 0x557c5bc95831 0x557c5bcc77ed 0x557c5bcc7cac 0x557c5bcc7d7e 0x557c5b2b7364 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56576474-06:00" level=error msg="#\t0x557c5b617752\tgithub.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink/nl.ParseRouteAttr+0x182\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:720" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56578617-06:00" level=error msg="#\t0x557c5b64be0d\tgithub.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink.LinkDeserialize+0x8d\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink/link_linux.go:1397" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565805874-06:00" level=error msg="#\t0x557c5b64bc48\tgithub.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink.execGetLink+0x288\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink/link_linux.go:1385" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565823288-06:00" level=error msg="#\t0x557c5b64aae8\tgithub.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink.(*Handle).LinkByName+0x358\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/vishvananda/netlink/link_linux.go:1305" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565840791-06:00" level=error msg="#\t0x557c5bbb3cde\tgithub.com/kata-containers/runtime/virtcontainers.getLinkByName+0x5e\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:371" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565861733-06:00" level=error msg="#\t0x557c5bbb365a\tgithub.com/kata-containers/runtime/virtcontainers.createLink+0x38a\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:347" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565878912-06:00" level=error msg="#\t0x557c5bbb655f\tgithub.com/kata-containers/runtime/virtcontainers.setupTCFiltering+0x12f\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:635" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565895943-06:00" level=error msg="#\t0x557c5bbb4634\tgithub.com/kata-containers/runtime/virtcontainers.xConnectVMNetwork+0x1c4\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:429" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565912488-06:00" level=error msg="#\t0x557c5bbff07a\tgithub.com/kata-containers/runtime/virtcontainers.(*VethEndpoint).Attach+0x6a\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/veth_endpoint.go:91" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56592944-06:00" level=error msg="#\t0x557c5bc0e058\tgithub.com/kata-containers/runtime/virtcontainers.(*Network).Add.func1+0x478\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:1256" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565945691-06:00" level=error msg="#\t0x557c5bbb87d9\tgithub.com/kata-containers/runtime/virtcontainers.doNetNS+0x149\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:920" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565962023-06:00" level=error msg="#\t0x557c5bbbc59a\tgithub.com/kata-containers/runtime/virtcontainers.(*Network).Add+0x1ba\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/network.go:1248" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565978588-06:00" level=error msg="#\t0x557c5bbe9a68\tgithub.com/kata-containers/runtime/virtcontainers.(*Sandbox).createNetwork+0x1c8\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/sandbox.go:866" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.565995421-06:00" level=error msg="#\t0x557c5bb5de90\tgithub.com/kata-containers/runtime/virtcontainers.createSandboxFromConfig+0x1b0\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/api.go:94" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566011864-06:00" level=error msg="#\t0x557c5bb5dc0f\tgithub.com/kata-containers/runtime/virtcontainers.CreateSandbox+0x11f\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/api.go:61" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566029696-06:00" level=error msg="#\t0x557c5bb92ee0\tgithub.com/kata-containers/runtime/virtcontainers.(*VCImpl).CreateSandbox+0x90\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/virtcontainers/implementation.go:41" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56604754-06:00" level=error msg="#\t0x557c5bc88528\tgithub.com/kata-containers/runtime/pkg/katautils.CreateSandbox+0x418\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/pkg/katautils/create.go:161" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566066942-06:00" level=error msg="#\t0x557c5bcb7196\tmain.create+0x7c6\t\t\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/create.go:137" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566084599-06:00" level=error msg="#\t0x557c5bcd2861\tmain.glob..func1+0x3e1\t\t\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/create.go:79" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566100947-06:00" level=error msg="#\t0x557c5bc974f9\tgithub.com/kata-containers/runtime/vendor/github.com/urfave/cli.HandleAction+0xc9\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/app.go:490" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566119134-06:00" level=error msg="#\t0x557c5bc986c7\tgithub.com/kata-containers/runtime/vendor/github.com/urfave/cli.Command.Run+0x997\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/command.go:210" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566135823-06:00" level=error msg="#\t0x557c5bc95830\tgithub.com/kata-containers/runtime/vendor/github.com/urfave/cli.(*App).Run+0x6b0\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/urfave/cli/app.go:255" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566154134-06:00" level=error msg="#\t0x557c5bcc77ec\tmain.createRuntimeApp+0x22c\t\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:530" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566169862-06:00" level=error msg="#\t0x557c5bcc7cab\tmain.createRuntime+0x7b\t\t\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:573" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566185322-06:00" level=error msg="#\t0x557c5bcc7d7d\tmain.main+0x9d\t\t\t\t\t\t\t\t\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/cli/main.go:605" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566200799-06:00" level=error msg="#\t0x557c5b2b7363\truntime.main+0x213\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:200" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566215903-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566229027-06:00" level=error msg="0: 0 [1: 8192] @ 0x557c5b37876f 0x557c5b3780a1 0x557c5b37855d 0x557c5b32461e 0x557c5b74765e 0x557c5b747624 0x557c5b7479af 0x557c5b747972 0x557c5b747e8a 0x557c5b750a9c 0x557c5b7484d9 0x557c5b7484d4 0x557c5b748434 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566246145-06:00" level=error msg="#\t0x557c5b37876e\tbytes.makeSlice+0x6e\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/bytes/buffer.go:232" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566261229-06:00" level=error msg="#\t0x557c5b3780a0\tbytes.(*Buffer).grow+0x170\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/bytes/buffer.go:145" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566277938-06:00" level=error msg="#\t0x557c5b37855c\tbytes.(*Buffer).ReadFrom+0x4c\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/bytes/buffer.go:205" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566293167-06:00" level=error msg="#\t0x557c5b32461d\tio.copyBuffer+0x2fd\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/io/io.go:388" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566308318-06:00" level=error msg="#\t0x557c5b74765d\tio.Copy+0x24d\t\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/io/io.go:364" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566323244-06:00" level=error msg="#\t0x557c5b747623\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.bindataRead+0x213\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/bindata.go:28" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566343286-06:00" level=error msg="#\t0x557c5b7479ae\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.jsonschemaDraft04JSONBytes+0x6e\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/bindata.go:75" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566362683-06:00" level=error msg="#\t0x557c5b747971\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.jsonschemaDraft04JSON+0x31\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/bindata.go:82" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566380927-06:00" level=error msg="#\t0x557c5b747e89\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.Asset+0xc9\t\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/bindata.go:118" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566397875-06:00" level=error msg="#\t0x557c5b750a9b\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.JSONSchemaDraft04+0x3b\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:52" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566414374-06:00" level=error msg="#\t0x557c5b7484d8\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadJSONSchemaDraft04+0x58\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:43" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56643103-06:00" level=error msg="#\t0x557c5b7484d3\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.initResolutionCache+0x53\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/expander.go:62" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566448111-06:00" level=error msg="#\t0x557c5b748433\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.1+0x23\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/expander.go:55" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566465098-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566481812-06:00" level=error arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566496568-06:00" level=error msg="0: 0 [1: 288] @ 0x557c5b29b09e 0x557c5b3b27e7 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3b2382 0x557c5b3b27a5 0x557c5b3aecbe 0x557c5b3ab440 0x557c5b3ae41e 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750570 0x557c5b3aee98 0x557c5b3ab440 0x557c5b3aab5b 0x557c5b3aa535 0x557c5b750c4a 0x557c5b7484a9 0x557c5b7484a4 0x557c5b748434 0x557c5b2b7320 0x557c5b2e2b31" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566518002-06:00" level=error msg="#\t0x557c5b3b27e6\tencoding/json.(*decodeState).objectInterface+0x1c6\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566533901-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566550716-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566568599-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566584731-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566602456-06:00" level=error msg="#\t0x557c5b3b2381\tencoding/json.(*decodeState).valueInterface+0xb1\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1030" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56662111-06:00" level=error msg="#\t0x557c5b3b27a4\tencoding/json.(*decodeState).objectInterface+0x184\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:1097" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566638032-06:00" level=error msg="#\t0x557c5b3aecbd\tencoding/json.(*decodeState).object+0x215d\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:623" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566657215-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566673145-06:00" level=error msg="#\t0x557c5b3ae41d\tencoding/json.(*decodeState).object+0x18bd\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:763" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566688571-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566703999-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566721428-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566736925-06:00" level=error msg="#\t0x557c5b75056f\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON+0x17f\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/schema.go:605" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566755675-06:00" level=error msg="#\t0x557c5b3aee97\tencoding/json.(*decodeState).object+0x2337\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:611" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.56677171-06:00" level=error msg="#\t0x557c5b3ab43f\tencoding/json.(*decodeState).value+0x6f\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:381" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566792454-06:00" level=error msg="#\t0x557c5b3aab5a\tencoding/json.(*decodeState).unmarshal+0x20a\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:179" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566809466-06:00" level=error msg="#\t0x557c5b3aa534\tencoding/json.Unmarshal+0x124\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/encoding/json/decode.go:106" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566824932-06:00" level=error msg="#\t0x557c5b750c49\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.Swagger20Schema+0xb9\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:82" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566843397-06:00" level=error msg="#\t0x557c5b7484a8\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema+0x28\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/spec.go:66" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566862985-06:00" level=error msg="#\t0x557c5b7484a3\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.initResolutionCache+0x23\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/expander.go:61" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566880695-06:00" level=error msg="#\t0x557c5b748433\tgithub.com/kata-containers/runtime/vendor/github.com/go-openapi/spec.init.1+0x23\t\t\t/home/X/go/src/github.com/kata-containers/runtime/vendor/github.com/go-openapi/spec/expander.go:55" arch=amd64 name=kata-runtime pid=16272 source=runtime
Mar 20 10:25:20 X-localhost kata-runtime[16272]: time="2020-03-20T10:25:20.566898079-06:00" level=error msg="#\t0x557c5b2b731f\truntime.main+0x1cf\t\t\t\t\t\t\t\t\t\t\t/usr/local/go/src/runtime/proc.go:188" arch=amd64 name=kata-runtime pid=16272 source=runtime

```

### PR DESCRIPTION
**Pull request by devimc**
Make sure the number of columns in the PCI resource file is greater
or equal to 2, since the first two columns are used to calculate
the PCI bar space.
Add unit test for `isLargeBarSpace()`.

fixes #2542

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
cc @amshinde @Jimmy-Xu

File: virtcontainers/device/manager/utils.go [hunk 1]
```diff
@@ -105,6 +105,11 @@ func isLargeBarSpace(resourcePath string) (bool, error) {
 	suffix := []string{"", "K", "M", "G", "T"}
 	for rIdx, line := range strings.Split(string(buf), "\n") {
 		cols := strings.Fields(line)
+		// start and end columns are required to calculate the size
```
Comment (amshinde) [inline virtcontainers/device/manager/utils.go]: Looks good. 
Just wondering if its documented somewhere what this format should like @Jimmy-Xu ?

File: virtcontainers/device/manager/utils.go [hunk 2]
```diff
@@ -102,30 +102,27 @@ func isLargeBarSpace(resourcePath string) (bool, error) {
...
-		for i := range suffix {
-			if size/1024 < 1 {
-				break
-			}
-			size /= 1024
-			sIdx = i + 1
-		}
+		// Use right shift to convert Bytes to GBytes
+		// This is equivalent to ((end - start + 1) / 1024 / 1024 / 1024)
+		gbSize := (end - start + 1) >> 30
```
Comment (jodh-intel) [inline virtcontainers/device/manager/utils.go]: Paranoia: what about checking to ensure that `end` > `start`?

File: virtcontainers/device/manager/utils_test.go [hunk 3]
```diff
@@ -89,3 +91,44 @@ func TestIsVhostUserSCSI(t *testing.T) {
...
+
+	for _, d := range []testData{
+		{"", false, false},
+		{"\t\n\t  ", false, false},
+		{"abc zyx", false, false},
+		{"abc zyx rgb", false, false},
+		{"abc\t       zyx     \trgb", false, false},
+		{"0x00015\n0x0013", false, false},
+		{"0x00000000c6000000 0x00000000c6ffffff 0x0000000000040200", false, false},
+		{"0x0000383800000000 0x0000383bffffffff 0x000000000014220c", false, true},
```
Comment (jodh-intel) [inline virtcontainers/device/manager/utils_test.go]: If we only care about the first two fields, could you add another entry here for a successful call with only two fields?

**Comment by devimc** [comment]
@jodh-intel changes applied, thanks

**Comment by devimc** [comment]
@Jimmy-Xu  please take a look

**Comment by amshinde** [comment]
@devimc Does this need a backport?

**Comment by devimc** [comment]
@amshinde no, `isLargeBarSpace` didn't land in 1.10 nor 1.9
