### PR TITLE
virtcontainers: Fix unit tests

### LINKED ISSUE #208: virtcontainers: Fix unit tests
Relates to kata-containers/tests#225

### PR DESCRIPTION
**Pull request by sboeuf**
Several failures have been reported through https://github.com/kata-containers/tests/issues/225 regarding our CI. A panic was triggered after our unit tests were reaching the defined timeout of 10s, and we could have bumped this timeout to a bigger value, but the root cause was our bad management of the go routines from our code and from our tests, leaving a lot of go routines behind, and slowing down our tests.

Fixes #208

### CODE REVIEW

**Comment by sboeuf** [comment]
@devimc @grahamwhaley @egernst @bergwolf PTAL and let's merge this ;)

File: virtcontainers/pkg/mock/cc_proxy_mock.go [hunk 1]
```diff
@@ -296,17 +300,30 @@ func (proxy *CCProxyMock) serve() {
 
 // Start invokes mock proxy instance to start listening.
 func (proxy *CCProxyMock) Start() {
+	proxy.stopped = false
 	proxy.startListening()
 	go func() {
 		for {
 			proxy.serve()
+
+			proxy.Lock()
```
Comment (grahamwhaley) [inline virtcontainers/pkg/mock/cc_proxy_mock.go]: Just curious - do you need the locking if you only have one reader and one writer?

**Comment by grahamwhaley** [comment]
Couple of strange things on the failed 17.10 CI - I'll give it a nudge (or is this a known issue @chavafg ?).
From the logs:
```
[env],Tty:false,Stdin:false,Stdout:true,Stderr:true,}" 
# time="2018-04-14T02:06:14Z" level=fatal msg="execing command in container failed: unable to upgrade connection: 404 page not found"
# 1
# rm: cannot remove '/tmp/tmp.bRonNcxVBh/crio/devicemapper/mnt/39c165bd2c9a769327ce7504c6107baea42d08faab2a53f67d578c1b8ab9d820': Device or resource busy
# rm: cannot remove '/tmp/tmp.bRonNcxVBh/crio/devicemapper/mnt/0fdf931ad72a8ccc862ad2376cb0d3b95dc264908a1af5a6d7894546fb9db7a3': Device or resource busy
# rm: cannot remove '/tmp/tmp.bRonNcxVBh/crio-run/devicemapper-containers/200b9202d80ea95734851b07445c36344b5426d452a303317f31c20d760badb9/userdata/shm': Device or resource busy
Build timed out (after 5 minutes). Marking the build as aborted.
```
