### PR TITLE
virtcontainers: Fix TestIsHostDevice test as non-root

### LINKED ISSUE #242: Fix TestIsHostDevice test
`TestIsHostDevice` fails running as non-`root` as it attempts to create a file in `/dev/`.

### PR DESCRIPTION
**Pull request by jodh-intel**
Don't Attempt to create file below `/dev` when running as non-`root`.

Move the logic into a new `TestIsHostDeviceCreateFile` test and skip
unless `root.`

Fixes #242.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

File: virtcontainers/mount_test.go [hunk 1]
```diff
@@ -8,14 +8,15 @@ package virtcontainers
 import (
 	"bytes"
 	"fmt"
-	"github.com/stretchr/testify/assert"
```
Comment (grahamwhaley) [inline virtcontainers/mount_test.go]: How did that ever pass the fmt checks? :-/

**Comment by grahamwhaley** [comment]
CI 16.04 - is this expected?:
```
Summarizing 1 Failure:

[Fail] docker privileges check no-new-privileges flag [It] should display the correct uid 
/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests/integration/docker/privileges_test.go:50
```

**Comment by jodh-intel** [comment]
That no-new-privs issue seems to be intermittent - do you have any further info on this @chavafg, @GabyCT?

File: virtcontainers/mount_test.go (hunk 1 above)
Comment (jodh-intel) [reply virtcontainers/mount_test.go]: Well tbh I'm wondering how this entire test can have not failed under the CI until now as we should be launching the tests in the CI as a non-root user and allowing the tests to elevate privs to `root` and re-run.

Any thoughts on that @chavafg, @GabyCT, @amshinde?

**Comment by chavafg** [comment]
not really, haven't seen this failure before, sending a retry... and I'll open an issue for this. If we found it again, we can start investigating more. If not, we can close the issue.

**Comment by amshinde** [comment]
My understanding was that we had added a special case for virtcontainers in the CI to run the virtcontainers tests as root as they need root privileges for other reasons as well.

**Comment by jodh-intel** [comment]
@amshinde - ah - that rings a bell. The problem is we need the skips for running tests locally.

**Comment by jodh-intel** [comment]
Yes, it's rather delicate. Some of the tests absolutely require `root` whereas others must run as non-priv.

+1 for minimising `root` usage but I'd encourage *everyone* to read the test script below carefully in the context of the tests you're either writing or planning to run:

- https://github.com/kata-containers/tests/blob/master/.ci/go-test.sh
