### PR TITLE
virtcontainers: Don't ignore container mounts based on their path

### LINKED ISSUE #116: kube-dns pod cannot start using Kata Containers
# Description of problem

When trying to launch kubelet using kata-containers, I got some errors when creating the kube-dns pods. 

# Expected result

kube-dns pod should run successfully.

# Actual result

Kube-dns failed to start successfully.

```
fuentess@k8s-kata:~/go/src/github.com/kata-containers/tests/integration/kubernetes$ sudo -E kubectl get pods --all-namespaces
NAMESPACE     NAME                               READY     STATUS                 RESTARTS   AGE
kube-system   etcd-k8s-kata                      1/1       Running                0          48s
kube-system   kube-apiserver-k8s-kata            1/1       Running                0          39s
kube-system   kube-controller-manager-k8s-kata   1/1       Running                0          34s
kube-system   kube-dns-6f4fd4bdf-hdcll           0/3       CreateContainerError   0          1m
kube-system   kube-flannel-ds-lrwbg              2/2       Running                0          43s
kube-system   kube-proxy-bwrw6                   1/1       Running                0          1m
kube-system   kube-scheduler-k8s-kata            1/1       Running                0          45s
```

Kata-runtime log shows this error:
```
Mar 26 17:33:36 k8s-kata kata-runtime[95067]: time="2018-03-26T17:33:36.628786037Z" level=error msg="rpc error: code = Internal desc = Could not run process: container_linux.go:296: starting container process caused \"process_linux.go:398: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/var/run/containers/storage/overlay-containers/c5f4f4fd2ae75434e8912044aa2af6880d1a4883e3fed31ae1677ec2c9c0aead/userdata/shm\\\\\\\" to rootfs \\\\\\\"/run/kata-containers/shared/containers/3d7b1511042a2e33b53d1060c15d8049cacd31442f090d6abb06a32206ce6464/rootfs\\\\\\\" at \\\\\\\"/dev/shm\\\\\\\" caused \\\\\\\"stat /var/run/containers/storage/overlay-containers/c5f4f4fd2ae75434e8912044aa2af6880d1a4883e3fed31ae1677ec2c9c0aead/userdata/shm: no such file or directory\\\\\\\"\\\"\"" command=create name=kata-runtime pid=95067 source=runtime
```

Using:
CRI-O version 1.9.10
Kubernetes version 1.9.3
crictl version 1.0.0-alpha.0

# Logs:

kata-runtime log:
```
Mar 26 17:33:36 k8s-kata kata-runtime[95067]: time="2018-03-26T17:33:36.555308397Z" level=info arguments="\"create --bundle /var/run/containers/storage/overlay-containers/3d7b1511042a2e33b53d1060c15d8049cacd31442f090d6abb06a32206ce6464/userdata --pid-file /var/run/containers/storage/overlay-containers/3d7b1511042a2e33b53d1060c15d8049cacd31442f090d6abb06a32206ce6464/userdata/pidfile 3d7b1511042a2e33b53d1060c15d8049cacd31442f090d6abb06a32206ce6464\"" command=create commit=184662416d5e0fa45fa88b2facf7a0863cdce4c0 name=kata-runtime pid=95067 source=runtime version=0.1.0
Mar 26 17:33:36 k8s-kata kata-runtime[95067]: time="2018-03-26T17:33:36.557748588Z" level=info msg="Virtual endpoint unmarshalled [{{e4dcdc2e-c233-47a2-8037-6b9d1fc47266 br0 {eth0 02:00:ca:fe:00:00 [10.244.0.3/24 eth0]} {tap0 0a:58:0a:f4:00:03 []} 2 [0xc42000e1b8 0xc42000e1c8 0xc42000e1d0 0xc42000e1d8 0xc42000e1e0 0xc42000e1e8 0xc42000e1f0 0xc42000e1f8] [0xc42000e200 0xc42000e208 0xc42000e210 0xc42000e218 0xc42000e2200xc42000e228 0xc42000e230 0xc42000e238]} {{{3 1450 0 eth0 0a:58:0a:f4:00:03 up|broadcast|multicast 69699 20 0 <nil>  0xc420174240 0 0xc4200775e0 ether <nil> up 0 0 0} veth} [10.244.0.3/24 eth0 fe80::9419:f5ff:feb1:3c27/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=95067 source=virtcontainers
Mar 26 17:33:36 k8s-kata kata-runtime[95067]: time="2018-03-26T17:33:36.558562118Z" level=debug msg="converting /run/containers/storage/overlay-containers/3d7b1511042a2e33b53d1060c15d8049cacd31442f090d6abb06a32206ce6464/userdata/config.json" name=kata-runtime pid=95067 source=virtcontainers/oci
Mar 26 17:33:36 k8s-kata kata-runtime[95067]: time="2018-03-26T17:33:36.560397286Z" level=debug msg="container rootfs: /var/lib/containers/storage/overlay/37eccfa6ec3f2e8a1857ae02c6d48c30c26bfea45163058f0404d034bab9b2f5/merged" name=kata-runtime pid=95067 source=virtcontainers/oci
Mar 26 17:33:36 k8s-kata kata-runtime[95067]: time="2018-03-26T17:33:36.56183304Z" level=info msg="Virtual endpoint unmarshalled [{{e4dcdc2e-c233-47a2-8037-6b9d1fc47266 br0 {eth0 02:00:ca:fe:00:00 [10.244.0.3/24 eth0]} {tap0 0a:58:0a:f4:00:03 []} 2 [0xc42000eca8 0xc42000ecb0 0xc42000ecb8 0xc42000ecc0 0xc42000ecc8 0xc42000ecd0 0xc42000ecd8 0xc42000ece0] [0xc42000ece8 0xc42000ecf0 0xc42000ecf8 0xc42000ed00 0xc42000ed08 0xc42000ed10 0xc42000ed18 0xc42000ed20]} {{{3 1450 0 eth0 0a:58:0a:f4:00:03 up|broadcast|multicast 69699 20 0 <nil>  0xc420174600 0 0xc4202448a0 ether <nil> up 0 0 0} veth} [10.244.0.3/24 eth0 fe80::9419:f5ff:feb1:3c27/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=95067 source=virtcontainers
Mar 26 17:33:36 k8s-kata kata-runtime[95067]: time="2018-03-26T17:33:36.562670071Z" level=info msg="device details" arch=amd64 container-id=3d7b1511042a2e33b53d1060c15d8049cacd31442f090d6abb06a32206ce6464 device-major=0 device-minor=224 mount-point=/var/lib/containers/storage/overlay/37eccfa6ec3f2e8a1857ae02c6d48c30c26bfea45163058f0404d034bab9b2f5/merged name=kata-runtime pid=95067 pod-id=c5f4f4fd2ae75434e8912044aa2af6880d1a4883e3fed31ae1677ec2c9c0aead source=virtcontainers subsystem=container
Mar 26 17:33:36 k8s-kata kata-runtime[95067]: time="2018-03-26T17:33:36.566583517Z" level=debug msg="Replacing OCI mount (/etc/resolv.conf) source /var/run/containers/storage/overlay-containers/c5f4f4fd2ae75434e8912044aa2af6880d1a4883e3fed31ae1677ec2c9c0aead/userdata/resolv.conf with /run/kata-containers/shared/containers/3d7b1511042a2e33b53d1060c15d8049cacd31442f090d6abb06a32206ce6464-f2522c59291cba4b-resolv.conf" arch=amd64 name=kata-runtime pid=95067 source=virtcontainers subsystem=kata_agent
Mar 26 17:33:36 k8s-kata kata-runtime[95067]: time="2018-03-26T17:33:36.56666062Z" level=debug msg="Replacing OCI mount (/etc/hostname) source /var/run/containers/storage/overlay-containers/c5f4f4fd2ae75434e8912044aa2af6880d1a4883e3fed31ae1677ec2c9c0aead/userdata/hostname with /run/kata-containers/shared/containers/3d7b1511042a2e33b53d1060c15d8049cacd31442f090d6abb06a32206ce6464-08d493fd65dbc4f3-hostname" arch=amd64 name=kata-runtime pid=95067 source=virtcontainers subsystem=kata_agent
Mar 26 17:33:36 k8s-kata kata-runtime[95067]: time="2018-03-26T17:33:36.566730023Z" level=debug msg="Replacing OCI mount (/etc/hosts) source /var/lib/kubelet/pods/82cf3b73-311b-11e8-90c3-000d3af77469/etc-hosts with /run/kata-containers/shared/containers/3d7b1511042a2e33b53d1060c15d8049cacd31442f090d6abb06a32206ce6464-134a6111d4d68680-hosts" arch=amd64 name=kata-runtime pid=95067 source=virtcontainers subsystem=kata_agent
Mar 26 17:33:36 k8s-kata kata-runtime[95067]: time="2018-03-26T17:33:36.628786037Z" level=error msg="rpc error: code = Internal desc = Could not run process: container_linux.go:296: starting container process caused \"process_linux.go:398: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/var/run/containers/storage/overlay-containers/c5f4f4fd2ae75434e8912044aa2af6880d1a4883e3fed31ae1677ec2c9c0aead/userdata/shm\\\\\\\" to rootfs \\\\\\\"/run/kata-containers/shared/containers/3d7b1511042a2e33b53d1060c15d8049cacd31442f090d6abb06a32206ce6464/rootfs\\\\\\\" at \\\\\\\"/dev/shm\\\\\\\" caused \\\\\\\"stat /var/run/containers/storage/overlay-containers/c5f4f4fd2ae75434e8912044aa2af6880d1a4883e3fed31ae1677ec2c9c0aead/userdata/shm: no such file or directory\\\\\\\"\\\"\"" command=create name=kata-runtime pid=95067 source=runtime
Mar 26 17:33:36 k8s-kata kata-runtime[95093]: time="2018-03-26T17:33:36.64040797Z" level=debug msg="loaded configuration" command=delete format=TOML name=kata-runtime pid=95093 source=runtime
Mar 26 17:33:36 k8s-kata kata-runtime[95093]: time="2018-03-26T17:33:36.641091296Z" level=info arguments="\"delete --force 3d7b1511042a2e33b53d1060c15d8049cacd31442f090d6abb06a32206ce6464\"" command=delete commit=184662416d5e0fa45fa88b2facf7a0863cdce4c0 name=kata-runtime pid=95093 source=runtime version=0.1.0
Mar 26 17:33:36 k8s-kata kata-runtime[95093]: time="2018-03-26T17:33:36.644777033Z" level=info msg="Virtual endpoint unmarshalled [{{e4dcdc2e-c233-47a2-8037-6b9d1fc47266 br0 {eth0 02:00:ca:fe:00:00 [10.244.0.3/24 eth0]} {tap0 0a:58:0a:f4:00:03 []} 2 [0xc4201d2160 0xc4201d2170 0xc4201d2178 0xc4201d2180 0xc4201d2188 0xc4201d2190 0xc4201d2198 0xc4201d21a0] [0xc4201d21a8 0xc4201d21b0 0xc4201d21b8 0xc4201d21c0 0xc4201d21c80xc4201d21d0 0xc4201d21d8 0xc4201d21e0]} {{{3 1450 0 eth0 0a:58:0a:f4:00:03 up|broadcast|multicast 69699 20 0 <nil>  0xc420244180 0 0xc4201b70a0 ether <nil> up 0 0 0} veth} [10.244.0.3/24 eth0 fe80::9419:f5ff:feb1:3c27/64] [{Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/24 Src: 10.244.0.3 Gw: <nil> Flags: [] Table: 254} {Ifindex: 3 Dst: 10.244.0.0/16 Src: <nil> Gw: 10.244.0.1 Flags: [] Table: 254} {Ifindex: 3 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}] {[]  [] []}} false virtual}]" arch=amd64 name=kata-runtime pid=95093 source=virtcontainers
Mar 26 17:33:36 k8s-kata kata-runtime[95093]: time="2018-03-26T17:33:36.646079582Z" level=error msg="Container ID (3d7b1511042a2e33b53d1060c15d8049cacd31442f090d6abb06a32206ce6464) does not exist" command=delete name=kata-runtime pid=95093 source=runtime
```

Nothing relevant in kata-shim or kata-proxy logs.

### LINKED ISSUE #122: virtcontainers: Don't ignore container mounts based on their path
Instead of ignoring containers based on their path, we should rely on the type being `bind` to choose if this mount should be ignored or not.
Indeed, we have use cases where k8s expects `/dev/container-log` to be bind mounted inside the container, but the current code will ignore it because it has the prefix `/dev` which is a system prefix mount.

### PR DESCRIPTION
**Pull request by sboeuf**
Instead of ignoring containers based on their path, this commit
relies on the type of mount being "bind" to choose if this mount
should be ignored or not.

For instance, we have some use cases where k8s expects the path
"/dev/container-log" to be bind mounted inside the container, but
the code ignores it because it has the prefix "/dev" which is a
system prefix mount.

Fixes #116 #122

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

File: virtcontainers/container.go [hunk 1]
```diff
@@ -300,7 +300,7 @@ func (c *Container) createContainersDirs() error {
 func (c *Container) mountSharedDirMounts(hostSharedDir, guestSharedDir string) ([]Mount, error) {
 	var sharedDirMounts []Mount
 	for idx, m := range c.mounts {
-		if isSystemMount(m.Destination) || m.Type != "bind" {
+		if m.Type != "bind" {
```
Comment (bergwolf) [inline virtcontainers/container.go]: This would e.g., bind mount host `/proc` to a sub-directory of the shared dir. I'm not sure that we would want it.

Comment (sboeuf) [reply virtcontainers/container.go]: @bergwolf well no cause in case of `/proc`, the source type is `proc`. Same thing for `/dev/pts`, the type is `devpts`.
But at the same time we can have something like `/dev/termination-log` where the type is `bind`, which is case where we actually want to bind mount this through the shared dir.

One other way to proceed would be to provide an exhaustive list of the paths we don't want to consider, but this looks more tedious, and we would have to anticipate everything.

WDYT ?

Comment (bergwolf) [reply virtcontainers/container.go]: yeah, you are right. Thanks for the explanation.

**Comment by bergwolf** [comment]
lgtm

File: virtcontainers/container.go (hunk 1 above)
Comment (sboeuf) [reply virtcontainers/container.go]: No problem ! Glad you agree.

File: virtcontainers/kata_agent.go [hunk 2]
```diff
@@ -570,8 +570,6 @@ func constraintGRPCSpec(grpcSpec *grpc.Spec) {
 			grpcSpec.Mounts[idx].Type = "tmpfs"
 			grpcSpec.Mounts[idx].Source = "shm"
 			grpcSpec.Mounts[idx].Options = []string{"noexec", "nosuid", "nodev", "mode=1777", "size=65536k"}
-
-			break
```
Comment (jodh-intel) [inline virtcontainers/kata_agent.go]: I don't understand how this change relates to bind mounts?

Comment (sboeuf) [reply virtcontainers/kata_agent.go]: Oh yeah this one was a slightly different fix that is also needed. Let me split that in a different commit.

**Comment by sboeuf** [comment]
@jodh-intel @egernst Updated !

**Comment by jodh-intel** [comment]
lgtm

**Comment by egernst** [comment]
Waiting for CI to turn green...

**Comment by chavafg** [comment]
I see an error from the `log-parser` tool:

```
ERROR: kata-log-parser: failed to parse agent log entry {Count:0 TimeDelta:0 Filename:/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests/kata-proxy.log Line:40213 Time:2018-03-28 16:46:15.612334551 +0000 UTC Pid:11669 Level:info Msg:time="2018-03-28T16:46:15.591557266Z" level=debug msg="process exited" name=kata-agent pid=204 source=agent status=1[    2.329912] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
 Source:agent Name:kata-proxy Data:map[]}: key "0000" already exists in map with value "" (entry: &{Count:0 TimeDelta:0 Filename:/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests/kata-proxy.log Line:1 Time:2018-03-28 16:46:15.591557266 +0000 UTC Pid:204 Level:debug Msg:process exited Source:agent Name:kata-agent Data:map[CS:: 0010: DS:: 0000: ES:: status:1[ 2.329912]:]}) (entry: {Count:0 TimeDelta:0 Filename:/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests/kata-proxy.log Line:1 Time:2018-03-28 16:46:15.591557266 +0000 UTC Pid:204 Level:debug Msg:process exited Source:agent Name:kata-agent Data:map[DS:: 0000: ES:: status:1[ 2.329912]: CS:: 0010:]})
```

**Comment by jodh-intel** [comment]
@sboeuf, @bergwolf, @grahamwhaley - the error from the `kata-log-parser` above appears to be a real bug. The kernel appears to have oops-ed to the console:

```
[    2.329912] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
```

That's all the was captured it seems:

- http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-runtime-ubuntu-16-04-PR/117/consoleText

**Comment by grahamwhaley** [comment]
There is this extra bit under there that may give more of a clue:
```
 Source:agent Name:kata-proxy Data:map[]}: key "0000" already exists in map with value "" (entry: &{Count:0 TimeDelta:0 Filename:/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests/kata-proxy.log Line:1 Time:2018-03-28 16:46:15.591557266 +0000 UTC Pid:204 Level:debug Msg:process exited Source:agent Name:kata-agent Data:map[CS:: 0010: DS:: 0000: ES:: status:1[ 2.329912]:]}) (entry: {Count:0 TimeDelta:0 Filename:/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests/kata-proxy.log Line:1 Time:2018-03-28 16:46:15.591557266 +0000 UTC Pid:204 Level:debug Msg:process exited Source:agent Name:kata-agent Data:map[DS:: 0000: ES:: status:1[ 2.329912]: CS:: 0010:]})
```
