### PR TITLE
virtcontainers: fix invalid CPU topology

### LINKED ISSUE #1605: qemu: warning: Invalid CPU topology deprecated
Next warning is thrown in qemu 4

```
qemu-system-x86_64: warning: Invalid CPU topology deprecated: sockets * cores * threads != maxcpus (8)
```

This warning in the future will be an error, see https://patchwork.kernel.org/patch/10655799/

### PR DESCRIPTION
**Pull request by devimc**
sockets * cores * threads should be equal to maxcpus otherwise a
warning is thrown: 'warning: Invalid CPU topology deprecated:
    sockets * cores * threads != maxcpus'

This warning in the future will be an error and won't be possible to run
kata containers.

fixes #1605

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: virtcontainers/qemu_arch_base.go [hunk 1]
```diff
@@ -257,7 +257,7 @@ func (q *qemuArchBase) bridges(number uint32) []types.PCIBridge {
 func (q *qemuArchBase) cpuTopology(vcpus, maxvcpus uint32) govmmQemu.SMP {
 	smp := govmmQemu.SMP{
 		CPUs:    vcpus,
-		Sockets: vcpus,
+		Sockets: maxvcpus,
```
Comment (grahamwhaley) [inline virtcontainers/qemu_arch_base.go]: (thought I'd left this question already - maybe it was on a parallel PR or Issue???)
@devimc - does this have any performance impacts? iirc, way back when we first played with topologies there was discussion that different topologies could affect performance. Did you measure with the metrics report by chance?

Comment (devimc) [reply virtcontainers/qemu_arch_base.go]: @grahamwhaley metrics-CI is happy, do you want me to run a specific test?

**Comment by grahamwhaley** [comment]
@devimc - nope, thats fine. Fair point. Maybe it made more of a difference when we used to set the default ncpu to >=4 etc. Now we set to 1 and use hotplug, maybe we won't notice (at least not in the default container case). Hmm, maybe we need some metrics using ncpu > 1 :-)

Just for ref, metrics looks good with:

```
21:34:47 +-----+----------------------+-------+--------+--------+-------+--------+--------+-------+------+-----+
21:34:47 | P/F |         NAME         |  FLR  |  MEAN  |  CEIL  |  GAP  |  MIN   |  MAX   |  RNG  | COV  | ITS |
21:34:47 +-----+----------------------+-------+--------+--------+-------+--------+--------+-------+------+-----+
21:34:47 | P   | boot-times           | 95.0% | 102.8% | 105.0% | 10.0% | 93.4%  | 122.1% | 30.7% | 6.0% |  20 |
21:34:47 | P   | memory-footprint     | 95.0% | 100.3% | 105.0% | 10.0% | 100.3% | 100.3% | 0.0%  | 0.0% |   1 |
21:34:47 | P   | memory-footprint-ksm | 95.0% | 101.8% | 105.0% | 10.0% | 101.8% | 101.8% | 0.0%  | 0.0% |   1 |
21:34:47 +-----+----------------------+-------+--------+--------+-------+--------+--------+-------+------+-----+
```

**Comment by grahamwhaley** [comment]
Nudged fedora CI rebuild - looked like a net timeout.
Of course, when this lands, we'll also need to tweak the [metrics CI bounds checks](https://github.com/kata-containers/tests/tree/master/cmd/checkmetrics/ci_slaves). Now, it would be *great* if somebody other than me did this - so we can [spread the love](https://en.wikipedia.org/wiki/Bus_factor) - and not have me as the bottleneck...
In my head I'm even thinking 'he who broke it, fixes it'... heh.
