### PR TITLE
selinux: Disable selinux

### LINKED ISSUE #2442: Disable selinux
Kata fails when selinux policy is enforced and the container manager passes those labels in the OCI spec as reported in this issue:
https://github.com/kata-containers/runtime/issues/784

We should implement support for selinux. The first basic step would be to add selinux file system mount in the guest.
Before implementing support for selinux, lets disable it by not passing the selinux labels to the container running in the guest, to unblock users running kata on a system with selinux policy enforced.

### PR DESCRIPTION
**Pull request by amshinde**
Till we implement support for selinux, disable selinux
by not passing selinux labels in the container spec.

Fixes #2442

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
as per @c3d comments - I'm not a fan of silently disabling a feature. It's a security feature, the user has asked for it (even if it was implicit and they did not know they had), and we silently disabled it.
At minimum we need to issue a warning somewhere (which, sadly is likely to be in a log nobody reads, because the container launch will 'work', so nobody has any reason to check the logs....).

**Comment by grahamwhaley** [comment]
I guess... in the spirit of moving forwards ;-), if we:
- can make this issue an appropriate warning
- and document in the Limitations document that although selinux is **not supported**, the runtime will moderately silently disable it, whilst logging a warning
- and we work towards the longer term solution of implementing selinux support for kata....

then, ack!

File: virtcontainers/kata_agent.go [hunk 1]
```diff
@@ -1019,6 +1019,12 @@ func constraintGRPCSpec(grpcSpec *grpc.Spec, passSeccomp bool) {
 		grpcSpec.Linux.Seccomp = nil
 	}
 
+	// Disable selinux
+	if grpcSpec.Process.SelinuxLabel != "" {
+		k.Logger().Warnf("Selinux label specified in config, but not supported in Kata yet, running container without selinux")
```
Comment (grahamwhaley) [inline virtcontainers/kata_agent.go]: nitpick, for which I don't know if you might fail the CI - but, you don't need `Warnf` if you have no % formatters in the string - you might be able to just use `Warn` :-)

Comment (c3d) [reply virtcontainers/kata_agent.go]: Looks good to me with this change, but I am not a member, so I cannot approve.
